import {test} from 'node:test';import assert from 'node:assert/strict';
import {emptyState,save,load,setWishStatus,addGoal,completeDay,diary,result,normalize,STORAGE_KEY,BACKUP_KEY} from '../src/state.js';
import {days,day3} from '../src/program.js';
class Storage{constructor(){this.data=new Map()}getItem(k){return this.data.get(k)||null}setItem(k,v){this.data.set(k,v)}}
test('Полный маршрут: три желания, радость, благодарность, цель и все дни сохраняются',()=>{const store=new Storage(),s=emptyState();s.intention[0]='Услышать свои желания';for(const [i,text]of ['Увидеть океан','Научиться петь','Узнать историю семьи'].entries())s.wishes.push({id:'w'+i,text,category:i===0?'Хочу иметь':'',status:'active'});s.tasks.push({id:'task',text:'Прогуляться',date:'2026-10-07',kind:2,day:2,done:true,joy:true,feeling:'Тепло и спокойно'});s.resources.push({id:'resource',text:'Мой опыт',kind:1});s.answers['gratitude-self']={0:'За смелость'};s.evenings['day3:2026-10-07']={day:3,date:'2026-10-07',closed:true,answers:{0:'Прогулка',1:'За внимание к себе'}};const g=addGoal(s,'w0');g.step='Выбрать дату поездки';g.importance='Простор';g.why='Свобода';for(let d=0;d<=5;d++)completeDay(s,d);s.final[0]='Лучше слышу себя';s.finished=true;save(store,s);const reopened=load(store);assert.deepEqual(reopened,s);assert.equal(reopened.goals[0].title,'Увидеть океан');assert.equal(reopened.goals[0].wishId,'w0');assert(diary(reopened).some(e=>e.text==='Тепло и спокойно'));assert.equal(result(s).wishes,3);assert.equal(result(s).joys,2);assert.equal(result(s).gratitude,2)});
test('Все переходы работают без желаний, целей, категории и необязательных ответов',()=>{const s=emptyState();for(let d=0;d<=5;d++)assert.equal(completeDay(s,d),d===5?'final':`day/${d+1}`);assert.equal(s.completed.length,6)});
test('Исполнение и архив обратимы и не создают цели',()=>{const s=emptyState();s.wishes=[{id:'w',text:'Желание',status:'active'}];setWishStatus(s,'w','fulfilled');assert.equal(result(s).fulfilled,1);setWishStatus(s,'w','active');setWishStatus(s,'w','archived');assert.equal(s.wishes.length,1);setWishStatus(s,'w','active');assert.equal(s.wishes[0].status,'active');assert.equal(s.goals.length,0)});
test('Неповрежденная предыдущая запись восстанавливается из резервной копии',()=>{const store=new Storage(),s=emptyState();s.intention[0]='Ответ';save(store,s);s.intention[0]='Новый ответ';save(store,s);store.setItem(STORAGE_KEY,'broken');assert.equal(load(store).intention[0],'Ответ');assert(store.getItem(BACKUP_KEY))});
test('Старый экспорт существующего приложения переносит желания и цели',()=>{const s=normalize({intention:['1','2','3','4'],wishes:[{id:'w',text:'Желание',done:true}],goals:[{id:'g',title:'Цель',step:'Шаг'}],blessings:[{id:'b',text:'Ресурс'}]});assert.equal(s.wishes[0].status,'fulfilled');assert.equal(s.goals[0].title,'Цель');assert.equal(s.resources[0].text,'Ресурс');assert.equal(s.intention.length,5)});
test('Шесть точных видео, включая День 3',()=>{assert.equal(days.length,6);assert.equal(day3.videoUrl,'https://www.youtube.com/watch?v=FT-6xy7Sb5A');assert.deepEqual(days.map(d=>new URL(d.videoUrl).searchParams.get('v')),['oMSWPT8n_rY','i63JIcE-h8o','_5e0_pBmWHA','FT-6xy7Sb5A','j9UC8Obctho','c-Lon2UZiIo'])});
