name = "mysite"
main = "time-for-us/backend/worker.mjs"
compatibility_date = "2026-10-07"

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = ["/shadow-transformation", "/shadow-transformation/*", "/for-mama/api/*", "/telegram/webhook", "/time-for-us", "/time-for-us/*"]

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "MAMA_DB"
database_name = "mama365"
database_id = "2ca52e94-aa66-4727-b57a-5a653a1a471d"
migrations_dir = "mama-backend/migrations"

[observability]
enabled = true
