name = "mysite"
main = "mama-backend/worker.mjs"
compatibility_date = "2026-10-07"

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = ["/for-mama/api/*", "/telegram/webhook"]

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "MAMA_DB"
database_name = "mama365"
database_id = "2ca52e94-aa66-4727-b57a-5a653a1a471d"
migrations_dir = "mama-backend/migrations"

[observability]
enabled = true
