/* Center progression is an author-defined 60-hour hypothesis, never a measurement. */
(function(root){
const HOUR=3600000,STEP=60*HOUR;
const scenarios={regular:'Обычный цикл',irregular:'Нерегулярный цикл',perimenopause:'Пременопауза',menopause:'Менопауза',surgery:'После операции',none:'Не отслеживаю цикл'};
function observationTime(row){if(Number.isFinite(row.anchorAt))return row.anchorAt;let made=new Date(row.created),key=`${made.getFullYear()}-${String(made.getMonth()+1).padStart(2,'0')}-${String(made.getDate()).padStart(2,'0')}`;return key===row.date&&Number.isFinite(+made)?+made:new Date(row.date+'T12:00:00').getTime()}
function centerForecast(at,history,entries,config={}){let interval=(Number(config.intervalHours)||60)*HOUR;let list=(history||[]).map(row=>({...row,at:observationTime(row)})).filter(row=>row.at<=+at).sort((a,b)=>a.at-b.at||(a.created||0)-(b.created||0));if(!list.length)return null;let anchor=list.at(-1),ordered=entries.filter(e=>e.type==='centers').sort((a,b)=>config.order?config.order.indexOf(a.number)-config.order.indexOf(b.number):a.number-b.number),idx=ordered.findIndex(e=>e.id===anchor.id);if(idx<0)return null;let steps=Math.floor((+at-anchor.at)/interval),entry=ordered[(idx+steps)%ordered.length];return {entry,anchor,steps,assumed:steps>0,nextAt:new Date(anchor.at+(steps+1)*interval),since:new Date(anchor.at+steps*interval)}}

function centerDay(date,history,entries,config={}){let start=new Date(date);start.setHours(0,0,0,0);let end=new Date(start);end.setDate(end.getDate()+1);let anchors=history.map(row=>({...row,at:observationTime(row)})).filter(row=>Number.isFinite(row.at)).sort((a,b)=>a.at-b.at||(a.created||0)-(b.created||0));let segments=[],t=+start;while(t<+end){let f=centerForecast(new Date(t),history,entries,config),nextAnchor=anchors.find(row=>row.at>t)?.at||Infinity,next=Math.min(+end,nextAnchor,f?+f.nextAt:Infinity);if(!Number.isFinite(next)||next<=t)break;if(f)segments.push({entry:f.entry,from:new Date(t),to:new Date(next),assumed:f.assumed});t=next}let numbers=segments.map(x=>x.entry.number).filter((n,i,a)=>i===0||n!==a[i-1]);return {start,end,segments,numbers,label:numbers.join(' → '),partial:segments.length>0&&+segments[0].from>+start,transitions:segments.slice(1).filter((s,i)=>s.entry.id!==segments[i].entry.id).map(s=>({at:s.from,entry:s.entry,assumed:s.assumed}))}}
function centerHistory(history,entries,until=new Date(),config={}){let sorted=history.map(row=>({...row,at:observationTime(row)})).filter(row=>Number.isFinite(row.at)&&row.at<=+until).sort((a,b)=>a.at-b.at||(a.created||0)-(b.created||0)),out=[];let interval=(Number(config.intervalHours)||60)*HOUR;for(let i=0;i<sorted.length;i++){let row=sorted[i],end=Math.min(+until,sorted[i+1]?.at??Infinity);out.push({id:row.id,at:new Date(row.at),method:row.method||'Определение пользователя',assumed:false});for(let at=row.at+interval;at<end&&out.length<3000;at+=interval){let f=centerForecast(new Date(at),[row],entries,config);if(f)out.push({id:f.entry.id,at:new Date(at),method:'Автоматический прогноз',assumed:true})}}return out.sort((a,b)=>b.at-a.at)}

function cycleMode(profile){if(profile.trackCycle===false)return 'none';return scenarios[profile.cycleScenario]?profile.cycleScenario:'regular'}
function forecastsAllowed(profile){return cycleMode(profile)==='regular'}
function periodIdeas(goal,contexts){const wanted={project:['start','create'],finance:['focus','finish'],relationships:['connect'],learning:['focus','start'],rest:['rest'],cleanse:['finish','rest'],review:['finish','focus']};let allowed=wanted[goal]||['start'];return contexts.filter(x=>allowed.includes(x.recommendation.mode)).slice(0,3)}
const api={HOUR,STEP,scenarios,observationTime,centerForecast,centerDay,centerHistory,cycleMode,forecastsAllowed,periodIdeas};root.LunaDream=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
