/* Pure calculations shared by UI and verification. Astronomy Engine 2.1.19, MIT. */
(function(root){
const DAY=86400000;const zodiac=['Овен','Телец','Близнецы','Рак','Лев','Дева','Весы','Скорпион','Стрелец','Козерог','Водолей','Рыбы'];
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(s){return new Date(s+'T12:00:00')}
function days(a,b){return Math.round((Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())-Date.UTC(b.getFullYear(),b.getMonth(),b.getDate()))/DAY)}
function shift(d,n){let out=new Date(d);out.setDate(out.getDate()+n);return out}
function moon(date,A){const angle=A.MoonPhase(date);const longitude=A.EclipticGeoMoon(date).lon;const illum=A.Illumination(A.Body.Moon,date).phase_fraction;let prior=A.SearchMoonPhase(0,new Date(+date-32*DAY),40);if(prior&&+prior.date>+date)prior=A.SearchMoonPhase(0,new Date(+date-62*DAY),40);let next=A.SearchMoonPhase(0,new Date(+prior.date+DAY),40);if(next&&+next.date<=+date)prior=next;const age=(+date-+prior.date)/DAY;let phase=angle<5||angle>355?'Новолуние':angle<85?'Растущая Луна':angle<95?'Первая четверть':angle<175?'Растущая выпуклая':angle<185?'Полнолуние':angle<265?'Убывающая Луна':angle<275?'Последняя четверть':'Убывающий серп';return {angle,longitude,illum,age,day:Math.floor(age)+1,zodiac:zodiac[Math.floor(longitude/30)%12],phase,emoji:angle<45?'🌑':angle<90?'🌒':angle<135?'🌓':angle<175?'🌔':angle<185?'🌕':angle<225?'🌖':angle<270?'🌗':'🌘',nextNew:A.SearchMoonPhase(0,date,40).date,nextFull:A.SearchMoonPhase(180,date,40).date}}
function events(date,A){let z=Math.floor(A.EclipticGeoMoon(date).lon/30);let hi=+date;for(let i=0;i<100;i++){hi+=3600000;if(Math.floor(A.EclipticGeoMoon(new Date(hi)).lon/30)!==z)break}let lo=hi-3600000;for(let i=0;i<20;i++){let mid=(lo+hi)/2;if(Math.floor(A.EclipticGeoMoon(new Date(mid)).lon/30)===z)lo=mid;else hi=mid}let l=A.SearchLunarEclipse(date);let s=A.SearchGlobalSolarEclipse(date);return {ingress:new Date(hi),nextSign:zodiac[Math.floor(A.EclipticGeoMoon(new Date(hi+1000)).lon/30)%12],lunar:l.peak.date,lunarKind:l.kind,solar:s.peak.date,solarKind:s.kind}}
function cycle(date,state){let starts=[...(state.cycles||[])].filter(x=>x.date<=dateKey(date)).sort((a,b)=>a.date.localeCompare(b.date));if(!starts.length)return null;let last=starts.at(-1);let length=Number(state.profile.cycleLength)||28;let day=days(date,parseDate(last.date))+1;let bleed=last.duration||state.profile.periodLength||5;let expected=shift(parseDate(last.date),length);let overdue=dateKey(date)>dateKey(expected);let projected=dateKey(date)>dateKey(new Date())&&day>length;let shownDay=projected?(day-1)%length+1:day;let ov=length-14;let phase=shownDay<=bleed?'Менструальная':shownDay<ov-2?'Фолликулярная':shownDay<=ov+2?'Овуляторная':'Лютеиновая';if(overdue&&!projected)phase='Ожидается новая запись';return {day:shownDay,actualDay:day,phase,length,bleed,ovulationDay:ov,fertile:shownDay>=ov-5&&shownDay<=ov+1,expected,overdue,projected}}
function season(date,A,library){let y=date.getFullYear(),seasons=A.Seasons(y),dates={'Остара':seasons.mar_equinox.date,'Лита':seasons.jun_solstice.date,'Мабон':seasons.sep_equinox.date,'Йоль':seasons.dec_solstice.date};let list=library.entries.filter(x=>x.type==='wheel').map(x=>({...x,at:dates[x.title]||parseDate(`${y}-${x.date}`)})).sort((a,b)=>a.at-b.at);let current=list.filter(x=>x.at<=date).at(-1)||{...list.at(-1),at:A.Seasons(y-1).dec_solstice.date};let upcoming=list.find(x=>x.at>date)||{...list[0],at:parseDate(`${y+1}-${list[0].date}`)};return {current,upcoming}}
const api={DAY,dateKey,parseDate,days,shift,moon,events,cycle,season};root.LunaModel=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
