/* Print-first layouts with embedded Cyrillic; overflow is preserved as a designed appendix. */
(function(root){
const groups={must:'Что я должен сделать',want:'Что мне хочется сделать',joy:'Что принесёт мне радость'};
async function create(data,options={}){const C=options.jsPDF||root.jspdf.jsPDF;let font=options.font;if(!font){let bytes=new Uint8Array(await fetch('assets/pdf-text.ttf').then(r=>{if(!r.ok)throw Error('font');return r.arrayBuffer()})),str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));font=btoa(str)}let daily=data.mode==='day',doc=new C({orientation:daily?'portrait':'landscape',unit:'mm',format:daily?'a4':'a3',compress:true}),W=daily?210:420,H=297,pages=1,overflow=[];doc.addFileToVFS('Planner.ttf',font);doc.addFont('Planner.ttf','Planner','normal');doc.setFont('Planner');doc.setLanguage('ru-RU');doc.setProperties({title:'LUNA · '+data.title,author:'Автор: Юлия Стоянова',subject:'Личный лунный планировщик'});
const clean=t=>String(t||'').replace(/\u2192/g,' / ').replace(/[\u2011\u2013\u2014]/g,'-'),colors={ink:'#352f38',muted:'#756b76',gold:'#8b704a',line:'#d8ccb7',paper:'#f7f3ec'};
function text(t,x,y,size=10,color=colors.ink){doc.setFontSize(size);doc.setTextColor(color);doc.text(clean(t),x,y)}
function wrap(t,w,size){doc.setFontSize(size);return doc.splitTextToSize(clean(t),w)}
function block(t,x,y,w,size,maxY,heading){let ls=wrap(t,w,size),step=size*.3528*1.42,fit=Math.max(0,Math.floor((maxY-y)/step)+1);ls.slice(0,fit).forEach((s,i)=>text(s,x,y+i*step,size));if(ls.length>fit)overflow.push({heading,text:ls.slice(fit).join(' ')});return y+Math.min(ls.length,fit)*step}
function base(){doc.setFillColor(colors.paper);doc.rect(0,0,W,H,'F');text('L U N A  /  Л У Н Н Ы Й  П Л А Н',14,14,9,colors.gold);text('Автор: Юлия Стоянова',W-72,11,8,colors.gold);text('yuliastoyanova.com',W-72,17,8,colors.gold);doc.setDrawColor(colors.line);doc.setLineWidth(.25);doc.line(14,23,W-14,23);text('В своём ритме. С вниманием к себе.',14,H-9,8,colors.gold);text(String(pages),W-20,H-9,8,colors.gold)}
function moon(angle,x,y,r){doc.setFillColor('#746b79');doc.circle(x,y,r,'F');let wax=angle<=180,c=Math.cos(angle*Math.PI/180),pts=[];for(let i=0;i<=32;i++){let yy=-1+2*i/32,v=Math.sqrt(Math.max(0,1-yy*yy));pts.push([x+(wax?1:-1)*r*v,y+r*yy])}for(let i=32;i>=0;i--){let yy=-1+2*i/32,v=Math.sqrt(Math.max(0,1-yy*yy));pts.push([x+(wax?c:-c)*r*v,y+r*yy])}let diffs=pts.slice(1).map((p,i)=>[p[0]-pts[i][0],p[1]-pts[i][1]]);doc.setFillColor('#ddd6c9');doc.lines(diffs,pts[0][0],pts[0][1],[1,1],'F',true)}
function ruled(x,y,w,count=3,gap=7){doc.setDrawColor(colors.line);for(let i=0;i<count;i++)doc.line(x,y+i*gap,x+w,y+i*gap)}
function tasksBlock(tasks,x,y,w,bottom,heading,size=10){let list=tasks.filter(t=>t.text?.trim());if(!list.length){for(let i=0;i<3;i++){if(y+8>bottom)break;doc.rect(x,y-2.5,2.7,2.7);ruled(x+8,y,w-8,1);y+=8}return y}for(let t of list){if(y>bottom-4){overflow.push({heading,text:(t.done?'Выполнено: ':'')+t.text});continue}doc.setDrawColor(colors.line);doc.rect(x,y-2.5,2.7,2.7);if(t.done){doc.setDrawColor(colors.gold);doc.line(x+.3,y-1.5,x+1.1,y-.5);doc.line(x+1.1,y-.5,x+2.5,y-2.3)}y=block(t.text,x+7,y,w-7,size,bottom-3,heading)+3}return y}
function sectionPanel(title,x,y,w,h){doc.setFillColor('#fffcf7');doc.setDrawColor(colors.line);doc.roundedRect(x,y,w,h,2,2,'FD');block(title,x+4,y+8,w-8,w<80?9.5:11,y+14,title)}
base();
if(daily){let d=data.days[0];moon(d.angle,184,38,7);text('Мой день в ритме Луны',14,37,20);text(data.title,14,47,11);block(`${d.phase} · ${d.lunarDay||"—"} лунный день · ${d.zodiac}\nЦикл: ${d.cycle} · Центр ${d.center} · ${d.season}`,14,58,182,10,72,'Ритмы дня');sectionPanel('Сегодня для вас',14,79,182,46);block(d.recommendation,18,94,174,10,112,'Рекомендация дня');block('Избегать: '+d.avoid,18,118,174,9,121,'Чего избегать');let col=(182-8)/3;Object.entries(groups).forEach(([key,title],i)=>{let x=14+i*(col+4);sectionPanel(title,x,133,col,78);tasksBlock(d.tasks.filter(t=>(t.group||'must')===key),x+4,153,col-8,203,title,10)});text('ГЛАВНОЕ НАМЕРЕНИЕ',14,223,9,colors.gold);block(d.intention,14,232,182,12,241,'Намерение');text('РИТУАЛ ДНЯ',14,251,9,colors.gold);block(d.ritual.title,14,259,182,11,266,'Ритуал');if(d.meetings||d.ideas||d.notes||d.events.length){overflow.push(...[['Мои встречи',d.meetings],['Мои идеи',d.ideas],['Мои заметки',d.notes],['События дня',d.events.map(e=>(e.time?e.time+' - ':'')+e.title+(e.notes?' - '+e.notes:'')).join('\n')]].filter(([,v])=>v).map(([heading,text])=>({heading,text})))}else{ruled(14,274,182,1)}overflow.push({heading:'Ритуал · '+d.ritual.title,text:Object.entries(d.ritual.fields).filter(([k])=>['Свеча','Цвет','Аромат','Камень','Музыка','Практика','Медитация','Намерение'].includes(k)).map(([k,v])=>k+': '+v).join('\n')});
}else if(data.mode==='week'){text('Моя неделя',14,36,22);text(data.title,14,45,11);text('НАМЕРЕНИЕ НЕДЕЛИ',14,55,8,colors.gold);block(data.meta.intention||'Дать место важному, желанному и радостному.',14,63,392,12,70,'Намерение недели');let gap=2,col=(W-28-gap*6)/7,top=69,bottom=267;data.days.forEach((d,i)=>{let x=14+i*(col+gap);doc.setFillColor('#fffcf7');doc.setDrawColor(colors.line);doc.roundedRect(x,top,col,bottom-top,2,2,'FD');text(d.weekday,x+3,top+8,10,colors.gold);text(d.title,x+3,top+16,12);moon(d.angle,x+col-7,top+7,3);block(`${d.phase} · ${d.lunarDay||"—"} л.д.\nЛуна: ${d.zodiac}\nЦикл: ${d.cycle}\nЦентр: ${d.center}`,x+3,top+25,col-6,8.5,top+45,'Ритмы · '+d.weekday);text('Рекомендуется',x+3,top+52,8,colors.gold);block(d.shortRecommendation,x+3,top+59,col-6,9,top+81,'Рекомендация · '+d.weekday);text('Лучше избегать',x+3,top+88,8,colors.gold);block(d.avoid,x+3,top+95,col-6,8.5,top+108,'Избегать · '+d.weekday);text('Намерение',x+3,top+115,8,colors.gold);block(d.intention,x+3,top+122,col-6,9,top+135,'Намерение · '+d.weekday);let y=top+143;for(let [key,title] of Object.entries(groups)){text(title,x+3,y,7.4,colors.gold);y+=6;let list=d.tasks.filter(t=>(t.group||'must')===key&&t.text?.trim());if(list.length){let first=list[0];doc.setDrawColor(colors.line);doc.rect(x+3,y-2.2,2.3,2.3);if(first.done)text('×',x+3.15,y-.1,8,colors.gold);block(first.text,x+8,y,col-11,8.5,y+8,'Задачи · '+d.weekday+' · '+title);list.slice(1).forEach(t=>overflow.push({heading:d.weekday+' · '+title,text:(t.done?'Выполнено: ':'')+t.text}))}else{doc.rect(x+3,y-2.2,2.3,2.3);ruled(x+9,y,col-12,1)}y+=13}for(let [heading,value] of [['Мои встречи',d.meetings],['Мои идеи',d.ideas],['Мои заметки',d.notes],['События',d.events.map(e=>(e.time?e.time+' - ':'')+e.title+(e.notes?' - '+e.notes:'')).join('\n')]])if(value)overflow.push({heading:d.weekday+' · '+heading,text:value});});let width=(W-32)/3;[['РИТУАЛЫ',data.meta.rituals||data.days.map(d=>d.weekday+': '+d.ritual.title).join('; ')],['ВАЖНЫЕ ДАТЫ',data.meta.dates],['ЗАМЕТКИ',data.meta.notes]].forEach(([h,v],i)=>{let x=14+i*(width+2);text(h,x,274,8,colors.gold);if(v)block(v,x,282,width-5,8.5,284,h);else ruled(x,282,width-5,1)});
}else{let days=data.days,first=new Date(days[0].date+'T12:00:00'),offset=(first.getDay()+6)%7,rows=Math.ceil((offset+days.length)/7),top=77,cellH=rows===6?30:35,col=(W-28)/7;text('Мой месяц',14,36,22);text(data.title,14,45,12);text('НАМЕРЕНИЕ МЕСЯЦА',14,55,8,colors.gold);block(data.meta.intention||'Выбрать главное и оставить место для жизни.',14,63,392,12,68,'Намерение месяца');['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].forEach((t,i)=>text(t,14+i*col+3,top-4,9,colors.gold));days.forEach((d,i)=>{let position=i+offset,x=14+(position%7)*col,y=top+Math.floor(position/7)*cellH;doc.setFillColor('#fffcf7');doc.setDrawColor(colors.line);doc.rect(x,y,col,cellH,'FD');text(String(first.getDate()+i),x+3,y+7,12);moon(d.angle,x+col-7,y+6,3);block(`${d.zodiac} · цикл ${d.cycle}\nЦентр ${d.center}`,x+3,y+14,col-6,7.8,y+22,'Ритмы · '+d.title);let events=d.events.map(e=>(e.time?e.time+' ':'')+e.title),tasks=d.tasks.filter(t=>t.text?.trim());if(events.length)block(events.join('; '),x+3,y+25,col-6,8,y+cellH-3,'События · '+d.title);if(tasks.length||d.meetings||d.ideas||d.notes||d.events.length){overflow.push({heading:d.weekday+', '+d.title,text:'Рекомендация: '+d.shortRecommendation+'\nИзбегать: '+d.avoid+'\nНамерение: '+d.intention+'\n'+Object.entries(groups).map(([k,t])=>t+': '+tasks.filter(v=>(v.group||'must')===k).map(v=>(v.done?'Выполнено - ':'')+v.text).join('; ')).join('\n')+'\nСобытия: '+d.events.map(e=>(e.time?e.time+' ':'')+e.title+(e.notes?' - '+e.notes:'')).join('; ')+'\nВстречи: '+d.meetings+'\nИдеи: '+d.ideas+'\nЗаметки: '+d.notes})}});let y=top+rows*cellH+10;text('ЗАМЕТКИ МЕСЯЦА',14,y,8,colors.gold);if(data.meta.notes)block(data.meta.notes,14,y+7,392,10,279,'Заметки месяца');else ruled(14,y+8,392,2)}
while(overflow.length){let batch=overflow;overflow=[];doc.addPage();pages++;base();text(daily?'Пространство моего дня':'Пространство для деталей',14,36,20);let y=49;for(let item of batch){if(y>260){overflow.push(item);continue}text(item.heading,14,y,11,colors.gold);y+=8;let ls=wrap(item.text,W-28,10),step=5.2,fit=Math.max(1,Math.floor((277-y)/step));ls.slice(0,fit).forEach((l,i)=>text(l,14,y+i*step,10));y+=Math.min(fit,ls.length)*step+10;if(ls.length>fit)overflow.push({heading:item.heading+' (продолжение)',text:ls.slice(fit).join(' ')})}}
return new Uint8Array(doc.output('arraybuffer'));
}
root.LunaPlanningPDF={create};if(typeof module!=='undefined')module.exports={create};
})(typeof globalThis!=='undefined'?globalThis:this);
