/* Deterministic editorial suggestions. Personal observations take precedence. */
(function(root){
let rules={},modes={rest:{label:'Бережный день',action:'Оставить время для отдыха и спокойной прогулки',avoid:'Плотный график без пауз',intention:'Я восстанавливаю силы и уважаю свой темп.'},finish:{label:'Освободить пространство',action:'Завершить одно начатое дело',avoid:'Браться сразу за несколько новых проектов',intention:'Я завершаю важное и освобождаю место для нового.'},focus:{label:'Спокойная ясность',action:'Выделить час для одной важной задачи',avoid:'Отвлекаться на каждое новое сообщение',intention:'Я выбираю главное и сохраняю внимание.'},create:{label:'Творческий импульс',action:'Дать время идее, тексту или творчеству',avoid:'Требовать от первой попытки совершенства',intention:'Я позволяю своим идеям обрести форму.'},connect:{label:'Тёплые связи',action:'Запланировать спокойный разговор с близким человеком',avoid:'Соглашаться на встречи из чувства долга',intention:'Я строю отношения с теплом и честностью.'},start:{label:'Небольшой новый шаг',action:'Сделать один посильный шаг к своей цели',avoid:'Планировать больше, чем есть сил',intention:'Я начинаю с малого и доверяю своему пути.'}};
function recommend(x){let score={rest:0,finish:0,focus:0,create:0,connect:0,start:0},reasons=[];let l=x.l,c=x.c,z=l.zodiac;
if(l.angle<5||l.angle>355){score.rest+=3;score.start+=1;reasons.push('Новолуние предлагает сначала прояснить намерение.')}else if(l.angle<180){score.start+=2;score.create++;reasons.push('Растущая Луна задаёт символическую тему развития.')}else{score.finish+=3;score.rest++;reasons.push('Убывающая Луна поддерживает тему завершения.')}
let element=(rules.zodiacGroups?.fire||['Овен','Лев','Стрелец']).includes(z)?'fire':(rules.zodiacGroups?.earth||['Телец','Дева','Козерог']).includes(z)?'earth':(rules.zodiacGroups?.air||['Близнецы','Весы','Водолей']).includes(z)?'air':'water';let zmode=(rules.elementModes||{fire:'start',earth:'focus',air:'connect',water:'rest'})[element];score[zmode]+=2;reasons.push(`Луна в знаке ${z}: тема ${modes[zmode].label.toLowerCase()}.`);
let daymode=l.day<=3?'rest':l.day<=10?'start':l.day<=16?'create':l.day<=23?'focus':'finish';score[daymode]++;reasons.push(`${l.day}-й день от новолуния — ориентир для ${daymode==='finish'?'подведения итогов':'выбора темпа'}.`);
if(c&&!c.observationOnly&&!c.overdue){let cm=c.phase==='Менструальная'?'rest':c.phase==='Фолликулярная'?'start':c.phase==='Овуляторная'?'connect':'focus';score[cm]+=2;if(c.day>=c.length-3)score.rest+=2;reasons.push(`${c.day}-й день цикла${c.projected?' (прогноз)':''}: нагрузку уточняйте по ощущениям.`)}
let season=(rules.seasonModes||{Имболк:'start',Остара:'start',Белтейн:'connect',Лита:'create',Лугнасад:'focus',Мабон:'finish',Самайн:'rest',Йоль:'rest'})[x.s.current.title]||'focus';score[season]++;reasons.push(`Период ${x.s.current.title}: ${x.s.current.subtitle.toLowerCase()}.`);
if(x.centerDay?.segments.length){let total=x.centerDay.segments.reduce((n,s)=>n+(s.to-s.from),0);for(let seg of x.centerDay.segments){let mode=(rules.centerModes||['connect','start','focus','rest','connect','create','connect','rest','focus','create','rest'])[(seg.entry.number-1)%11];score[mode]+=2*(seg.to-seg.from)/total}reasons.push(`Центры этого дня: ${x.centerDay.label}. Переходы учитываются как авторские предположения.`)}else if(x.center){let n=Number(x.center.number)||1,mode=(rules.centerModes||['connect','start','focus','rest','connect','create','connect','rest','focus','create','rest'])[(n-1)%11];score[mode]+=2;reasons.push(`${x.center.assumed?'Предполагаемый':'Подтверждённый'} центр №${x.center.number}: ${x.center.subtitle.toLowerCase()}.`)}
let low=x.j&&(+x.j.energy<=2||(x.j.sleep!=null&&x.j.sleep!==''&&+x.j.sleep<6));if(low){score.rest+=20;reasons.unshift('Вы отметили мало сил или короткий сон: сегодня оставьте запас на восстановление.')}
let imperative=t=>t.replace(/^(Оставить|Завершить|Выделить|Дать|Запланировать|Сделать)/,v=>({Оставить:'Оставьте',Завершить:'Завершите',Выделить:'Выделите',Дать:'Дайте',Запланировать:'Запланируйте',Сделать:'Сделайте'})[v]);let ranked=Object.keys(score).sort((a,b)=>score[b]-score[a]),main=modes[ranked[0]],good=ranked.slice(0,3).map(k=>modes[k].action);if(x.center?.fields?.Практика)good.push(x.center.fields.Практика);else good.push('Сделать короткую внутреннюю практику и записать наблюдения');
return {mode:ranked[0],label:main.label,good,avoid:[main.avoid,low?'Заменять отдых дополнительными обязательствами':'Принимать важные решения в спешке'],intention:main.intention,text:`${low?'Начните с восстановления. ':''}${imperative(main.action)}. ${imperative(modes[ranked[1]].action)}. ${x.center?`Тема центра №${x.center.number} поможет выбрать личную практику. `:''}В период ${x.s.current.title} оставьте место для ${season==='finish'?'подведения итогов':season==='rest'?'тишины и заботы о себе':'осмысленного движения'}.`,reasons,ritual:ranked[0]==='finish'?'Очищение и благодарность':'Тихое намерение',meditation:'Две минуты мягкого дыхания',color:ranked[0]==='create'?'Фуксия':'Мягкое золото',stone:ranked[0]==='rest'?'Аметист':'Розовый кварц',chakra:ranked[0]==='focus'?'Аджна':'Анахата',aroma:ranked[0]==='rest'?'Лаванда':'Роза'};
}
function monday(d){let date=new Date(d);date.setDate(date.getDate()-(date.getDay()+6)%7);return date}
function aggregate(rows,key){let groups={};for(let r of rows){let k=key(r);if(k==null)continue;let g=groups[k]||(groups[k]={key:k,count:0,total:0});g.count++;g.total+=Number(r.energy)}return Object.values(groups).map(g=>({...g,mean:g.total/g.count})).sort((a,b)=>b.mean-a.mean)}
function setRules(value){if(value?.schemaVersion!==1||!value.modes||Object.keys(modes).some(k=>!value.modes[k]?.action))throw Error('planner rules');rules=value;modes=value.modes}
const api={recommend,monday,aggregate,setRules};root.LunaPlanner=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
