/* LUNA atelier: readable print-first book pages. All overflow survives. */
(function(root){
const groups={must:'Что я должен сделать',want:'Что мне хочется сделать',joy:'Что принесет мне радость'};
const clean=t=>String(t??'').replace(/\u0451/g,'е').replace(/\u0401/g,'Е').replace(/→/g,' / ').replace(/[‑–—]/g,'-');
async function encoded(url){let b=new Uint8Array(await fetch(url).then(r=>{if(!r.ok)throw Error(url);return r.arrayBuffer()})),s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s)}
async function create(data,options={}){const C=options.jsPDF||root.jspdf.jsPDF;let font=options.font||await encoded('assets/pdf-text.ttf'),display=options.displayFont||await encoded('assets/prata.ttf'),art=options.art||{};if(!options.art){let a=await Promise.all(['cosmos','moon-cover','flowers','ritual'].map(async n=>[n,'data:image/jpeg;base64,'+await encoded('assets/atelier/pdf-'+n+'.jpg')]));art=Object.fromEntries(a)}let month=data.mode==='month',W=month?297:210,H=month?210:297,doc=new C({orientation:month?'landscape':'portrait',unit:'mm',format:'a4',compress:true}),page=0,overflow=[];doc.addFileToVFS('AtelierBody.ttf',font);doc.addFont('AtelierBody.ttf','Body','normal');doc.addFileToVFS('AtelierDisplay.ttf',display);doc.addFont('AtelierDisplay.ttf','Display','normal');doc.setLanguage('ru-RU');doc.setProperties({title:'LUNA · '+clean(data.title),author:'Автор: Юлия Стоянова',subject:'Авторский лунный ежедневник'});
const col={ink:'#51445e',soft:'#776982',gold:'#997a49',line:'#d6c5d6',paper:'#fcfaf5',blue:'#eaf1f5',pink:'#f6e9ef',lilac:'#eee8f4'};
function text(t,x,y,size=11,color=col.ink,serif=false){doc.setFont(serif?'Display':'Body');doc.setFontSize(size);doc.setTextColor(color);doc.text(clean(t),x,y)}
function wrap(t,w,size=11,serif=false){doc.setFont(serif?'Display':'Body');doc.setFontSize(size);return doc.splitTextToSize(clean(t),w)}
function block(t,x,y,w,size,maxY,heading,serif=false){let ls=wrap(t,w,size,serif),step=size*.3528*1.5,fit=Math.max(0,Math.floor((maxY-y)/step)+1);ls.slice(0,fit).forEach((s,i)=>text(s,x,y+i*step,size,col.ink,serif));if(ls.length>fit)overflow.push({heading,text:ls.slice(fit).join('\n')});return y+Math.min(ls.length,fit)*step}
function image(n,x,y,w,h,opacity=1){if(!art[n])return;doc.saveGraphicsState();if(doc.GState)doc.setGState(new doc.GState({opacity}));doc.addImage(art[n],'JPEG',x,y,w,h,undefined,'FAST');doc.restoreGraphicsState()}
function base(){if(page++)doc.addPage();doc.setFillColor(col.paper);doc.rect(0,0,W,H,'F');image('cosmos',W-80,0,80,80,.18);image('flowers',0,H-73,75,75,.12);text('L U N A',17,15,10,col.gold);text('Автор: Юлия Стоянова',W-73,12,8.5,col.soft);text('yuliastoyanova.com',W-73,18,8.5,col.soft);doc.link(W-73,14,56,5,{url:'https://yuliastoyanova.com'});doc.setDrawColor(col.line);doc.setLineWidth(.2);doc.line(17,24,W-17,24);doc.saveGraphicsState();if(doc.GState)doc.setGState(new doc.GState({opacity:.28}));doc.setDrawColor(col.gold);doc.setLineWidth(.16);doc.ellipse(W-15,8,25,39);doc.ellipse(W-12,8,27,42);doc.restoreGraphicsState();text('В своем ритме. С вниманием к себе.',17,H-10,9,col.soft);text(page,W-22,H-10,9,col.gold)}
function panel(title,x,y,w,h,color=col.lilac){doc.setFillColor(color);doc.setDrawColor(col.line);doc.roundedRect(x,y,w,h,3,3,'FD');text(title,x+5,y+9,11,col.ink,true)}
function ruled(x,y,w,n=3,gap=7){doc.setDrawColor(col.line);doc.setLineWidth(.18);for(let i=0;i<n;i++)doc.line(x,y+i*gap,x+w,y+i*gap)}
function phase(angle,x,y,r=5){doc.setFillColor('#80718e');doc.circle(x,y,r,'F');let wax=angle<=180,c=Math.cos(angle*Math.PI/180),pts=[];for(let i=0;i<=32;i++){let yy=-1+2*i/32,v=Math.sqrt(Math.max(0,1-yy*yy));pts.push([x+(wax?1:-1)*r*v,y+r*yy])}for(let i=32;i>=0;i--){let yy=-1+2*i/32,v=Math.sqrt(Math.max(0,1-yy*yy));pts.push([x+(wax?c:-c)*r*v,y+r*yy])}doc.setFillColor('#ebe0c9');doc.lines(pts.slice(1).map((p,i)=>[p[0]-pts[i][0],p[1]-pts[i][1]]),pts[0][0],pts[0][1],[1,1],'F',true)}
function taskList(tasks,x,y,w,bottom,heading){let rows=tasks.filter(t=>t.text?.trim());if(!rows.length){for(let i=0;i<3&&y<bottom;i++){doc.setDrawColor(col.line);doc.rect(x,y-2.5,3,3);ruled(x+8,y,w-8,1);y+=8}return}for(let t of rows){if(y>bottom-5){overflow.push({heading,text:(t.done?'Выполнено: ':'')+t.text});continue}doc.setDrawColor(col.line);doc.rect(x,y-2.5,3,3);if(t.done){doc.setDrawColor(col.gold);doc.line(x+.3,y-1.3,x+1.2,y-.3);doc.line(x+1.2,y-.3,x+2.6,y-2.2)}y=block(t.text,x+8,y,w-8,11,bottom-3,heading)+3}}
function quote(t,x,y,w,maxY=H-24){if(!t)return;doc.setDrawColor(col.gold);doc.line(x+w/2-3,y-6,x+w/2+3,y-6);doc.line(x+w/2,y-9,x+w/2,y-3);block(t,x,y,w,13,maxY,'Слова для вдохновения',true)}
function cover(title,subtitle){base();text(title,17,43,24,col.ink,true);text(subtitle,17,56,12,col.soft);image('moon-cover',35,66,140,140);quote(data.quotes?.[0]||'Пусть сегодняшний день станет тихим шагом навстречу себе.',25,227,160,260);if(data.name)text(data.name,17,277,12,col.gold)}
function dayPage(d,caption,withJournal=false){base();text(caption,17,41,22,col.ink,true);text(d.weekday+', '+d.title,17,51,12,col.soft);phase(d.angle,185,40,7);block(`${d.phase} · ${d.lunarDay||'—'} лунный день · ${d.zodiac}\nЦикл: ${d.cycle} · Центр: ${d.center} · ${d.season}`,17,64,176,11,75,'Ритмы · '+d.title);panel('Сегодня для вас',17,85,176,65,col.blue);block(d.recommendation,22,103,166,11,134,'Рекомендация · '+d.title);block('Лучше избегать: '+d.avoid,22,141,166,10.5,149,'Лучше избегать · '+d.title);
let gap=5,w=(176-gap*2)/3;Object.entries(groups).forEach(([key,title],i)=>{let x=17+i*(w+gap);doc.setFillColor([col.lilac,col.pink,col.blue][i]);doc.setDrawColor(col.line);doc.roundedRect(x,156,w,65,3,3,'FD');block(title,x+5,166,w-10,11,178,title,true);taskList(d.tasks.filter(t=>(t.group||'must')===key),x+5,187,w-10,213,d.title+' · '+title)});text('Главное намерение',17,232,12,col.gold,true);block(d.intention,17,242,176,12,253,'Намерение · '+d.title);text('Ритуал дня',17,267,11,col.gold,true);block(d.ritual.title,17,276,176,11,278,'Ритуал · '+d.title);
let details=[['Мои встречи',d.meetings],['Мои идеи',d.ideas],['Мои заметки',d.notes],['События',d.events.map(e=>(e.time?e.time+' - ':'')+e.title+(e.notes?' - '+e.notes:'')).join('\n')]];details.filter(([,v])=>v).forEach(([heading,text])=>overflow.push({heading:d.title+' · '+heading,text}));if(data.mode==='day'||withJournal)for(let [heading,value] of Object.entries(d.ritual.fields))overflow.push({heading:d.title+' · '+heading,text:value});if(withJournal)journalPage(d)}
function journalPage(d){base();text('Мои наблюдения',17,41,23,col.ink,true);text(d.title,17,52,12,col.soft);let j=d.journal||{},metrics=`Энергия: ${j.energy??'—'}/5 · Настроение: ${j.mood||'—'} · Сон: ${j.sleep??'—'} ч.`;block(metrics,17,65,176,11,77,'Состояние · '+d.title);let fields=[['Самочувствие',j.wellbeing],['Симптомы и эмоции',[j.symptoms,j.emotions].filter(Boolean).join('\n')],['Осознания и благодарность',[j.insights,j.gratitude].filter(Boolean).join('\n')],['Мои личные записи',j.notes]],y=88;for(let[h,v]of fields){panel(h,17,y,176,39,y%2?col.blue:col.lilac);if(v)block(v,22,y+19,166,11,y+32,d.title+' · '+h);else ruled(22,y+22,166,2,8);y+=44}quote(data.quotes?.[(new Date(d.date).getDate())%7]||'Слушайте свой мир так же бережно, как слушают шелест листьев.',25,270,160,280)}
function calendarPage(){base();text('Мой месяц',17,40,23,col.ink,true);text(data.title,17,50,12,col.soft);block(data.meta.intention||'Выбрать главное и оставить место для жизни.',17,62,W-34,12,67,'Намерение месяца');let first=new Date(data.days[0].date+'T12:00:00'),offset=(first.getDay()+6)%7,rows=Math.ceil((offset+data.days.length)/7),top=83,h=rows===6?16:19,w=(W-34)/7;['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].forEach((t,i)=>text(t,17+i*w+3,top-5,10,col.gold));data.days.forEach((d,i)=>{let n=i+offset,x=17+n%7*w,y=top+Math.floor(n/7)*h;doc.setFillColor((i%3)?'#fffcf8':col.lilac);doc.setDrawColor(col.line);doc.rect(x,y,w,h,'FD');text(i+1,x+3,y+6,12,col.ink);phase(d.angle,x+w-6,y+5,2.5);block('Ц:'+d.cycle.replace(/ день.*/, '')+' · '+d.center.replace(' (предп.)',''),x+3,y+13,w-5,9.5,y+h-2,'Ритмы · '+d.title);if(d.events.length||d.tasks.some(t=>t.text?.trim())||d.notes||d.meetings||d.ideas)overflow.push({heading:d.title,text:`${d.phase} · ${d.zodiac} · ${d.lunarDay} лунный день\nЦикл: ${d.cycle} · Центр: ${d.center} · ${d.season}\nРекомендуется: ${d.recommendation}\nИзбегать: ${d.avoid}\nНамерение: ${d.intention}\n`+Object.entries(groups).map(([k,h])=>h+': '+d.tasks.filter(t=>(t.group||'must')===k).map(t=>(t.done?'Выполнено: ':'')+t.text).join('; ')).join('\n')+'\nСобытия: '+d.events.map(e=>(e.time?e.time+' - ':'')+e.title+(e.notes?' - '+e.notes:'')).join('; ')+'\nВстречи: '+d.meetings+'\nИдеи: '+d.ideas+'\nЗаметки: '+d.notes})});let y=top+rows*h+9;text('Заметки месяца',17,y,11,col.gold,true);if(data.meta.notes)block(data.meta.notes,17,y+7,W-34,10.5,H-22,'Заметки месяца');else ruled(17,y+7,W-34,2)}
if(data.mode==='knowledge'){let e=data.entry;base();let titleEnd=block(e.title,17,41,176,23,80,'Название',true);block(e.summary,17,titleEnd+5,176,12,110,'Описание');for(let [heading,value] of Object.entries(e.fields||{}))overflow.push({heading,text:value});if(data.note)overflow.push({heading:'Мои наблюдения',text:data.note});}else if(data.mode==='day'){dayPage(data.days[0],'Мой день в ритме Луны')}else if(data.mode==='month'){calendarPage()}else if(data.mode==='week'){cover('Моя неделя',data.title);if(data.meta.intention)overflow.push({heading:'Главное намерение недели',text:data.meta.intention});for(let d of data.days)dayPage(d,'Моя неделя');[['Ритуалы недели',data.meta.rituals||data.days.map(d=>d.weekday+': '+d.ritual.title).join('\n')],['Важные даты',data.meta.dates],['Заметки недели',data.meta.notes]].filter(([,v])=>v).forEach(([heading,text])=>overflow.push({heading,text}));}else if(data.mode==='journal'){cover('Мой лунный дневник',data.title);for(let d of data.days)dayPage(d,'Мой день',true)}else throw Error('Unknown planner mode');
while(overflow.length){let batch=overflow;overflow=[];base();text('Пространство для деталей',17,41,21,col.ink,true);let y=57,bottom=H-23;for(let item of batch){let headingLines=wrap(item.heading,W-34,12,true),ls=wrap(item.text,W-34,11),step=5.8,headingHeight=headingLines.length*7+3,total=headingHeight+ls.length*step+9;
// Keep a whole section when it fits on an empty page; otherwise keep its heading with at least two lines.
if(y+headingHeight+Math.min(2,ls.length)*step>bottom||(total<=bottom-57&&y+total>bottom)){overflow.push(item);continue}
for(let l of headingLines){text(l,17,y,12,col.gold,true);y+=7}y+=3;let fit=Math.max(1,Math.floor((bottom-y)/step)+1);if(ls.length-fit===1&&fit>2)fit--;ls.slice(0,fit).forEach((l,i)=>text(l,17,y+i*step,11));y+=Math.min(fit,ls.length)*step+9;if(ls.length>fit)overflow.push({heading:item.heading.replace(/ \(продолжение\)$/,'')+' (продолжение)',text:ls.slice(fit).join('\n')})}}
return new Uint8Array(doc.output('arraybuffer'));
}
root.LunaPlanningPDF={create};if(typeof module!=='undefined')module.exports={create};
})(typeof globalThis!=='undefined'?globalThis:this);
