'use strict';
const weekdayPlanets=['Солнца','Луны','Марса','Меркурия','Юпитера','Венеры','Сатурна'];
const beforeRefinedToday=today;
today=function(){let html=beforeRefinedToday(),x=context(),r=P.recommend(x),action=html.match(/<div class="central-action">[\s\S]*?<\/div>/)?.[0]||'';html=html.replace(action,'');html=html.replace('<div class="four-rhythms">',`<div class="day-planet">День ${weekdayPlanets[selected.getDay()]}</div>${action}<section class="today-focus"><span class="small-label">ЧТО СЕГОДНЯ ВАЖНО</span><p>${esc(combinedAdvice(x,r))}</p><button class="text-button" data-action="daily-ritual">Моя практика дня →</button></section><div class="four-rhythms">`);html=html.replace(pretty(selected,{weekday:'long',day:'numeric',month:'long',year:'numeric'}),`<span class="hero-weekday">${pretty(selected,{weekday:'long'})}</span><strong class="hero-date">${pretty(selected,{day:'numeric',month:'long'})}</strong>`);html=html.replace('<a class="rhythm-card cycle-card"',`<button class="rhythm-card zodiac-card" data-action="moon"><span class="rhythm-icon">✦</span><div><h2>Луна в знаке</h2><strong>${x.l.zodiac}</strong><p>Открыть картину Луны на сегодня</p></div></button><a class="rhythm-card cycle-card"`);return html};
async function saveBookFile(name,bytes){let file=new File([bytes],name,{type:'application/pdf'});try{if(window.showSaveFilePicker){let handle=await showSaveFilePicker({suggestedName:name,types:[{description:'PDF',accept:{'application/pdf':['.pdf']}}]});let stream=await handle.createWritable();await stream.write(file);await stream.close();toast('Документ сохранен')}else if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Мой лунный ежедневник'})}else{download(name,bytes,'application/pdf');toast('Документ отправлен в загрузки')}}catch(e){if(e.name!=='AbortError')toast('Не удалось сохранить файл. Попробуйте кнопку «Поделиться».')}}
// Print rendered pages, never PDF bytes or the application shell.
async function printBookFile(bytes){let button=$('#print-book-pdf');if(button){button.disabled=true;button.textContent='Готовим печать…'}let frame;try{let pdfjs=await import('./assets/vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('assets/vendor/pdf.worker.mjs',document.baseURI).href;let task=pdfjs.getDocument({data:bytes.slice(),isEvalSupported:false}),pdf=await task.promise;frame=document.createElement('iframe');frame.title='Страницы для печати';frame.style.cssText='position:fixed;width:1px;height:1px;left:-10000px;border:0';document.body.append(frame);let d=frame.contentDocument;d.open();d.write('<!doctype html><html><head><title>Лунный ежедневник</title><style>@page{margin:0}body{margin:0}img{display:block;width:100%;break-after:page;page-break-after:always}img:last-child{break-after:auto}</style></head><body></body></html>');d.close();let first=await pdf.getPage(1),size=first.getViewport({scale:1});d.querySelector('style').textContent+=`@page{size:${size.width/72*25.4}mm ${size.height/72*25.4}mm}`;for(let i=1;i<=pdf.numPages;i++){let page=await pdf.getPage(i),viewport=page.getViewport({scale:1.6}),canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;let img=d.createElement('img');img.alt='Страница '+i;img.src=canvas.toDataURL('image/jpeg',.94);d.body.append(img);await img.decode();canvas.width=canvas.height=0}await task.destroy();frame.contentWindow.addEventListener('afterprint',()=>frame.remove(),{once:true});frame.contentWindow.focus();frame.contentWindow.print();}catch(e){frame?.remove();toast('Откройте сохраненный PDF и выберите «Печать» в меню устройства.')}finally{if(button){button.disabled=false;button.textContent='Печать'}}}
function showKnowledgePDF(bytes,name){closeModal();modal('<h2>Ваша страница готова</h2><div id="book-pdf-preview"></div><div class="pdf-actions"><button class="primary" id="save-book-pdf">Сохранить PDF</button><button class="secondary" id="print-book-pdf">Печать</button><button class="secondary" data-book-back>Вернуться</button></div>');$('#save-book-pdf').onclick=()=>saveBookFile(name,bytes);$('#print-book-pdf').onclick=()=>printBookFile(bytes);previewBookPDF(bytes)}
const ritualSymbols=['Светильник','Рог изобилия','Леопард','Древо','Единорог','Журавль','Роза ветров','Феникс','Летучая мышь','Источник','Огненный меч','Чаша','Колесо','Труба','Змей','Голубь','Виноградная лоза','Зеркало','Паук','Орел','Конь','Слон','Крокодил','Медведь','Черепаха','Жаба','Трезубец','Лотос','Спрут','Золотой лебедь'];
const ritualSymbolThemes=['заметить свет внутри себя и выбрать направление','заметить доступные ресурсы и принять поддержку','соединить решительность с вниманием к границам','почувствовать корни и опору в близких связях','сохранить верность своему намерению','услышать тихие сигналы и дать себе пространство','выбрать направление среди многих возможностей','увидеть возможность обновления после завершения','заметить страх и вернуть внимание к реальности','восстановить силы через простые привычки','направить силу на одно ясное действие','принять чувства без требования немедленно их изменить','вспомнить, что жизнь движется циклично','обозначить то, что давно хочется сказать','заметить желание и осознанно выбрать свой ответ','вернуться к спокойствию и согласию с собой','разделить радость и почувствовать связь с другими','увидеть свои реакции с мягкостью и честностью','заметить связи между привычками и их результатом','посмотреть на ситуацию с большей высоты','двигаться вперед, сохраняя посильный темп','вспомнить опыт, который стал внутренней опорой','дать сильным чувствам место, сохраняя границы','позволить себе восстановление и уединение','снизить темп и услышать потребность в отдыхе','заметить, что можно изменить в привычном окружении','соединить чувство, мысль и действие','увидеть красоту даже в несовершенном дне','распутать лишние обязательства по одному','признать прожитое и завершить круг с благодарностью'];
function ritualDayPage(){let x=context(),r=P.recommend(x),e=dailyRitual(x),planet=weekdayPlanets[selected.getDay()],symbol=ritualSymbols[(x.l.day-1)%30],wax=x.l.angle<180,archetype=x.l.angle<45?['Геката','Образ порога и внутреннего выбора. Ее факел напоминает о праве двигаться небольшими шагами, даже когда весь путь еще не виден.']:x.l.angle<135?['Дурга','Образ спокойной силы и бережных границ. Ее присутствие помогает вспомнить, что решительность может сочетаться с заботой о себе.']:x.l.angle<225?['Фрейя','Образ чувственности, красоты и личной ценности. В этой практике она приглашает замечать удовольствие и выбирать то, что наполняет жизнь.']:['Кали','Образ завершения и освобождения от исчерпанного. Ее символическое присутствие приглашает отпустить привычку, которая больше не помогает, без борьбы с собой.'];let fields={
'Энергия дня':`${pretty(selected,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}. ${x.l.day}-й лунный день, ${x.l.phase.toLowerCase()}, Луна в знаке ${x.l.zodiac}. День ${planet}. Ваше состояние задает темп практики: если сил мало, сократите ее до нескольких минут тишины.`,
'Символ лунного дня':`${symbol} приглашает ${ritualSymbolThemes[(x.l.day-1)%30]}. В нашей практике этот символ проявляется через то, как вы выбираете темп, общение и небольшие повседневные действия. Представьте этот образ как приглашение к размышлению: что в нем привлекает вас, какие чувства он вызывает и с какой ситуацией вашей жизни перекликается? Запишите собственную ассоциацию, чтобы символ стал личным, а не готовым предсказанием.`,
'Энергия текущей фазы Луны':`${x.l.phase}. ${wax?'Растущая Луна в символической практике поддерживает развитие намерения: выберите небольшой шаг, которому готовы уделять внимание, и оставьте время для постепенного роста.':'Убывающая Луна в символической практике связана с завершением: посмотрите, что уже принесло результат, и освободите место от лишних обязательств.'} Наблюдайте, совпадает ли эта тема с вашим реальным состоянием.`,
'Энергия знака Луны':`Луна в знаке ${x.l.zodiac} добавляет к практике тему ${({'Овен':'инициативы','Телец':'устойчивости и телесного комфорта','Близнецы':'общения и любопытства','Рак':'дома и эмоциональной опоры','Лев':'творчества','Дева':'порядка и заботы','Весы':'равновесия в отношениях','Скорпион':'глубины и честности','Стрелец':'смысла и расширения горизонта','Козерог':'границ и последовательности','Водолей':'свободы и новых идей','Рыбы':'воображения и мягкости'})[x.l.zodiac]}. Пусть она станет вопросом к себе: где сегодня мне пригодится это качество? Выберите один конкретный способ проявить его в обычных делах.`,
'Энергия дня недели':`День ${planet} связывает недельный ритм с темой ${['ясности и жизненной радости','чувств и внутреннего дома','действия и личных границ','общения и обучения','смысла и щедрости','красоты и отношений','завершения и устойчивости'][selected.getDay()]}. Подумайте, какое дело сегодня позволит проявить эту тему без спешки. Планета дня служит символическим образом для размышления.`,
'Главная тема дня':combinedAdvice(x,r),
'Подготовка алтаря':`Освободите небольшое пространство и поставьте рядом стакан воды и блокнот. Свеча: ${e.fields.Свеча||'простая свеча без добавок'}. Цвет: ${e.fields.Цвет||'белый'}. Камень: ${e.fields.Камень||'любой предмет, который напоминает об опоре'}. Травы можно представить рисунком или положить отдельно в чашу, масло использовать только как закрытый ароматический предмет, если запах вам приятен. Добавьте символ ${symbol.toLowerCase()}; все предметы необязательны.`,
'Создание свечи':`Выберите готовую свечу подходящего цвета и обозначьте ее назначение в блокноте: ${r.intention} Украсьте подставку рисунком символа дня. Оставьте воск и фитиль без трав, камней и масел; дополнительные предметы разместите отдельно от огня. Поставьте свечу на негорючую устойчивую поверхность, не оставляйте ее без присмотра. Для практики подойдет и светодиодная свеча.`,
'Намерение дня':`${r.intention}\n\nЯ выбираю посильный шаг и позволяю себе двигаться в своем ритме.\n\nЯ слышу свои потребности и оставляю в этом дне место для радости.`,
'Архетип богини':`${archetype[0]}. ${archetype[1]} Это современная символическая интерпретация для самонаблюдения; вы можете выбрать другой близкий вам образ.`,
'Практика дня':`1. Устройтесь удобно и сделайте несколько спокойных выдохов, замечая опору под телом.\n\n2. Посмотрите на символ дня и запишите, что сейчас занимает ваше внимание.\n\n3. ${e.fields.Практика||'Выберите одно небольшое действие, соответствующее вашему намерению.'}\n\n4. Произнесите выбранное намерение и обозначьте конкретный шаг, который сможете сделать сегодня.\n\n5. Завершите практику благодарностью себе, погасите свечу и вернитесь к обычным делам.`,
'Наблюдение дня':`Обратите внимание на отклик тела, уровень энергии и желание общаться или побыть в тишине. Если появляются сильные эмоции, дайте им место в записи, не требуя немедленного решения. Вечером вспомните, что поддержало вас, и что стоит изменить завтра; ${r.avoid.join('; ')} можно оставить за пределами сегодняшнего плана.`};return {id:'daily-structured',title:'Мой ритуал дня',type:'rituals',image:e.image,summary:'Личная практика в ритме дня, с вниманием к вашему состоянию.',fields}}
actions['daily-ritual']=()=>{let e=ritualDayPage();modal(`<img class="ritual-cover" src="${e.image}" alt="Свеча и мягкий лунный свет"><h2>${e.title}</h2>${Object.entries(e.fields).map(([h,t])=>`<section class="ritual-chapter"><h3>${h}</h3>${t.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('')}<button class="primary" id="ritual-pdf">Сохранить ритуал в PDF</button>`);$('#ritual-pdf').onclick=async()=>{try{let bytes=await LunaPlanningPDF.create({mode:'knowledge',title:e.title,entry:e,meta:{}});showKnowledgePDF(bytes,'Ритуал-'+M.dateKey(selected)+'.pdf')}catch{toast('Не удалось оформить ритуал. Попробуйте еще раз.')}}};
const oldRitualPresentation=ritualPresentation;ritualPresentation=function(e){return oldRitualPresentation(e).replace(`data-entry="${e.id}">Открыть ритуал`,`data-action="daily-ritual">Открыть ритуал дня`)};
const priorPDFDay=plannerPDFDay;plannerPDFDay=function(date){let row=priorPDFDay(date);let previous=selected;try{selected=date;row.ritual=ritualDayPage();return row}finally{selected=previous}};
reminderTypes.push(['planning','Планирование дня'],['important','Важные даты']);
const priorReminderSchedule=reminderSchedule;reminderSchedule=function(){let events=priorReminderSchedule(),now=Date.now(),[h,m]=state.reminders.time.split(':').map(Number);for(let i=0;i<90;i++){let date=M.shift(new Date(),i);date.setHours(h,m,0,0);if(+date<=now)continue;if(state.reminders.planning)events.push({at:+date,title:'Выберите главное и запланируйте свой день'});if(state.reminders.important)for(let e of eventsFor(date))events.push({at:+date,title:e.title})}return events.sort((a,b)=>a.at-b.at)};
window.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.atelier-wheel [data-entry]')){e.preventDefault();entry(e.target.dataset.entry)}});
// A single owner updates the Telegram back button, including dialogs on the home screen.
window.addEventListener('hashchange',()=>queueMicrotask(syncBookBack));
async function telegramVisit(){let tg=window.Telegram?.WebApp;if(!tg?.initData)return;try{await fetch('api/telegram/visit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData})})}catch{}}
window.addEventListener('load',telegramVisit);document.addEventListener('visibilitychange',()=>{if(!document.hidden)telegramVisit()});
const browserPushEnable=actions['enable-push'];
async function telegramReminders(events){let response=await fetch('api/telegram/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:Telegram.WebApp.initData,events:events.map(e=>({...e,title:e.title.slice(0,200)}))})});let result=await response.json();if(!response.ok)throw Error(result.error);return result}
actions['enable-push']=async()=>{let tg=window.Telegram?.WebApp;if(!tg?.initData)return browserPushEnable();try{let f=$('#reminder-form');if(f){state.reminders={time:f.elements.time.value,...Object.fromEntries(reminderTypes.map(([k])=>[k,f.elements[k].checked]))};persist()}let events=reminderSchedule();if(!events.length)return toast('Выберите хотя бы одно напоминание.');let available=await fetch('api/telegram/visit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData})});if(!available.ok)throw Error((await available.json()).error);let granted=await new Promise(resolve=>tg.requestWriteAccess(resolve));if(!granted)return toast('Чтобы получать напоминания, разрешите сообщения от бота.');await telegramReminders(events);localStorage.setItem('ys-luna-telegram-reminders','1');toast('Напоминания Telegram включены');render()}catch(e){toast(e.message||'Не удалось включить напоминания Telegram.')}};
const beforeTelegramSettings=settings;settings=function(){let html=beforeTelegramSettings();if(window.Telegram?.WebApp?.initData){html=html.replace(/Включить напоминания браузера|Обновить напоминания браузера/g,'Включить напоминания Telegram');html+='<section class="panel spaced"><h2>Напоминания Telegram</h2><p>Бот будет отправлять выбранные напоминания в личный чат.</p><button class="secondary" data-action="disable-telegram">Отключить напоминания Telegram</button></section>'}return html};
actions['disable-telegram']=async()=>{try{await telegramReminders([]);localStorage.removeItem('ys-luna-telegram-reminders');toast('Напоминания Telegram отключены')}catch(e){toast(e.message)}};
const beforeTelegramForms=bindForms;bindForms=function(){beforeTelegramForms();let f=$('#reminder-form');if(f){let handler=f.onsubmit;f.onsubmit=e=>{handler?.(e);if(localStorage.getItem('ys-luna-telegram-reminders'))telegramReminders(reminderSchedule()).catch(e=>toast(e.message))}}};
window.addEventListener('load',()=>{if(localStorage.getItem('ys-luna-telegram-reminders')&&window.Telegram?.WebApp?.initData)telegramReminders(reminderSchedule()).catch(()=>{})});
actions['weekly-pdf']=()=>plannerPDF('week');
actions['notification-test']=async()=>{if(window.Telegram?.WebApp?.initData){try{await telegramReminders([...reminderSchedule(),{at:Date.now()+90000,title:'ЛУНА · Напоминания подключены'}]);toast('Проверка придет примерно через две минуты.')}catch(e){toast(e.message)}return}try{if(!('Notification'in window))return actions['enable-push']();let permission=await Notification.requestPermission();if(permission!=='granted')return toast('Разрешите уведомления в настройках устройства.');let registration=await navigator.serviceWorker.ready;await registration.showNotification('ЛУНА · Ваш личный ритм',{body:'Найдите минуту для себя.',icon:'assets/icon-192.png'})}catch{toast('Откройте установленное приложение и включите уведомления.')}};
const originalTelegramPersist=persist;let telegramScheduleTimer;
persist=function(){let ok=originalTelegramPersist();if(ok&&localStorage.getItem('ys-luna-telegram-reminders')&&window.Telegram?.WebApp?.initData){clearTimeout(telegramScheduleTimer);telegramScheduleTimer=setTimeout(()=>telegramReminders(reminderSchedule()).catch(()=>{}),2500)}return ok};
const privateTelegramSettings=settings;settings=function(){let html=privateTelegramSettings();if(window.Telegram?.WebApp?.initData)html=html.replace('На сервер сайта передаются адрес подписки и время событий. Тексты напоминаний, планы и дневник остаются в браузере.','Для напоминаний Telegram на сервер передаются ваш Telegram ID, имя, username, время и текст выбранных напоминаний. Личные записи дневника остаются на устройстве.');return html};
downloadReminders=function(){let events=reminderSchedule(),escapeICS=s=>String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');if(!events.length)return toast('Выберите события напоминаний.');let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LUNA//Reminders//RU','CALSCALE:GREGORIAN',...events.flatMap((e,i)=>['BEGIN:VEVENT',`UID:${e.at}-${i}@luna.yuliastoyanova.com`,`DTSTAMP:${icsTime(new Date())}`,`DTSTART:${icsTime(new Date(e.at))}`,`SUMMARY:${escapeICS(e.title)}`,'BEGIN:VALARM','TRIGGER:-PT0M','ACTION:DISPLAY',`DESCRIPTION:${escapeICS(e.title)}`,'END:VALARM','END:VEVENT']),'END:VCALENDAR'];download('Лунные-напоминания.ics',lines.join('\r\n'),'text/calendar;charset=utf-8');toast('Откройте файл в календаре телефона. Напоминания подготовлены на 90 дней.')};
function normalizeBookText(container){let walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT);for(let node;node=walker.nextNode();){if(node.parentElement.closest('textarea,input,script,style'))continue;node.nodeValue=node.nodeValue.replace(/ё/g,'е').replace(/Ё/g,'Е').replace(/[–—]/g,'-')}}
const refinedRender=render;render=function(){refinedRender();normalizeBookText($('#view'))};
const refinedModal=modal;modal=function(html){refinedModal(html);normalizeBookText($('#modal-content'))};
