/* Same PDF renderer runs in the browser and in document verification. */
(function(root){
async function create(data,options={}){let C=options.jsPDF||root.jspdf.jsPDF,font=options.font;if(!font){let bytes=new Uint8Array(await fetch('assets/pdf-text.ttf').then(r=>{if(!r.ok)throw Error('font');return r.arrayBuffer()}));let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));font=btoa(str)}let doc=new C({orientation:'landscape',unit:'mm',format:'a3',compress:true});doc.addFileToVFS('Manrope.ttf',font);doc.addFont('Manrope.ttf','Manrope','normal');doc.setFont('Manrope');doc.setLanguage('ru-RU');doc.setProperties({title:'Моя неделя · Лунный дневник',author:'Юлия Стоянова'});let W=420,H=297,overflow=[];
function text(t,x,y,size=10,color='#352d30'){doc.setFontSize(size);doc.setTextColor(color);doc.text(String(t||'').replace(/[\u2011\u2013\u2014]/g,'-'),x,y)}
function lines(t,w,size){doc.setFontSize(size);return doc.splitTextToSize(String(t||'').replace(/[\u2011\u2013\u2014]/g,'-'),w)}
function block(t,x,y,w,size,maxY,heading){let ls=lines(t,w,size),step=size*.3528*1.45,fit=Math.max(0,Math.floor((maxY-y)/step)+1);ls.slice(0,fit).forEach((s,i)=>text(s,x,y+i*step,size));if(ls.length>fit)overflow.push({heading,text:ls.slice(fit).join(' ')});return y+Math.min(ls.length,fit)*step}
function pageBase(page){doc.setFillColor('#f7f3ec');doc.rect(0,0,W,H,'F');doc.setDrawColor('#b59a65');doc.setLineWidth(.25);doc.line(14,24,W-14,24);text('Л У Н А   /   Л И Ч Н Ы Й  П Л А Н',14,16,10,'#806a43');text('ЮЛИЯ СТОЯНОВА',W-59,16,9,'#806a43');text('Внимание к себе - каждый день',14,H-10,9,'#806a43');text(String(page),W-20,H-10,9,'#806a43')}
pageBase(1);text('Моя неделя',14,39,24);text(data.title,14,48,12);if(data.name)block(data.name,W-80,39,66,12,52,'Имя');text('ГЛАВНОЕ НАМЕРЕНИЕ НЕДЕЛИ',14,60,9,'#806a43');block(data.meta.intention||'Оставить место для важного и для себя.',14,68,390,13,78,'Намерение недели');
let col=(W-28-6*2)/7,top=87,bottom=230;data.days.forEach((d,i)=>{let x=14+i*(col+2);doc.setFillColor('#fffcf7');doc.setDrawColor('#ddd1bb');doc.roundedRect(x,top,col,bottom-top,2,2,'FD');text(d.weekday,x+3,top+9,11,'#806a43');text(d.date,x+3,top+17,13);let y=block(d.phase+'\nЛуна: '+d.zodiac+'\n'+d.cycle,x+3,top+27,col-6,9,top+48,'Ритмы · '+d.weekday);doc.setDrawColor('#e1d6c2');doc.line(x+3,top+52,x+col-3,top+52);text('Намерение',x+3,top+61,9,'#806a43');block(d.intention,x+3,top+68,col-6,10,top+90,'Намерение · '+d.weekday);text('Главные задачи',x+3,top+93,9,'#806a43');y=top+102;let tasks=d.tasks.filter(t=>t.text.trim());if(!tasks.length){for(let n=0;n<3;n++){doc.rect(x+3,y-2.5,2.5,2.5);doc.line(x+9,y,x+col-3,y);y+=9}}else tasks.forEach((t,n)=>{if(y>bottom-8){overflow.push({heading:'Задачи · '+d.weekday,text:(t.done?'Выполнено: ':'')+t.text});return}doc.rect(x+3,y-2.5,2.5,2.5);if(t.done){doc.line(x+3,y-2.5,x+5.5,y);doc.line(x+3,y,x+5.5,y-2.5)}y=block(t.text,x+9,y,col-12,10,bottom-8,'Задача · '+d.weekday)+4});if(d.notes)overflow.push({heading:'Заметки · '+d.weekday,text:d.notes})});
let lower=242,width=(W-32)/3;[['РИТУАЛЫ И ПРАКТИКИ',data.meta.rituals],['ВАЖНЫЕ ДАТЫ',data.meta.dates],['ЗАМЕТКИ',data.meta.notes]].forEach(([h,t],i)=>{let x=14+i*(width+2);text(h,x,lower,9,'#806a43');if(t)block(t,x,lower+8,width-5,10,278,h);else{doc.setDrawColor('#ddd1bb');[252,261,270].forEach(y=>doc.line(x,y,x+width-5,y))}});
let page=1,y=39;while(overflow.length){let items=overflow;overflow=[];doc.addPage();pageBase(++page);text('Пространство для деталей',14,39,21);y=53;for(let item of items){if(y>255){overflow.push(item);continue}text(item.heading,14,y,12,'#806a43');y+=8;let ls=lines(item.text,385,11),step=5.6,fit=Math.floor((275-y)/step);ls.slice(0,fit).forEach((l,i)=>text(l,14,y+i*step,11));y+=Math.min(fit,ls.length)*step+11;if(ls.length>fit)overflow.push({heading:item.heading+' (продолжение)',text:ls.slice(fit).join(' ')})}}
return new Uint8Array(doc.output('arraybuffer'));
}
root.LunaWeeklyPDF={create};if(typeof module!=='undefined')module.exports={create};
})(typeof globalThis!=='undefined'?globalThis:this);
