import {auditedGeometry} from './audited-geometry.js';
import {shriTriangles,shriVerification} from './shri.js';
export const TAU=2*Math.PI,PHI=(1+Math.sqrt(5))/2;
const f=x=>Number(x.toFixed(12));
export const points=(n,r=90,cx=150,cy=150,start=-Math.PI/2)=>Array.from({length:n},(_,i)=>[cx+r*Math.cos(start+TAU*i/n),cy+r*Math.sin(start+TAU*i/n)]);
const circle=(x=150,y=150,r=90)=>`<circle cx="${f(x)}" cy="${f(y)}" r="${f(r)}"/>`;
const dot=(x=150,y=150,r=3)=>`<circle class="solid" cx="${f(x)}" cy="${f(y)}" r="${r}"/>`;
const line=(a,b)=>`<line x1="${f(a[0])}" y1="${f(a[1])}" x2="${f(b[0])}" y2="${f(b[1])}"/>`;
const path=d=>`<path d="${d}"/>`;
const poly=p=>`<polygon points="${p.map(q=>q.map(f).join(',')).join(' ')}"/>`;
const polygon=(n,r=90,cx=150,cy=150,start=-Math.PI/2)=>poly(points(n,r,cx,cy,start));
const curve=p=>path(p.map((q,i)=>(i?'L':'M')+q.map(f).join(' ')).join(''));
const sample=(fn,count=240)=>Array.from({length:count+1},(_,i)=>fn(i/count));
const ellipse=(cx,cy,rx,ry)=>path(`M${f(cx-rx)} ${f(cy)}a${f(rx)} ${f(ry)} 0 1 0 ${f(2*rx)} 0a${f(rx)} ${f(ry)} 0 1 0 ${f(-2*rx)} 0`);
export function latticeCenters(level=2,r=36){const a=[];for(let q=-level;q<=level;q++)for(let t=-level;t<=level;t++){let ring=Math.max(Math.abs(q),Math.abs(t),Math.abs(q+t));if(ring<=level)a.push({q,t,ring,x:150+r*(q+t/2),y:150+r*Math.sqrt(3)*t/2});}return a.sort((a,b)=>a.ring-b.ring||Math.atan2(a.y-150,a.x-150)-Math.atan2(b.y-150,b.x-150));}
export function fruitCenters(r=20){return [[150,150],...points(6,2*r,150,150,0),...points(6,4*r,150,150,0)];}
export function solidModel(name){let v=[],p=PHI,a=1/p;
 if(name==='ТЕТРАЭДР')v=[[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]];
 else if(name==='ОКТАЭДР')v=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
 else if(name==='ИКОСАЭДР')for(let s of [-1,1])for(let t of [-1,1])v.push([0,s,t*p],[s,t*p,0],[t*p,0,s]);
 else if(name==='ДОДЕКАЭДР'){for(let x of [-1,1])for(let y of [-1,1])for(let z of [-1,1])v.push([x,y,z]);for(let s of [-1,1])for(let t of [-1,1])v.push([0,s*a,t*p],[s*a,t*p,0],[t*p,0,s*a]);}
 else if(name==='КУБООКТАЭДР'||name==='ВЕКТОРНЫЙ ЭКВИЛИБРИУМ')for(let i=0;i<3;i++)for(let s of [-1,1])for(let t of [-1,1]){let u=[0,0,0];u[(i+1)%3]=s;u[(i+2)%3]=t;v.push(u);}
 else for(let x of [-1,1])for(let y of [-1,1])for(let z of [-1,1])v.push([x,y,z]);
 let distances=[];v.forEach((u,i)=>v.slice(i+1).forEach(w=>distances.push(Math.hypot(...u.map((x,k)=>x-w[k])))));let edge=Math.min(...distances),edges=[];v.forEach((u,i)=>v.forEach((w,j)=>{if(j>i&&Math.abs(Math.hypot(...u.map((x,k)=>x-w[k]))-edge)<1e-8)edges.push([i,j]);}));return{vertices:v,edges,edge};
}
function project(v,scale=53){const c=Math.cos(.43),s=Math.sin(.43),a=.37;let x=v[0]*c-v[1]*s,y=v[0]*s+v[1]*c;return[150+scale*x,150+scale*(y*Math.sin(a)-v[2]*Math.cos(a))];}
function solid(name,scale){let m=solidModel(name),max=Math.max(...m.vertices.flat().map(Math.abs));return m.edges.map(([i,j])=>line(project(m.vertices[i],scale||68/max),project(m.vertices[j],scale||68/max))).join('');}
export function hypercube(n=4){const vertices=Array.from({length:2**n},(_,i)=>Array.from({length:n},(_,b)=>i&(1<<b)?1:-1));let edges=[];vertices.forEach((v,i)=>{for(let b=0;b<n;b++){let j=i^(1<<b);if(j>i)edges.push([i,j]);}});return{vertices,edges};}
function hyper(n){const m=hypercube(n),basis=[[43,0],[0,43],[-22,17],[17,24],[-13,-11]],p=m.vertices.map(v=>v.reduce((a,x,k)=>[a[0]+x*basis[k][0],a[1]+x*basis[k][1]],[150,150]));return m.edges.map(([a,b])=>line(p[a],p[b])).join('');}
function spiral(kind='arch',turns=3,phase=0){return curve(sample(t=>{let angle=t*TAU*turns+phase,r=kind==='gold'?4*Math.exp(Math.log(PHI)/(Math.PI/2)*t*TAU*turns):6+85*t;return[150+r*Math.cos(angle),150+r*Math.sin(angle)];},600));}
export function fibonacciParts(){let x=0,y=0,w=1,h=1,seq=[{x,y,size:1,start:Math.PI,end:1.5*Math.PI,cx:1,cy:1}];let prev=1,current=1;for(let i=1;i<10;i++){let size=i===1?1:prev+current;if(i>1){prev=current;current=size;}let dir=(i-1)%4,sq;if(dir===0){sq={x:x+w,y,size,cx:x+w,cy:y+size,start:-Math.PI/2,end:0};w+=size;}if(dir===1){sq={x,y:y+h,size,cx:x,cy:y+h,start:0,end:Math.PI/2};h+=size;}if(dir===2){sq={x:x-size,y,size,cx:x,cy:y,start:Math.PI/2,end:Math.PI};x-=size;w+=size;}if(dir===3){sq={x,y:y-size,size,cx:x+w,cy:y,start:Math.PI,end:1.5*Math.PI};y-=size;h+=size;}seq.push(sq);}return{seq,bounds:{x,y,w,h}};}
function fibonacci(){const{seq,bounds:b}=fibonacciParts(),s=210/Math.max(b.w,b.h),tx=150-(b.x+b.w/2)*s,ty=150-(b.y+b.h/2)*s;return seq.map(q=>curve(sample(t=>[tx+(q.cx+q.size*Math.cos(q.start+t*(q.end-q.start)))*s,ty+(q.cy+q.size*Math.sin(q.start+t*(q.end-q.start)))*s],40))).join('');}
function torus(R=65,r=25,tilt=.8){let out='';const p=(u,v)=>{let x=(R+r*Math.cos(v))*Math.cos(u),y=(R+r*Math.cos(v))*Math.sin(u),z=r*Math.sin(v);return[150+x,150+y*Math.cos(tilt)-z*Math.sin(tilt)];};for(let i=0;i<12;i++)out+=curve(sample(t=>p(i*TAU/12,t*TAU),72));for(let i=0;i<4;i++)out+=curve(sample(t=>p(t*TAU,i*TAU/4),120));return out;}
function sphere(){let out=circle();for(let k=-2;k<=2;k++){let z=k*28,r=Math.sqrt(90**2-z**2);out+=ellipse(150,150-z*.78,r,r*.36);}for(let k=1;k<5;k++)out+=ellipse(150,150,90*Math.sin(k*Math.PI/5),90);return out;}
function rosette(n,r=75,inner=24,phase=0){let out='';for(let i=0;i<n;i++){let a=TAU*i/n+phase,center=[150,150],p=[150+r*Math.cos(a),150+r*Math.sin(a)],l=[150+inner*Math.cos(a-.35),150+inner*Math.sin(a-.35)],h=[150+inner*Math.cos(a+.35),150+inner*Math.sin(a+.35)];out+=path(`M${center} Q${l} ${p}Q${h} ${center}`);}return out;}
function wave(count=4,phase=0){let out='';for(let k=0;k<count;k++)out+=curve(sample(t=>[45+t*210,150+(18+k*10)*Math.sin(t*TAU*2+phase)],120));return out;}
function fractal(depth=4){let out='';function recur(p,d){if(!d){out+=poly(p);return;}const[a,b,c]=p,ab=a.map((x,i)=>(x+b[i])/2),bc=b.map((x,i)=>(x+c[i])/2),ca=c.map((x,i)=>(x+a[i])/2);recur([a,ab,ca],d-1);recur([ab,b,bc],d-1);recur([ca,bc,c],d-1);}recur(points(3,102),depth);return out;}
const treeNodes=[[150,35],[95,75],[205,75],[95,125],[205,125],[150,153],[95,203],[205,203],[150,235],[150,275]];
export const treeEdges=[[0,1],[0,2],[0,5],[1,2],[1,3],[1,5],[2,4],[2,5],[3,4],[3,5],[3,6],[4,5],[4,7],[5,6],[5,7],[5,8],[5,9],[6,7],[6,8],[6,9],[7,8],[8,9]];
function tree(mode=0){let out=mode===1?line(treeNodes[0],treeNodes[9]):mode===2?curve(treeNodes):treeEdges.map(([a,b])=>line(treeNodes[a],treeNodes[b])).join('');return out+treeNodes.filter((p,i)=>mode!==1||[0,5,8,9].includes(i)).map(p=>circle(...p,9)).join('');}
function grid(n=5,diagonal=false){let out='';for(let i=0;i<n;i++){let a=55+i*190/(n-1);out+=line([55,a],[245,a])+line([a,55],[a,245]);}if(diagonal)for(let i=0;i<n-1;i++)for(let j=0;j<n-1;j++){let a=55+i*190/(n-1),b=55+j*190/(n-1);out+=line([a,b],[a+190/(n-1),b+190/(n-1)]);}return out;}
function honeycomb(){let out='';for(let q=-2;q<=2;q++)for(let r=-2;r<=2;r++)if(Math.max(Math.abs(q),Math.abs(r),Math.abs(q+r))<=2)out+=polygon(6,22,150+33*q,150+Math.sqrt(3)*22*(r+q/2),0);return out;}
function starTetra(){let m=solidModel('ТЕТРАЭДР');return solid('ТЕТРАЭДР')+m.edges.map(([a,b])=>line(project(m.vertices[a].map(x=>-x),68),project(m.vertices[b].map(x=>-x),68))).join('');}
function triangleAt(r,up=true){return polygon(3,r,150,150,up?-Math.PI/2:Math.PI/2);}
// Every entry has an explicit construction. Abstract entries use named compositions,
// never a fallback glyph. Symbolic compositions are identified in the UI.
function baseGeometry(name){let out='',mode='exact',math='',algorithm=[],parameters={};
 const exact=(s,text,steps)=>{out=s;math=text;algorithm=steps||['Задать центр и масштаб.','Последовательно построить элементы по координатам.'];};
 const art=(s,text)=>{mode='interpretation';exact(s,text,['Задать композиционный центр.','Построить опорные элементы интерпретации.','Добавить связи и завершить композицию.']);};
 const polygons={'КВАДРАТ':4,'ПЕНТАГОН':5,'ГЕКСАГОН':6,'ГЕПТАГОН':7,'ОКТАГОН':8,'ЭННЕАГОН':9,'ДЕКАГОН':10};
 if(polygons[name]){let n=polygons[name];parameters={n,radius:90};exact(polygon(n),`Правильный ${n}-угольник. Вершины: x = R cos(2πk/n - π/2), y = R sin(2πk/n - π/2). Сторона a = 2R sin(π/n), внутренний угол ${(180*(n-2)/n).toFixed(3)}°. ${n} осей отражения и повороты на 360°/${n}.`,['Построить описанную окружность.','Разделить полный угол на равные части.','Соединить соседние вершины.']);}
 else if(['ТЕТРАЭДР','КУБ (ГЕКСАЭДР)','ОКТАЭДР','ИКОСАЭДР','ДОДЕКАЭДР','КУБООКТАЭДР','ВЕКТОРНЫЙ ЭКВИЛИБРИУМ'].includes(name)){let m=solidModel(name);parameters={vertices:m.vertices,edges:m.edges};exact(solid(name)+(name==='ВЕКТОРНЫЙ ЭКВИЛИБРИУМ'?m.vertices.map(p=>line([150,150],project(p,68))).join(''):''),`Ортогональная проекция пространственной модели: ${m.vertices.length} вершин, ${m.edges.length} ребер. Ребра соединяют вершины на минимальном ненулевом расстоянии. Все исходные ребра равны; в проекции их длины могут различаться.`,['Вычислить пространственные координаты вершин.','Найти пары вершин, образующие ребра.','Применить один поворот и ортогональную проекцию.']);}
 else switch(name){
 case 'ТОЧКА':exact(dot(150,150,4),'Точка задает положение и не имеет размера. Видимый диск служит обозначением точки, его радиус не является математическим свойством.');break;
 case 'ЛИНИЯ':exact(line([45,150],[255,150])+dot(45,150)+dot(255,150),'Показан отрезок прямой: P(t) = A + t(B - A), 0 ≤ t ≤ 1. Прямая продолжается в обе стороны без ограничения.');break;
 case 'КРУГ':exact(circle(),'Граница круга: (x - cx)² + (y - cy)² = R². Площадь круга πR², длина окружности 2πR. Любая прямая через центр является осью симметрии.');break;
 case 'ПРЯМОУГОЛЬНИК':exact(poly([[55,95],[245,95],[245,205],[55,205]]),'Четыре прямых угла; противоположные стороны равны. Для показанного примера a = 190, b = 110. Диагонали равны √(a² + b²), две оси отражения.');break;
 case 'СПИРАЛЬ':exact(spiral(),'Выбран частный случай: спираль Архимеда r = 6 + 85θ/(6π), 0 ≤ θ ≤ 6π. Радиальное расстояние между соседними витками постоянно.');break;
 case 'ЗОЛОТАЯ СПИРАЛЬ':exact(spiral('gold',1.5),'Логарифмическая спираль r = 4 exp(bθ), b = ln(φ)/(π/2), φ = (1 + √5)/2. Радиус увеличивается в φ раз за четверть оборота. SVG-путь аппроксимирован 600 отрезками; формула задает каждый узел.');break;
 case 'СПИРАЛЬ ФИБОНАЧЧИ':exact(fibonacci(),'Четверти окружностей в последовательно прилегающих квадратах со сторонами 1, 1, 2, 3, 5, 8, 13, 21, 34, 55. Это составная кривая из дуг, которая отличается от логарифмической золотой спирали.');break;
 case 'ДВОЙНАЯ СПИРАЛЬ':exact(spiral('arch',2.5)+spiral('arch',2.5,Math.PI),'Две спирали Архимеда r = 6 + 85t, θ = 5πt и θ = 5πt + π. Вторая получается поворотом первой на 180°. Показана плоская модель, а не пространственная двойная спираль ДНК.');break;
 case 'ПЕНТАГРАММА':{let p=points(5);exact(poly([p[0],p[2],p[4],p[1],p[3]]),'Правильная звезда {5/2}: соединяем каждую вторую вершину пятиугольника. Отношение диагонали к стороне равно φ = (1 + √5)/2; пять осей отражения.');break;}
 case 'ГЕКСАГРАММА':{let p=points(6);exact(poly([p[0],p[2],p[4]])+poly([p[1],p[3],p[5]]),'Два равносторонних треугольника на одной окружности. Их вершины чередуются с угловым шагом 60°. Композиция имеет шесть осей отражения.');break;}
 case 'ВЕЗИКА ПИСЦИС':exact(circle(112,150,76)+circle(188,150,76),'Две окружности радиуса R = 76, расстояние между центрами R. Центр каждой лежит на другой окружности. Высота общей линзы √3R, ширина R; отношение высоты к ширине √3.');parameters={radius:76,centers:[[112,150],[188,150]]};break;
 case 'СЕМЯ ЖИЗНИ':case 'ЦВЕТОК ЖИЗНИ':{let l=name==='СЕМЯ ЖИЗНИ'?1:2,r=l===1?49:34,centers=latticeCenters(l,r);parameters={radius:r,centers};exact(centers.map(p=>circle(p.x,p.y,r)).join(''),`${centers.length} равных окружностей на треугольной решетке. Центры (Rq + Rt/2, √3Rt/2), max(|q|, |t|, |q + t|) ≤ ${l}. Расстояние между соседями R. Шесть осей симметрии.`,['Построить центральную окружность.','Разместить шесть центров на ее окружности с шагом 60°.','Продолжить решетку по концентрическим шестигранным слоям.']);break;}
 case 'ПЛОД ЖИЗНИ':case 'КУБ МЕТАТРОНА':{let p=fruitCenters();parameters={radius:20,centers:p};out=p.map(q=>circle(...q,20)).join('');if(name==='КУБ МЕТАТРОНА')for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++)out+=line(p[i],p[j]);exact(out,`13 центров: один в центре и по шесть на окружностях радиусов 2R и 4R при R = 20. ${name==='КУБ МЕТАТРОНА'?'Все пары центров соединены: 13 × 12 / 2 = 78 отрезков.':'Окружности радиуса R на внутренних радиальных направлениях касаются соседних окружностей.'} Шестикратная вращательная симметрия.`,['Построить центральную окружность.','Добавить внутренние шесть окружностей.','Продолжить каждое радиальное направление.','Соединить центры, если это Куб Метатрона.']);break;}
 case 'ЯЙЦО ЖИЗНИ':{let m=solidModel('КУБ (ГЕКСАЭДР)');exact(m.vertices.map(v=>circle(...project(v,36),36)).join(''),'Показана проекция восьми равных сфер с центрами в вершинах куба. В трехмерной модели радиус равен половине ребра куба, соседние сферы касаются. Круги на экране представляют контуры сфер; перекрытие проекций не означает пересечение объемов.');break;}
 case 'СФЕРА':exact(sphere(),'Сфера x² + y² + z² = R². Площадь 4πR², объем ограниченного ею шара 4πR³/3. Изображены проекции меридианов и параллелей, а не плоская геометрическая фигура.');break;
 case 'ТОР':exact(torus(),'Параметризация: x = (R + r cos v) cos u, y = (R + r cos v) sin u, z = r sin v. Здесь R = 65, r = 25. Объем кольцевого тора 2π²Rr².');break;
 case 'ТОРОИД':exact(torus(62,31,1.15),'Тороид обозначает тело кольцевого типа. Здесь выбран круговой тор с R = 62, r = 31 и другой ориентацией проекции. Форма является частным математическим примером.');break;
 case 'МЕРКАБА':exact(starTetra()+circle(150,150,112),'Показана звездчатая тетраэдральная модель и ее описанная сфера. Два правильных тетраэдра получены центральным отражением. Геометрическое тело следует отличать от религиозного понятия меркабы.');break;
 case 'ЗВЕЗДЧАТЫЙ ТЕТРАЭДР':exact(starTetra(),'Соединение двух правильных тетраэдров с общим центром. Вершины вместе образуют вершины куба. Пересечение тел является правильным октаэдром.');break;
 case 'ТЕССЕРАКТ':case 'ПЕНТЕРАКТ':{let n=name==='ТЕССЕРАКТ'?4:5,m=hypercube(n);parameters={dimension:n};exact(hyper(n),`Линейная проекция ${n}-мерного гиперкуба. Вершины задаются координатами ±1. ${m.vertices.length} вершин и ${m.edges.length} ребер: n·2^(n - 1). Ребро меняет ровно одну координату. Углы и длины на экране не сохраняются.`,['Перебрать все двоичные комбинации координат.','Соединить вершины, отличающиеся одной координатой.','Спроецировать по фиксированным векторам базиса.']);break;}
 case 'ГИПЕРСФЕРА':exact(circle()+[15,35,55,75].map(r=>circle(150,150,r)).join('')+line([60,150],[240,150]),'Гиперсфера S³: x₁² + x₂² + x₃² + x₄² = R². Показаны плоские сечения x₃ = 0 при разных x₄: окружности радиусов √(R² - x₄²). Это диаграмма сечений, а не полный вид четырехмерной поверхности.');break;
 case 'ФРАКТАЛ':exact(fractal(),'Четвертая итерация треугольника Серпинского. Каждый треугольник заменяется тремя копиями масштаба 1/2. Число малых треугольников 3⁴ = 81; доля оставшейся площади (3/4)⁴.');break;
 case 'ФРАКТАЛЬНАЯ ВСЕЛЕННАЯ':art(fractal(3)+circle(150,150,116),'Авторская космологическая композиция: третья итерация треугольника Серпинского внутри окружности. Она не доказывает фрактальное устройство Вселенной.');break;
 case 'СНЕЖИНКА':{for(let i=0;i<6;i++){let a=i*Math.PI/3,tip=[150+96*Math.cos(a),150+96*Math.sin(a)];out+=line([150,150],tip);for(let r of [40,65])for(let s of [-1,1]){let b=[150+r*Math.cos(a),150+r*Math.sin(a)];out+=line(b,[b[0]+22*Math.cos(a+s*Math.PI/3),b[1]+22*Math.sin(a+s*Math.PI/3)]);}}exact(out,'Идеализированный шестилучевой рисунок: оси через 60°, ответвления через 60° к лучу. Действительная снежинка имеет вариации; эта схема показывает шестикратную симметрию.');break;}
 case 'ПЧЕЛИНЫЕ СОТЫ':exact(honeycomb(),'19 правильных шестиугольников радиуса R = 22. Центры: x = 3Rq/2, y = √3R(t + q/2). Соседи имеют общую сторону. Идеальная плоская модель отличается от живых восковых сот.');break;
 case 'РАКОВИНА НАУТИЛУСА':art(spiral('gold',1.5)+points(14,90).map((p,i)=>line([150,150],[150+(15+5*i)*Math.cos(i*.45),150+(15+5*i)*Math.sin(i*.45)])).join(''),'Стилизованный спиральный контур с перегородками камер. Параметры выбраны для рисунка; соответствие реальной раковины золотой спирали не предполагается.');break;
 case 'ТРИКВЕТР':{let p=points(3,68);out=p.map(c=>{let tip=[300-c[0],300-c[1]];return path(`M150 150A68 68 0 0 1 ${tip.map(f)}A68 68 0 0 1 150 150`);}).join('');exact(out,'Три одинаковые линзы образованы шестью дугами окружностей. Центры вспомогательных окружностей образуют равносторонний треугольник, каждая окружность проходит через общий центр. Рисунок обладает трехкратной вращательной симметрией; способы переплетения в исторических орнаментах различаются.');break;}
 case 'ИНЬ-ЯН':exact(circle()+path('M150 60a45 45 0 0 1 0 90a45 45 0 0 0 0 90')+circle(150,105,7)+dot(150,195,7),'Круг радиуса 90 разделен двумя полуокружностями радиуса 45. Две малые окружности расположены в центрах полуокружностей. Поворот на 180° меняет местами части рисунка.');break;
 case 'ЦИРКУМПУНКТ':exact(circle()+dot(150,150,5),'Окружность и обозначение ее центра. Полная вращательная симметрия. Значения такого знака зависят от конкретного источника и традиции.');break;
 case 'ДРЕВО ЖИЗНИ':exact(tree(),'Диаграмма десяти узлов и 22 связей. Выбран один вариант западной герметической схемы; распределение путей в исторических каббалистических изображениях различается. Линии являются связями графа, а не метрическими отношениями.');break;
 case 'СРЕДИННЫЙ СТОЛП':exact(tree(1),'Выделены четыре центральных узла выбранной схемы Древа жизни. Центральная ось вертикальна. Даат не добавлен как одиннадцатая сефира.');break;
 case 'МОЛНИЯ ТВОРЕНИЯ':exact(tree(2),'Последовательная ломаная через десять узлов Древа жизни: верхний центр, правая и левая пары, центральные и нижние узлы. Это схема порядка, а не физическая траектория энергии.');break;
 case 'АРХЕТИП ЕДИНСТВА':art(circle()+points(6,55).map(p=>line([150,150],p)+circle(...p,12)).join('')+dot(),'Шесть частей сходятся к единому центру внутри общей границы. Авторская композиция на основе окружностей и радиальных связей.');break;
 case 'АРХЕТИП ПОЛЯРНОСТИ':art(circle(105,150,48)+circle(195,150,48)+line([105,150],[195,150])+dot(105,150)+circle(195,150,5),'Два равноправных центра, соединенных осью. Одна точка заполнена, другая оставлена открытой.');break;
 case 'АРХЕТИП БАЛАНСА':art(line([65,125],[235,125])+poly([[150,125],[130,200],[170,200]])+path('M75 125v42M225 125v42')+path('M53 167Q75 193 97 167ZM203 167Q225 193 247 167Z'),'Симметричная композиция весов на треугольной опоре. Равные плечи отражают выбранную метафору равновесия.');break;
 case 'АРХЕТИП ПОТОКА':art(wave(3)+line([45,150],[255,150]),'Три синусоидальные кривые вокруг направляющей оси. Их движение выражено изменением высоты вдоль одного направления.');break;
 case 'АРХЕТИП РЕЗОНАНСА':art([28,45,62].map(r=>circle(105,150,r)+circle(195,150,r)).join(''),'Две системы концентрических окружностей образуют пересечения. Это метафора взаимодействия, а не модель измеренного резонанса.');break;
 case 'АРХЕТИП ТРАНСФОРМАЦИИ':art(polygon(3,90)+polygon(4,65)+circle(150,150,36),'Последовательное наложение треугольника, квадрата и окружности. Изменение числа сторон служит визуальной метафорой перехода.');break;
 case 'АРХЕТИП БЕСКОНЕЧНОСТИ':art(curve(sample(t=>[150+95*Math.cos(t*TAU)/(1+Math.sin(t*TAU)**2),150+95*Math.sin(t*TAU)*Math.cos(t*TAU)/(1+Math.sin(t*TAU)**2)])),'Лемниската Бернулли в параметрической форме. Знак бесконечности здесь выбран как авторская метафора, не как геометрия сознания.');break;
 case 'КРИСТАЛЛ':art(poly([[150,40],[205,85],[205,215],[150,260],[95,215],[95,85]])+line([150,40],[150,260])+line([95,85],[205,85])+line([95,215],[205,215]),'Стилизованный шестигранный кристалл с продольной осью. Конкретная кристаллографическая структура минерала не задана.');break;
 case 'АЛМАЗ':art(poly([[60,110],[95,75],[205,75],[240,110],[150,235]])+line([60,110],[240,110])+line([95,75],[120,110])+line([205,75],[180,110])+line([120,110],[150,235])+line([180,110],[150,235]),'Фронтальная схема ограненного камня. Она изображает огранку, а не атомную решетку алмаза.');break;
 case 'ВИХРЬ':art(rosette(7,94,58,.2)+circle(150,150,18),'Семь изогнутых лепестков вокруг центра. Наклон контрольных точек создает впечатление вращения.');break;
 case 'ЭНЕРГЕТИЧЕСКАЯ ВОРОНКА':art([0,1,2,3,4,5].map(k=>ellipse(150,70+k*31,86-k*13,12)).join('')+line([64,70],[143,225])+line([236,70],[157,225]),'Сужающаяся последовательность эллиптических сечений. Художественная схема воронки, без утверждения о существовании энергетического объекта.');break;
 case 'ПОТОКОВАЯ СПИРАЛЬ':art(curve(sample(t=>[150+70*Math.cos(t*TAU*3)*(1-t*.6),45+210*t]))+line([150,45],[150,255]),'Спиральный путь вдоль вертикальной оси, с уменьшающимся радиусом. Выбранная проекция передает движение.');break;
 case 'СВЕТОВОЙ СТОЛБ':art([120,135,150,165,180].map(x=>line([x,55],[x,245])).join('')+ellipse(150,55,30,10)+ellipse(150,245,30,10),'Пять параллельных вертикалей между двумя эллиптическими основаниями. Авторская метафора оси и направленности.');break;
 case 'ЭНЕРГЕТИЧЕСКИЙ КОКОН':art([38,55,72].map(r=>ellipse(150,150,r,105)).join('')+dot(),'Три вложенных овальных контура и центральная точка. Их параметры заданы для композиции, не для описания физического поля.');break;
 case 'ВЕКТОРНЫЙ ТОРОИД':art(torus(65,20,.6)+points(8,102).map(p=>line([150,150],p)).join(''),'Параметрический тор дополнен восемью радиальными направлениями. Линии не обозначают измеренные векторы силы.');break;
 case 'ВОЛНА СТОЯЧЕЙ ГЕОМЕТРИИ':art(wave(2)+wave(2,Math.PI)+[45,97.5,150,202.5,255].map(x=>dot(x,150)).join(''),'Пары синусоидальных профилей и выделенные узлы. Это композиция на тему стоячей волны, без заданных физических единиц.');break;
 case 'ГАРМОНИЧЕСКОЕ ПОЛЕ':art(curve(sample(t=>[150+90*Math.sin(3*TAU*t),150+90*Math.sin(2*TAU*t)]))+circle(150,150,105),'Фигура Лиссажу с частотным отношением 3:2 внутри окружности. Математическая кривая используется для авторской интерпретации.');break;
 case 'МНОГОМЕРНАЯ РЕШЕТКА':art(grid(4,true)+poly([[40,150],[150,40],[260,150],[150,260]]),'Решетка с диагональными связями внутри ромбовидной границы. Число измерений не определено исходной карточкой.');break;
 case 'КРИСТАЛЛИЧЕСКАЯ МАТРИЦА':art(grid(5)+points(4,110,150,150,0).map(p=>circle(...p,8)).join(''),'Пять горизонтальных и пять вертикальных линий с четырьмя опорными узлами. Это авторская композиция порядка.');break;
 case '64-ТЕТРАЭДРНАЯ РЕШЕТКА':{for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++){let x=75+i*39+k*8,y=85+j*35-k*12;out+=poly([[x,y-13],[x-12,y+7],[x+12,y+7]])+line([x,y-13],[x,y+2])+line([x,y+2],[x-12,y+7])+line([x,y+2],[x+12,y+7]);}art(out,'64 тетраэдральные ячейки организованы как 4 × 4 × 4. Их размещение является авторской схемой; конкретная эталонная пространственная решетка в таблице не задана.');break;}
 case 'ВЕКТОРНАЯ МАТРИЦА':art(grid(4)+points(8,86).map(p=>line([150,150],p)+dot(...p,2)).join(''),'Координатная решетка и восемь направлений от центра к узлам. Векторы представлены как геометрические отрезки.');break;
 case 'ДЖИТТЕРБАГ-ТРАНСФОРМАЦИЯ':art(solid('КУБООКТАЭДР',65)+solid('ОКТАЭДР',65),'Два состояния пространственной структуры наложены для сравнения. Режим построения показывает контуры, а не кинематическую модель механизма Фуллера. Для непрерывной трансформации требуется отдельный алгоритм.');break;
 case 'СЕТЬ ИНДРЫ':art(points(12,100).map((p,i,all)=>circle(...p,7)+all.slice(i+1).map(q=>line(p,q)).join('')).join(''),'Двенадцать узлов попарно соединены. Конечный граф является визуальной метафорой бесконечной сети из исходной карточки.');break;
 case 'МИРОВОЕ ДРЕВО':{out=line([150,265],[150,90]);for(let i=0;i<4;i++){let y=100+i*30;out+=line([150,y+20],[65+i*14,y-20])+line([150,y+20],[235-i*14,y-20]);}out+=line([150,245],[95,280])+line([150,245],[205,280])+circle(150,75,24);art(out,'Симметричный ствол, четыре уровня ветвей и два корня. Схема соединения верхнего и нижнего уровней, без привязки к одному историческому изображению.');break;}
 case 'ШРИ ЯНТРА':{parameters={triangles:shriTriangles,...shriVerification};out=shriTriangles.map(t=>poly(t.map(([x,y])=>[150+78*x,150+78*y]))).join('');exact(out+circle(150,150,80)+rosette(8,92,82)+rosette(16,106,94)+[108,112,116].map(r=>circle(150,150,r)).join('')+poly([[25,25],[275,25],[275,275],[25,275]])+dot(),'Численно согласованная модель по условиям (i)-(iii) Chiodo (2021). Девять равнобедренных треугольников имеют общую ось: пять направлены вниз, четыре вверх. Невязка тройных пересечений меньше 10⁻⁹ радиуса; отдельно проверены 43 треугольные области нечетного покрытия: 14 + 10 + 10 + 8 + 1. Внешний квадрат и лепестки служат орнаментальным обрамлением.', ['Задать четыре уровня оснований по выбранной модели.','Решить систему согласования вершин и пересечений.','Построить пять нижних и четыре верхних треугольника.','Добавить восемь и шестнадцать лепестков, окружности и внешнюю границу.']);break;}
 default:if(name.startsWith('ЯНТРА ')){const specs={'ЯНТРА САТУРНА':[4,3,0],'ЯНТРА УРАНА':[8,2,.2],'ЯНТРА НЕПТУНА':[3,5,.3],'ЯНТРА ПЛУТОНА':[5,4,.4],'ЯНТРА СОЛНЦА':[12,1,0],'ЯНТРА ЛУНЫ':[6,2,.6],'ЯНТРА МЕРКУРИЯ':[8,3,.1],'ЯНТРА ВЕНЕРЫ':[5,2,0],'ЯНТРА МАРСА':[3,3,0],'ЯНТРА ЮПИТЕРА':[9,2,.3]},[n,l,a]=specs[name];out=polygon(4,116,150,150,Math.PI/4)+rosette(n,91,38,a);for(let i=0;i<l;i++)out+=polygon(n,28+i*13,150,150,a);art(out+dot(),`Индивидуальная композиция: внешний квадрат, ${n} лепестков и ${l} вложенных многоугольника. Авторская визуальная интерпретация. Для исторической реконструкции планетной янтры нужен конкретный источник или эталон.`);}else throw new Error('Нет визуализации: '+name);
 }
 const tags=out.match(/<(?:circle|line|path|polygon|rect)\b[^>]*\/>/g)||[];
 return{name,mode,math,algorithm,parameters,shapes:tags,markup:out};
}
export function svgFor(name,{guides=false,view=0}={}){const g=geometry(name,{view});return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300" role="img" aria-label="${name}" fill="none" stroke="#D6B56E" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><title>${name}</title><g class="aux" ${guides?'':'hidden'}>${circle(150,150,110)+line([20,150],[280,150])+line([150,20],[150,280])}</g><g class="drawing">${g.shapes.map((s,i)=>`<g class="step" style="--i:${i}">${s}</g>`).join('')}</g></svg>`;}

export function geometry(name,{view=0}={}){let g=baseGeometry(name),update=auditedGeometry(name,view);if(update)g={...g,...update};if(['СЕМЯ ЖИЗНИ','ЦВЕТОК ЖИЗНИ'].includes(name)){let r=name==='СЕМЯ ЖИЗНИ'?98:102;g.markup+=circle(150,150,r).replace('<circle','<circle class="framing"')+circle(150,150,r+5).replace('<circle','<circle class="framing"');g.math+=' Две внешние окружности добавлены как отдельное необязательное обрамление.';g.algorithm.push('Добавить необязательные внешние контуры.');}g.shapes=g.markup.match(/<(?:circle|line|path|polygon|rect)\b[^>]*\/>/g)||[];return g;}
