export const books=[
{title:'Начала / Elements',author:'Евклид; электронное издание David E. Joyce',year:'1996 (электронное издание)',kind:'Исторические источники',topics:'Окружности, многоугольники, платоновы тела',description:'Текст и интерактивные пояснения к классическому геометрическому трактату. Книги I-IV посвящены плоским построениям, книга XIII связывает пять правильных тел.',url:'https://mathcs.clarku.edu/~djoyce/elements/elements.html'},
{title:'Regular Polytopes',author:'H. S. M. Coxeter',year:'1973, третье издание',kind:'Академические исследования',topics:'Многогранники, тессеракт, многомерные правильные тела',description:'Систематическое изложение правильных многогранников и многомерных аналогов. Помогает отличать свойства тела от искажений его плоской проекции.',url:'https://old.maa.org/press/maa-reviews/regular-polytopes'},
{title:'The Symmetries of Things',author:'John H. Conway, Heidi Burgiel, Chaim Goodman-Strauss',year:'2008',kind:'Академические исследования',topics:'Оси отражения, орнаменты, решетки, симметрия',description:'Исследование симметрий конечных фигур и повторяющихся узоров. Дает язык для сравнения розеток, орнаментов и пространственных структур.',url:'https://www.routledge.com/The-Symmetries-of-Things/Burgiel-Conway-Goodman-Strauss/p/book/9781568812205'},
{title:'The Topkapi Scroll: Geometry and Ornament in Islamic Architecture',author:'Gülru Necipoğlu; геометрический анализ Mohammad al-Asad',year:'1995',kind:'Академические исследования',topics:'Геометрия в архитектуре, звезды, многогранные узоры',description:'Исследование архитектурного свитка из собрания Топкапы и способов передачи геометрических чертежей. Соединяет анализ построений с историей мастерских.',url:'https://www.getty.edu/publications-reports/item/248TH5'},
{title:'Tilings and Patterns',author:'Branko Grünbaum, G. C. Shephard',year:'1987',kind:'Академические исследования',topics:'Замощения, соты, периодические сетки',description:'Монография о разбиении плоскости и повторении мотивов. Полезна для анализа общих сторон, узлов и групп симметрии геометрических сеток.',url:'https://search.worldcat.org/title/Tilings-and-patterns/oclc/13092426'},
{title:'Tantra: enlightenment to revolution',author:'Imma Ramos',year:'2020',kind:'Музейные исследования',topics:'Янтры, мандалы, тантрическое искусство',description:'Каталог выставки Британского музея, рассматривающий ритуальные изображения в религиозном и историческом контексте. Помогает различать традиционные предметы и поздние западные интерпретации.',url:'https://www.britishmuseum.org/sites/default/files/2020-04/BMMag96-04-FINAL.pdf'},
{title:'Sacred Geometry: Philosophy and Practice',author:'Robert Lawlor',year:'1982',kind:'Современные эзотерические публикации',topics:'Золотая пропорция, спирали, геометрические практики',description:'Авторское символическое прочтение пропорций и практические построения. Исторические и духовные выводы книги следует проверять отдельно от геометрических упражнений.',url:'https://www.thamesandhudson.com/products/sacred-geometry-art-and-imagination'},
{title:'De occulta philosophia / Three Books of Occult Philosophy',author:'Heinrich Cornelius Agrippa; перевод James Freake',year:'1533; перевод 1651',kind:'Исторические источники',topics:'Западные планетарные магические квадраты',description:'Вторая книга, глава XXII описывает числовые таблицы планет. Это источник западной оккультной традиции; его нельзя использовать как свидетельство происхождения индуистских янтр.',url:'https://sacred-texts.com/eso/pnm/pnm2.htm'}
];
export const publications=[
{title:'On the construction of the Śrī Yantra',author:'Alessandro Chiodo',year:'2021',kind:'Научные публикации',topics:'Шри-янтра, согласование тройных пересечений',description:'Математическое исследование семейства согласованных моделей Шри-янтры и построения циркулем и линейкой.',url:'https://www.numdam.org/articles/10.5802/crmath.163/'},
{title:'Geometric Patterns in Islamic Art',author:'Department of Islamic Art, The Metropolitan Museum of Art',year:'2001',kind:'Музейные публикации',topics:'Круги, звезды, многоугольники, архитектура',description:'Обзор основных повторяющихся мотивов геометрического декора и их сочетаний в произведениях искусства.',url:'https://www.metmuseum.org/essays/geometric-patterns-in-islamic-art'},
{title:'Frequently Asked Questions about Snow Crystals',author:'Kenneth G. Libbrecht, Caltech',year:'Дата обновления не указана',kind:'Университетские материалы',topics:'Снежинка, шестикратная симметрия, рост кристаллов',description:'Объяснение связи шестилучевого роста с кристаллической решеткой льда и условиями среды.',url:'https://www.its.caltech.edu/~atomic/snowcrystals/faqs/faqs.htm'},
{title:'Chambered Shells',author:'Smithsonian Ocean',year:'2018',kind:'Музейные публикации',topics:'Раковина наутилуса, камеры и перегородки',description:'Анатомическая фотография разреза и пояснение связи камер с сифункулом. Изображение используется как внешний ориентир, без копирования в атлас.',url:'https://ocean.si.edu/ocean-life/invertebrates/chambered-shells'}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function libraryMarkup(){return `<section id="reading-library"><div class="page-title"><p class="eyebrow">КНИГИ И ПУБЛИКАЦИИ</p><h2>Библиотека сакральной геометрии</h2><p>Исторические тексты, академические исследования и авторские эзотерические публикации представлены отдельно. Ссылки ведут к издателям, библиотечным каталогам и легальным источникам.</p></div>${[...new Set([...books,...publications].map(x=>x.kind))].map(kind=>`<section><h3>${esc(kind)}</h3><div class="essays">${[...books,...publications].filter(x=>x.kind===kind).map(x=>`<article class="essay"><p class="eyebrow">${esc(x.year)}</p><h3>${esc(x.title)}</h3><p><b>${esc(x.author)}</b></p><p>${esc(x.description)}</p><p>Темы: ${esc(x.topics)}</p><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Издание или источник ↗</a></article>`).join('')}</div></section>`).join('')}</section>`;}
