import {geometry} from './geometry.js';
import {education} from './education.js';
import {mainCatalog} from './catalog.js';
const MM_PER_PT=25.4/72,W=76,H=106,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let resourcesPromise;
const bytesToBase64=b=>{let parts=[];for(let i=0;i<b.length;i+=8192)parts.push(String.fromCharCode(...b.subarray(i,i+8192)));return btoa(parts.join(''));};
function script(src){return new Promise((resolve,reject)=>{let s=document.createElement('script');s.src=new URL(src,import.meta.url);s.onload=resolve;s.onerror=()=>reject(Error('Не удалось загрузить библиотеку экспорта'));document.head.append(s);});}
export async function loadPrintResources(){return resourcesPromise??= (async()=>{await script('./vendor/jspdf.umd.min.js');await script('./vendor/svg2pdf.umd.min.js');await script('./vendor/fflate.umd.js');const fonts=await Promise.all(['./assets/print-sans-subset.ttf','./assets/prata.ttf'].map(async p=>{let r=await fetch(new URL(p,import.meta.url));if(!r.ok)throw Error('Не удалось загрузить шрифты печати');return bytesToBase64(new Uint8Array(await r.arrayBuffer()));}));return{sans:fonts[0],serif:fonts[1]};})();}
export function pdfDocument(fonts){const doc=new window.jspdf.jsPDF({orientation:'portrait',unit:'mm',format:[W,H],compress:true,putOnlyUsedFonts:true});doc.addFileToVFS('PrintSans.ttf',fonts.sans);doc.addFont('PrintSans.ttf','PrintSans','normal');doc.addFileToVFS('PrintSerif.ttf',fonts.serif);doc.addFont('PrintSerif.ttf','PrintSerif','normal');doc.setFont('PrintSans');return doc;}
function wrap(text,font,size,width,doc){doc.setFont(font);doc.setFontSize(size);return doc.splitTextToSize(String(text).replace(/[ё]/g,'е').replace(/[Ё]/g,'Е').replace(/[—–]/g,'-'),width);}
export function printNotes(s){const g=geometry(s.name),p=g.parameters;let form='Индивидуальная символическая композиция.';
if(g.mode==='exact')form=p.vertices?`${p.vertices.length} вершин, ${p.edges.length} ребер${p.faces?', '+p.faces.length+' граней':''}. Пространственная проекция.`:p.dimension?`${p.dimension}-мерный гиперкуб. Плоская проекция.`:p.n?`Правильный ${p.n}-угольник: равные стороны и углы.`:'Геометрическая модель с указанным в атласе построением.';
const brief={'ТОЧКА':'Положение в пространстве без размера.','ЛИНИЯ':'Отрезок прямой между двумя точками.','КРУГ':'Граница круга равноудалена от центра.','СПИРАЛЬ':'Спираль Архимеда с постоянным шагом витков.','ПРЯМОУГОЛЬНИК':'Четыре прямых угла; противоположные стороны равны.','ПЕНТАГРАММА':'Диагонали правильного пятиугольника образуют звезду.','ГЕКСАГРАММА':'Два равносторонних треугольника противоположной ориентации.','ВЕЗИКА ПИСЦИС':'Две равные окружности; расстояние центров равно радиусу.','СЕМЯ ЖИЗНИ':'Одна окружность и шесть равных вокруг нее.','ЦВЕТОК ЖИЗНИ':'19 равных окружностей на треугольной решетке.','ЯЙЦО ЖИЗНИ':'Восемь равных сфер в вершинах куба, вид вдоль диагонали.','ПЛОД ЖИЗНИ':'13 равных окружностей в шестикратной композиции.','КУБ МЕТАТРОНА':'13 центров соединены 78 отрезками.','СФЕРА':'Все точки поверхности равноудалены от центра.','ТОР':'Круговое сечение вращается вокруг внешней оси.','ТОРОИД':'Замкнутые тороидальные пути вокруг оси.','ВЕКТОРНЫЙ ТОРОИД':'Направленные пути на тороидальной поверхности.','ДВОЙНАЯ СПИРАЛЬ':'Две винтовые линии с фазовым сдвигом 180°.','ФРАКТАЛ':'Треугольник Серпинского: три копии масштаба 1/2.','СНЕЖИНКА':'Шесть лучей отражают симметрию решетки льда.','ПЧЕЛИНЫЕ СОТЫ':'Правильные шестиугольники образуют плоское замощение.','РАКОВИНА НАУТИЛУСА':'Спиральная раковина с изогнутыми перегородками камер.','ЗОЛОТАЯ СПИРАЛЬ':'Радиус возрастает в φ раз за четверть оборота.','СПИРАЛЬ ФИБОНАЧЧИ':'Четверти окружностей в квадратах Фибоначчи.','МЕРКАБА':'Два правильных тетраэдра противоположной ориентации.','ЗВЕЗДЧАТЫЙ ТЕТРАЭДР':'Соединение двух взаимопроникающих тетраэдров.','ВИХРЬ':'Спиральные пути приближаются к общей оси.','ТРИКВЕТР':'Три одинаковые дуги образуют трехлепестковый контур.','ИНЬ-ЯН':'Круг разделен двумя полуокружностями.','ЦИРКУМПУНКТ':'Окружность с отмеченным центром.','ШРИ ЯНТРА':'Девять согласованных треугольников; 43 внутренние области.','МИРОВОЕ ДРЕВО':'Авторский образ кроны, ствола и корней.','ДРЕВО ЖИЗНИ':'Десять сфирот и 22 пути герметической схемы.','СРЕДИННЫЙ СТОЛП':'Центральная ось выбранной схемы Древа.','МОЛНИЯ ТВОРЕНИЯ':'Последовательный путь через десять сфирот.'};
form=brief[s.name]||form;if(s.name.startsWith('ЯНТРА '))form='Современная композиция; каноническая схема не утверждается.';
let history='Атрибуция выбранного рисунка требует исторического источника.';if(['ТОЧКА','ЛИНИЯ','КРУГ','КВАДРАТ','ПРЯМОУГОЛЬНИК'].includes(s.name))history='Определения и построения изложены в «Началах» Евклида.';if(['ГЕКСАГОН','ОКТАГОН'].includes(s.name))history='Пример: индийская джали начала XVII века, The Met, 1985.240.2.';if(['ТЕТРАЭДР','ОКТАЭДР','КУБ (ГЕКСАЭДР)','ИКОСАЭДР','ДОДЕКАЭДР'].includes(s.name))history='Евклид описал построения правильных тел в книге XIII «Начал».';if(s.name==='ШРИ ЯНТРА')history='Индуистская тантрическая традиция; построение Chiodo, 2021.';if(s.name==='СНЕЖИНКА')history='Модель роста ледяного кристалла; пояснение K. Libbrecht, Caltech.';if(s.name==='РАКОВИНА НАУТИЛУСА')history='Анатомическая стилизация по разрезам Smithsonian Ocean.';
return{form,principle:String(s.principle).trim(),history,meaning:String(s.archetype).split(',')[0].trim()+'. Авторская трактовка.'};}
export function cardLayout(s,side,doc,{marks=false}={}){const items=[],notes=printNotes(s),text=(value,x,y,width,size,font='PrintSans',color='#F5F0E8',lineHeight=size*MM_PER_PT*1.3)=>{const lines=wrap(value,font,size,width,doc);const height=lines.length*lineHeight;items.push({type:'text',text:value,lines,x,y,width,size,font,color,lineHeight});return y+(lines.length-1)*lineHeight;};
const titles=wrap(s.name,'PrintSerif',15,62,doc);if(titles.length>3)throw Error('Название не помещается: '+s.name);items.push({type:'text',text:s.name,lines:titles,x:7,y:13,width:62,size:15,font:'PrintSerif',color:'#F2DEA3',lineHeight:6.5});
if(side==='front'){items.push({type:'geometry',markup:geometry(s.name).markup,x:12,y:32,width:52,height:52});text(s.category,7,92,62,9.5,'PrintSans','#D6B56E',4.1);}else{let y=31;for(let [label,value]of [['ФОРМА',notes.form],['ПРИНЦИП',notes.principle],['ИСТОРИЯ',notes.history],['ЗНАЧЕНИЕ',notes.meaning]]){y=text(label,7,y,62,9,'PrintSans','#D6B56E',3.9)+4.5;y=text(value,7,y,62,10,'PrintSans','#F5F0E8',4.4)+7;}}
for(const item of items.filter(i=>i.type==='text')){const finalY=item.y+(item.lines.length-1)*item.lineHeight; if(item.size<9||item.y-item.size*MM_PER_PT<7||finalY>99.2)throw Error('Текст выходит за безопасное поле: '+s.name);doc.setFont(item.font);doc.setFontSize(item.size);if(item.lines.some(l=>doc.getTextWidth(l)>62.02))throw Error('Строка выходит за безопасное поле: '+s.name);}
return{symbol:s.id,side,width:W,height:H,trim:[3,3,73,103],safe:[7,7,69,99],marks,items};}
export function layoutSvg(layout,fonts,{embedFonts=true}={}){const faces=embedFonts?`<style>@font-face{font-family:PrintSans;src:url(data:font/ttf;base64,${fonts.sans})}@font-face{font-family:PrintSerif;src:url(data:font/ttf;base64,${fonts.serif})}</style>`:'';let content=`<rect width="76" height="106" fill="#050509"/><rect x="5" y="5" width="66" height="96" fill="none" stroke="#D6B56E" stroke-width=".2" stroke-opacity=".4"/>`;
for(let i=0;i<14;i++){let x=5+(i*17.7)%65,y=5+(i*27.3)%95;content+=`<circle cx="${x}" cy="${y}" r=".12" fill="#D6B56E" fill-opacity=".35"/>`;}
for(const item of layout.items)if(item.type==='text')content+=`<text x="${item.x}" y="${item.y}" fill="${item.color}" font-family="${item.font}" font-size="${item.size*MM_PER_PT}">${item.lines.map((l,k)=>`<tspan x="${item.x}" y="${item.y+k*item.lineHeight}">${esc(l)}</tspan>`).join('')}</text>`;else content+=`<svg x="${item.x}" y="${item.y}" width="${item.width}" height="${item.height}" viewBox="0 0 300 300" fill="none" stroke="#D6B56E" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round">${item.markup.replaceAll('class="solid"','fill="#D6B56E" stroke="none"')}</svg>`;
if(layout.marks)content+=`<g stroke="#F5F0E8" stroke-width=".15"><path d="M0 3h2M3 0v2M74 3h2M73 0v2M0 103h2M3 104v2M74 103h2M73 104v2"/></g>`;
return `<svg xmlns="http://www.w3.org/2000/svg" width="76mm" height="106mm" viewBox="0 0 76 106"><defs>${faces}</defs>${content}</svg>`;}
async function appendPage(doc,layout,fonts,first){if(!first)doc.addPage([W,H],'portrait');const svg=new DOMParser().parseFromString(layoutSvg(layout,fonts,{embedFonts:false}),'image/svg+xml').documentElement;await doc.svg(svg,{x:0,y:0,width:W,height:H});const k=72/25.4,page=doc.internal.getCurrentPageInfo().pageNumber;doc.internal.events.subscribe('putPage',function(data){if(data.pageNumber===page){this.internal.write(`/TrimBox [${3*k} ${3*k} ${73*k} ${103*k}]`);this.internal.write(`/BleedBox [0 0 ${76*k} ${106*k}]`);}});}
export async function createDeck(list,{marks=false,includeIndividual=false,onProgress=()=>{}}={}){const fonts=await loadPrintResources(),deck=pdfDocument(fonts),files={},layouts=[];let first=true;for(let i=0;i<list.length;i++){const s=list[i],individual=includeIndividual?pdfDocument(fonts):null,name=String(s.id).padStart(2,'0')+'-'+s.name.toLowerCase().replace(/[^а-яa-z0-9]+/g,'-');for(const side of ['front','back']){const l=cardLayout(s,side,deck,{marks});layouts.push(l);await appendPage(deck,l,fonts,first);first=false;if(individual)await appendPage(individual,l,fonts,side==='front');if(includeIndividual)files[name+'/'+side+'.svg']=new TextEncoder().encode(layoutSvg(l,fonts));}if(individual)files[name+'/'+name+'.pdf']=new Uint8Array(individual.output('arraybuffer'));onProgress(i+1,list.length);await new Promise(r=>setTimeout(r,0));}files['atlas-deck.pdf']=new Uint8Array(deck.output('arraybuffer'));files['README.txt']=new TextEncoder().encode('Финальный размер: 70 x 100 мм. Страница с вылетами: 76 x 106 мм. Вылеты: 3 мм. Безопасное поле: 4 мм от линии реза. RGB, не PDF/X. Шрифты встроены в PDF. Золотой цвет является печатной краской, не металлической фольгой. Страницы идут парами: лицо, оборот. Для двусторонней печати карточного формата используйте переворот по длинной стороне и отключите масштабирование. Сначала выполните пробную печать одной пары. Для печати на больших листах типографии требуется спуск полос. CMYK/PDF-X требуют ICC-профиля и требований типографии.');return{pdf:files['atlas-deck.pdf'],files,layouts};}
function save(bytes,name,type){let url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export async function mountPrint(container,all){const symbols=mainCatalog(all),selected=new Set,fonts=await loadPrintResources(),measure=pdfDocument(fonts);let current=symbols[0],side='front',zoom=1,marks=false;
container.innerHTML=`<div class="page-title"><p class="eyebrow">КОЛЛЕКЦИОННАЯ КОЛОДА</p><h1>Подготовить карточки к печати</h1><p>Лицевая и оборотная стороны 70 × 100 мм. Векторная графика, встроенные шрифты, вылеты по 3 мм.</p></div><div class="print-workspace"><section class="print-selection"><h2>Выберите карточки</h2><div class="print-actions"><button id="select-all">Весь каталог</button><button id="select-none">Снять выбор</button></div><label for="print-category">Выбрать категорию</label><select id="print-category"><option value="">Выберите категорию</option>${[...new Set(symbols.map(s=>s.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select><p id="selection-count" role="status">Выбрано: 0</p><div class="print-list">${symbols.map(s=>`<div><label><input type="checkbox" data-select="${s.id}"><span>${esc(s.name)}</span></label><button data-preview="${s.id}" aria-label="Предпросмотр ${esc(s.name)}">Просмотр</button></div>`).join('')}</div></section><section class="print-preview"><h2 id="preview-title">${esc(current.name)}</h2><div class="print-actions"><button id="front" aria-pressed="true">Лицевая</button><button id="back" aria-pressed="false">Оборотная</button><button id="print-zoom-out" aria-label="Уменьшить предпросмотр">−</button><button id="print-zoom-in" aria-label="Увеличить предпросмотр">+</button></div><div class="print-canvas" id="print-canvas"></div><label class="print-check"><input id="crop-marks" type="checkbox">Показать метки реза</label><div class="print-actions"><button id="current-pdf">PDF этой карточки</button><button id="current-svg">SVG этой стороны</button></div><h3>Экспорт выбранной колоды</h3><div class="print-actions"><button id="deck-pdf" class="primary" disabled>Общий PDF</button><button id="deck-zip" class="primary" disabled>ZIP со всеми файлами</button></div><p id="print-status" role="status" aria-live="polite"></p><details class="print-spec"><summary>Параметры печати и цвет</summary><p>Страница 76 × 106 мм, обрез 70 × 100 мм, безопасное поле 4 мм. Основной текст 10 pt, названия 15 pt, минимальный шрифт 9 pt. Золотые линии имеют толщину 0,2 мм. Файлы RGB, без растровых изображений.</p><p>CMYK и PDF/X готовятся после выбора ICC-профиля типографии. Настоящая фольга требует отдельного технологического слоя; золотой цвет в этих файлах является обычной краской.</p><p>Пары страниц идут как лицо и оборот. Для печати в размер отключите масштабирование, используйте переворот по длинной стороне и сделайте пробную пару. Спуск на большие листы выполняется типографией.</p></details></section></div>`;
const $=id=>container.querySelector('#'+id),updateSelection=()=>{container.querySelectorAll('[data-select]').forEach(c=>c.checked=selected.has(Number(c.dataset.select)));$('selection-count').textContent='Выбрано: '+selected.size;$('deck-pdf').disabled=$('deck-zip').disabled=!selected.size;},preview=()=>{$('preview-title').textContent=current.name;$('print-canvas').innerHTML=layoutSvg(cardLayout(current,side,measure,{marks}),fonts);$('print-canvas').firstElementChild.style.width=76*3.5*zoom+'px';$('front').setAttribute('aria-pressed',side==='front');$('back').setAttribute('aria-pressed',side==='back');};
$('select-all').onclick=()=>{symbols.forEach(s=>selected.add(s.id));updateSelection();};$('select-none').onclick=()=>{selected.clear();updateSelection();};$('print-category').onchange=e=>{symbols.filter(s=>s.category===e.target.value).forEach(s=>selected.add(s.id));updateSelection();};container.querySelectorAll('[data-select]').forEach(c=>c.onchange=()=>{c.checked?selected.add(Number(c.dataset.select)):selected.delete(Number(c.dataset.select));updateSelection();});container.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{current=symbols.find(s=>s.id===Number(b.dataset.preview));preview();$('preview-title').scrollIntoView({block:'start'});});$('front').onclick=()=>{side='front';preview();};$('back').onclick=()=>{side='back';preview();};$('print-zoom-in').onclick=()=>{zoom=Math.min(2,zoom+.25);preview();};$('print-zoom-out').onclick=()=>{zoom=Math.max(.75,zoom-.25);preview();};$('crop-marks').onchange=e=>{marks=e.target.checked;preview();};
let busy=false;async function run(mode,list){if(busy)return;busy=true;container.querySelectorAll('button').forEach(b=>b.disabled=true);try{$('print-status').textContent='Готовим векторные файлы...';const out=await createDeck(list,{marks,includeIndividual:mode==='zip',onProgress:(n,t)=>$('print-status').textContent=`Подготовлено ${n} из ${t}`});if(mode==='zip')save(window.fflate.zipSync(out.files,{level:6}),'sacred-geometry-cards.zip','application/zip');else save(out.pdf,list.length===1?'symbol-'+list[0].id+'.pdf':'sacred-geometry-deck.pdf','application/pdf');$('print-status').textContent=`Готово: ${list.length} карточек. Размеры и безопасные поля проверены.`;}catch(e){$('print-status').textContent='Ошибка: '+e.message;}finally{busy=false;container.querySelectorAll('button').forEach(b=>b.disabled=false);updateSelection();}}
$('current-pdf').onclick=()=>run('pdf',[current]);$('current-svg').onclick=()=>save(new TextEncoder().encode(layoutSvg(cardLayout(current,side,measure,{marks}),fonts)),'symbol-'+current.id+'-'+side+'.svg','image/svg+xml');$('deck-pdf').onclick=()=>run('pdf',symbols.filter(s=>selected.has(s.id)));$('deck-zip').onclick=()=>run('zip',symbols.filter(s=>selected.has(s.id)));preview();}
