// Payload-free Web Push: private diary and notification text stay on the device.
const enc=new TextEncoder(),b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const json=(v,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
const hash=async s=>b64(await crypto.subtle.digest('SHA-256',enc.encode(s)));
export function validEndpoint(value){try{let u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].includes(u.hostname)&&value.length<2048}catch{return false}}
export function validTimes(times,now=Date.now()){return Array.isArray(times)&&times.length<=1500&&times.every(n=>Number.isSafeInteger(n)&&n>now-300000&&n<now+100*86400000)}
async function setup(db){await db.prepare('CREATE TABLE IF NOT EXISTS moon_push_keys (id INTEGER PRIMARY KEY, public_key TEXT NOT NULL, private_jwk TEXT NOT NULL)').run();await db.prepare('CREATE TABLE IF NOT EXISTS moon_push_subscriptions (token_hash TEXT PRIMARY KEY, endpoint TEXT NOT NULL UNIQUE, times TEXT NOT NULL, next_at INTEGER NOT NULL, updated INTEGER NOT NULL)').run();await db.prepare('CREATE INDEX IF NOT EXISTS moon_push_due ON moon_push_subscriptions(next_at)').run();await db.prepare('CREATE TABLE IF NOT EXISTS moon_push_rate (ip_hash TEXT PRIMARY KEY, window INTEGER NOT NULL, count INTEGER NOT NULL)').run()}
async function keys(db){let k=await db.prepare('SELECT * FROM moon_push_keys WHERE id=1').first();if(!k){let pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);await db.prepare('INSERT OR IGNORE INTO moon_push_keys(id,public_key,private_jwk) VALUES(1,?,?)').bind(b64(await crypto.subtle.exportKey('raw',pair.publicKey)),JSON.stringify(await crypto.subtle.exportKey('jwk',pair.privateKey))).run();k=await db.prepare('SELECT * FROM moon_push_keys WHERE id=1').first()}return k}
export async function authorization(endpoint,key,now=Date.now()){let header=b64(enc.encode(JSON.stringify({typ:'JWT',alg:'ES256'}))),claims=b64(enc.encode(JSON.stringify({aud:new URL(endpoint).origin,exp:Math.floor(now/1000)+12*3600,sub:'https://yuliastoyanova.com'}))),data=header+'.'+claims,privateKey=await crypto.subtle.importKey('jwk',JSON.parse(key.private_jwk),{name:'ECDSA',namedCurve:'P-256'},false,['sign']),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},privateKey,enc.encode(data));return `vapid t=${data}.${b64(sig)}, k=${key.public_key}`}
export async function handleMoonPush(request,env){let url=new URL(request.url),path=url.pathname,db=env.MAMA_DB;if(!db)return json({error:'Напоминания временно недоступны.'},503);await setup(db);
if(path==='/moon/api/push/key'&&request.method==='GET')return json({publicKey:(await keys(db)).public_key});
if(request.method!=='POST'||request.headers.get('origin')!==url.origin)return json({error:'Недопустимый запрос.'},403);
let ip=await hash(request.headers.get('cf-connecting-ip')||'unknown'),window=Math.floor(Date.now()/900000),limit=await db.prepare('INSERT INTO moon_push_rate(ip_hash,window,count) VALUES(?,?,1) ON CONFLICT(ip_hash) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END, window=excluded.window RETURNING count').bind(ip,window).first();if(limit.count>80)return json({error:'Попробуйте позже.'},429);
let raw=await request.text();if(raw.length>30000)return json({error:'Слишком большой запрос.'},413);let body;try{body=JSON.parse(raw)}catch{return json({error:'Неверный формат.'},400)}if(!/^[a-zA-Z0-9_-]{43}$/.test(body.token||''))return json({error:'Неверная подписка.'},400);let tokenHash=await hash(body.token);
if(path==='/moon/api/push/remove'){await db.prepare('DELETE FROM moon_push_subscriptions WHERE token_hash=?').bind(tokenHash).run();return json({ok:true})}
if(path==='/moon/api/push/subscribe'){if(!validEndpoint(body.endpoint)||!validTimes(body.times))return json({error:'Проверьте подписку и расписание.'},400);let times=[...new Set(body.times)].sort((a,b)=>a-b),existing=await db.prepare('SELECT token_hash FROM moon_push_subscriptions WHERE endpoint=?').bind(body.endpoint).first();if(existing&&existing.token_hash!==tokenHash)return json({error:'Подписка уже зарегистрирована. Отключите её и подключите заново.'},409);await db.prepare('INSERT INTO moon_push_subscriptions(token_hash,endpoint,times,next_at,updated) VALUES(?,?,?,?,?) ON CONFLICT(token_hash) DO UPDATE SET endpoint=excluded.endpoint,times=excluded.times,next_at=excluded.next_at,updated=excluded.updated').bind(tokenHash,body.endpoint,JSON.stringify(times),times[0]||0,Date.now()).run();return json({ok:true,count:times.length})}
return json({error:'Не найдено.'},404)}
export async function scheduledMoonPush(env){let db=env.MAMA_DB;if(!db)return;await setup(db);let now=Date.now(),rows=(await db.prepare('SELECT * FROM moon_push_subscriptions WHERE next_at>0 AND next_at<=? LIMIT 100').bind(now).all()).results;if(!rows.length)return;let key=await keys(db);await Promise.allSettled(rows.map(async row=>{let pending=JSON.parse(row.times),recent=pending.some(t=>t<=now&&t>now-6*3600000),remaining=pending.filter(t=>t>now);if(recent){let result=await fetch(row.endpoint,{method:'POST',redirect:'error',headers:{Authorization:await authorization(row.endpoint,key,now),TTL:'300',Urgency:'normal','Content-Length':'0'}});if([404,410].includes(result.status)){await db.prepare('DELETE FROM moon_push_subscriptions WHERE token_hash=?').bind(row.token_hash).run();return}if(!result.ok)return}await db.prepare('UPDATE moon_push_subscriptions SET times=?,next_at=? WHERE token_hash=? AND next_at=?').bind(JSON.stringify(remaining),remaining[0]||0,row.token_hash,row.next_at).run()}));await db.prepare('DELETE FROM moon_push_subscriptions WHERE updated<?').bind(now-100*86400000).run();await db.prepare('DELETE FROM moon_push_rate WHERE window<?').bind(Math.floor(now/900000)-1).run()}
