// Telegram identity is accepted only after server-side initData validation.
const enc=new TextEncoder();
const json=(v,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store'}});
async function mac(key,text){let k=await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(text)))}
export async function validateTelegram(raw,token,now=Date.now()){if(typeof raw!=='string'||raw.length>10000||!token)return null;let p=new URLSearchParams(raw),hash=p.get('hash'),auth=Number(p.get('auth_date'));if(!/^[a-f0-9]{64}$/.test(hash||'')||!Number.isSafeInteger(auth)||now/1000-auth>86400||auth>now/1000+60)return null;p.delete('hash');let check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n'),secret=await mac(enc.encode('WebAppData'),token),signed=await mac(secret,check),actual=Array.from(signed,b=>b.toString(16).padStart(2,'0')).join('');let diff=0;for(let i=0;i<64;i++)diff|=actual.charCodeAt(i)^hash.charCodeAt(i);if(diff)return null;try{let user=JSON.parse(p.get('user'));return Number.isSafeInteger(user.id)&&user.id>0?user:null}catch{return null}}
async function setup(db){await db.prepare('CREATE TABLE IF NOT EXISTS moon_telegram_users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, username TEXT, connected_at INTEGER NOT NULL, last_active INTEGER NOT NULL, disconnected_at INTEGER, subscribed INTEGER NOT NULL DEFAULT 0)').run();await db.prepare('CREATE TABLE IF NOT EXISTS moon_telegram_reminders (user_id INTEGER NOT NULL, at INTEGER NOT NULL, title TEXT NOT NULL, PRIMARY KEY(user_id,at,title))').run()}
export async function handleMoonTelegram(request,env){let db=env.MAMA_DB,url=new URL(request.url);if(!db||!env.MOON_BOT_TOKEN)return json({error:'Подключение Telegram еще настраивается.'},503);await setup(db);
if(url.pathname==='/moon/api/telegram/users'){if(!env.MOON_ADMIN_TOKEN||request.headers.get('authorization')!=='Bearer '+env.MOON_ADMIN_TOKEN)return json({error:'Нет доступа'},401);let result=await db.prepare('SELECT * FROM moon_telegram_users ORDER BY last_active DESC LIMIT 1000').all();return json({users:result.results,counts:await db.prepare('SELECT COUNT(*) connected,SUM(disconnected_at IS NOT NULL) disconnected,SUM(last_active>?) active FROM moon_telegram_users').bind(Date.now()-30*86400000).first()})}
if(url.pathname==='/moon/api/telegram/webhook'){if(!env.MOON_WEBHOOK_SECRET||request.headers.get('x-telegram-bot-api-secret-token')!==env.MOON_WEBHOOK_SECRET)return json({error:'Нет доступа'},401);let update=await request.json(),member=update.my_chat_member;if(member&&member.chat.type==='private'){let blocked=['kicked','left'].includes(member.new_chat_member.status);await db.prepare('UPDATE moon_telegram_users SET disconnected_at=?,subscribed=CASE WHEN ? THEN 0 ELSE subscribed END WHERE id=?').bind(blocked?Date.now():null,blocked?1:0,member.chat.id).run()}return json({ok:true})}
if(request.method!=='POST'||request.headers.get('origin')!==url.origin)return json({error:'Недопустимый запрос'},403);let raw=await request.text();if(raw.length>50000)return json({error:'Слишком большой запрос'},413);let body;try{body=JSON.parse(raw)}catch{return json({error:'Неверный запрос'},400)}let user=await validateTelegram(body.initData,env.MOON_BOT_TOKEN);if(!user)return json({error:'Откройте приложение из Telegram заново.'},401);let now=Date.now();await db.prepare('INSERT INTO moon_telegram_users(id,name,username,connected_at,last_active) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,username=excluded.username,last_active=excluded.last_active').bind(user.id,String(user.first_name||'').slice(0,100),String(user.username||'').slice(0,100),now,now).run();
if(url.pathname.endsWith('/visit'))return json({ok:true});
if(url.pathname.endsWith('/reminders')){let events=body.events;if(!Array.isArray(events)||events.length>1500||events.some(e=>!Number.isSafeInteger(e.at)||e.at<now||e.at>now+100*86400000||typeof e.title!=='string'||e.title.length>200))return json({error:'Проверьте расписание'},400);let chat=await fetch(`https://api.telegram.org/bot${env.MOON_BOT_TOKEN}/getChat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:user.id})}).then(r=>r.json());if(!chat.ok)return json({error:'Разрешите сообщения от бота.'},403);await db.batch([db.prepare('DELETE FROM moon_telegram_reminders WHERE user_id=?').bind(user.id),...events.map(e=>db.prepare('INSERT OR IGNORE INTO moon_telegram_reminders VALUES(?,?,?)').bind(user.id,e.at,e.title)),db.prepare('UPDATE moon_telegram_users SET subscribed=?,disconnected_at=NULL WHERE id=?').bind(events.length?1:0,user.id)]);return json({ok:true})}return json({error:'Не найдено'},404)}
export async function scheduledMoonTelegram(env){if(!env.MAMA_DB||!env.MOON_BOT_TOKEN)return;let db=env.MAMA_DB;await setup(db);let now=Date.now(),rows=(await db.prepare('SELECT r.* FROM moon_telegram_reminders r JOIN moon_telegram_users u ON u.id=r.user_id WHERE r.at<=? AND r.at>? AND u.subscribed=1 LIMIT 100').bind(now,now-6*3600000).all()).results;for(let r of rows){let response=await fetch(`https://api.telegram.org/bot${env.MOON_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:r.user_id,text:r.title+'\n\nhttps://yuliastoyanova.com/moon/'})}),result=await response.json();if(result.ok||result.error_code===403){await db.prepare('DELETE FROM moon_telegram_reminders WHERE user_id=? AND at=? AND title=?').bind(r.user_id,r.at,r.title).run();if(result.error_code===403)await db.prepare('UPDATE moon_telegram_users SET subscribed=0,disconnected_at=? WHERE id=?').bind(now,r.user_id).run()}}await db.prepare('DELETE FROM moon_telegram_reminders WHERE at<?').bind(now-6*3600000).run()}
