import './style.css';
import {days,intentionQuestions,finalQuestions,planQuestions,acceptanceQuestions,meditations} from './program.js';
import {STORAGE_KEY,BACKUP_KEY,emptyState,normalize,load,save,id,localDate,setWishStatus,addGoal,completeDay,diary,result,joys,eveningKey} from './state.js';
const base=import.meta.env.BASE_URL;
const configScript=document.createElement('script');configScript.src=base+'config.js';document.head.append(configScript);
let s=emptyState(),storageError='',readOnly=false;
try{s=load(localStorage)}catch(e){storageError=e.message;readOnly=true}
let page=location.hash.slice(1)||'home',wishFilter='active',editedWish=null,editedGoal=null,diaryFilter='Все',activeDay=s.currentDay||0;
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=url=>{try{const u=new URL(url,location.origin);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const cfg=()=>window.MARATHON_CONFIG||{};
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),3800)}
function persist(){if(readOnly)return false;try{save(localStorage,s);storageError='';const el=document.getElementById('save-state');if(el)el.textContent='Сохранено на устройстве';return true}catch{storageError='Не удалось сохранить на устройстве. Освободите место или скачайте записи, прежде чем закрыть приложение.';toast(storageError);const el=document.getElementById('save-state');if(el)el.textContent='Нужна резервная копия';return false}}
function go(route){location.hash=route;page=route;render();window.scrollTo({top:0,behavior:'instant'})}
function button(label,action,extra='',type='primary'){return `<button class="${type}" data-action="${action}" ${extra}>${label}</button>`}
function link(label,route,type='text-link'){return `<a class="${type}" href="#${route}">${label}</a>`}
function field(label,bind,value='',hint='',rows=3){return `<label class="field"><span>${esc(label)}</span>${hint?`<small>${esc(hint)}</small>`:''}<textarea data-bind="${esc(bind)}" rows="${rows}" maxlength="20000" placeholder="Дайте себе время услышать ответ" >${esc(value)}</textarea></label>`}
function groupQuestions(title,key,questions){const answers=s.answers[key]||{};return `<section class="practice-section"><h2>${title}</h2>${questions.map((q,i)=>field(q,`answers|${key}|${i}`,answers[i]||'')).join('')}${button('Сохранить','save')}</section>`}
function heading(eyebrow,title,text=''){return `<header class="page-heading"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${text?`<p class="lead">${text}</p>`:''}</header>`}
function consultation(final=false){const url=safeUrl(cfg().consultationUrl);return `<aside class="consultation ${final?'consultation-final':''}"><span class="gold-symbol" aria-hidden="true">✧</span><div><h${final?'2':'3'}>${final?'Хотите продолжить этот путь глубже?':'Хотите разобрать свою ситуацию глубже?'}</h${final?'2':'3'}><p>${final?'Некоторые части себя сложно увидеть самостоятельно. В индивидуальной работе мы можем исследовать ваши желания, повторяющиеся ограничения, внутренние противоречия и опыт, который сейчас мешает двигаться дальше.':'На индивидуальной консультации мы можем исследовать именно вашу ситуацию, желания, внутренние ограничения и направление дальнейшего движения.'}</p></div>${url?`<a class="primary" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Записаться на консультацию ↗</a>`:button('Записаться на консультацию','missing-consultation')}${!url?'<p class="availability">Запись откроется после добавления ссылки автором</p>':''}</aside>`}
function bot(){return `<aside class="bot-block"><p class="eyebrow">БОЛЬШЕ ЯСНОСТИ</p><h2>Сложно сформулировать намерение?</h2><p>Помощник поможет превратить вашу мысль в более ясную формулировку</p><a class="primary" href="${esc(safeUrl(cfg().intentionBotUrl))}" data-telegram-link>Сформулировать намерение ↗</a></aside>`}
function video(day){const videoId=new URL(day.videoUrl).searchParams.get('v');return `<div class="video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/${videoId}?rel=0&playsinline=1" title="Видео: ${esc(day.title)}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div><a class="text-link" href="${esc(day.videoUrl)}" target="_blank" rel="noopener noreferrer">Открыть урок на YouTube ↗</a>`}
function meditation(m){return `<section class="meditation"><p class="eyebrow">БОНУС • В СВОЕМ РИТМЕ</p><h3>${m.label||m.title}</h3>${m.label?`<p>Медитация «${m.title}»</p>`:''}${m.audio?`<audio controls preload="none" src="${esc(safeUrl(m.audio))}"></audio>`:m.video?`<details><summary>Включить медитацию <span>＋</span></summary><div class="video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/${m.video}?rel=0&playsinline=1" title="${esc(m.title)}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div></details>`:'<p class="availability">Аудиозапись пока не добавлена автором. Здесь будет медитация «Создание намерения»</p>'}${m.id==='gratitude'?field('Что изменилось в моем состоянии?','answers|meditation-gratitude|0',s.answers['meditation-gratitude']?.[0]):''}</section>`}
function home(){return `<section class="hero"><img class="hero-image" src="${base}images/coast.webp" alt="Свет над морем и простор нового пути"><div class="hero-copy"><p class="eyebrow">АВТОРСКИЙ МАРАФОН ЮЛИИ СТОЯНОВОЙ</p><h1>Путь<br><em>к себе</em></h1><h2>Все начинается<br>с внутреннего «Я хочу»</h2><p>Услышать свои желания.<br>Увидеть собственное направление.<br>Постепенно выбрать жизнь, которая ощущается своей.</p>${link('Начать мой путь ↗','day/0','primary')}${link('Как проходит марафон ↓','how','hero-secondary')}</div></section><section class="landing-section"><p class="eyebrow">ИЗ ЧЕГО СОСТОИТ ПУТЬ</p><h2>От первого «хочу»<br><em>к большему пониманию себя</em></h2>${pathList()}<p class="lead">Вводный урок и 5 дней. Возвращайтесь в собственном ритме</p>${link('Как проходит марафон →','how','secondary')}</section>`}
function how(){const items=[['Смотрите уроки','Каждый этап помогает открыть следующую часть работы с собой'],['Выполняйте практики','Переносите полученные знания в свою жизнь'],['Записывайте желания и открытия','Все можно записывать непосредственно внутри приложения'],['Возвращайтесь в своем ритме','Ваши записи и результаты сохраняются на этом устройстве'],['Наблюдайте изменения','В конце пути вы сможете сравнить первоначальное намерение с тем, что изменилось']];return heading('ВНИМАНИЕ К СЕБЕ','Как проходит марафон')+`<div class="method-list">${items.map(([h,p],i)=>`<section><span class="step-number">0${i+1}</span><div><h2>${h}</h2><p>${p}</p></div></section>`).join('')}</div><section class="practice-section"><h2>Выделяйте время для себя</h2><p>Возвращайтесь к себе утром, в течение дня и вечером. Ориентир автора составляет около 20 минут. Проходите практики в собственном ритме.</p><p>Ориентир практики желаний: 100+. Количество желаний, задач, целей и заполненных ответов никогда не ограничивает переход.</p>${link('Перейти к вводному уроку →','day/0','primary')}</section>`}
function pathList(){return `<div class="path-list">${days.map(d=>`<a href="#day/${d.day}"><span class="step-number">${d.day===0?'✧':'0'+d.day}</span><div><p class="eyebrow">${d.day===0?'ВВОДНЫЙ УРОК':'ДЕНЬ '+d.day}${s.completed.includes(d.day)?' • ЗАВЕРШЕН':''}</p><h3>${d.title}</h3><p>${d.subtitle}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div>`}
function path(){return heading('ВАША НЕПРЕРЫВНАЯ ИСТОРИЯ','Мой путь','Желания, радости, цели и открытия накапливаются вместе с вашим опытом. Все уроки доступны')+pathList()+`<div class="actions">${link('Вернуться к моим желаниям','wishes','secondary')}${link('Мои жизненные цели','goals','secondary')}${link('Завершение марафона →','final','primary')}</div>`}
function chips(value,bind){return `<fieldset class="category-chips"><legend>Категория по желанию</legend>${[['','Без категории'],['Хочу иметь','ИМЕТЬ'],['Хочу уметь','УМЕТЬ'],['Хочу знать','ЗНАТЬ']].map(([v,label])=>`<label class="${value===v?'selected':''}"><input type="radio" name="${esc(bind)}" data-bind="${esc(bind)}" value="${v}" ${value===v?'checked':''}>${label}</label>`).join('')}</fieldset>`}
function wishComposer(){return `<div class="wish-guidance"><span class="big-count">${s.wishes.length}<small> / 100+</small></span><div><h3>Ориентир практики: 100 желаний</h3><p>Если после первых 10, 20 или 30 желаний кажется, что больше ничего нет, дайте себе немного тишины. Часто после паузы появляется следующий слой желаний.</p><p>Запишите столько, сколько приходит сейчас. Следующий день доступен при любом количестве.</p></div></div><form data-form="wish" class="composer">${field('Я хочу...','draft|wish',drafts.wish||'','Большое или совсем маленькое желание',2)}${chips(drafts.category||'','draft|category')}${button('＋ Добавить желание','submit-wish','type="submit"')}</form>`}
function wishList(select=false){let list=s.wishes.filter(w=>select?w.status==='active':w.status===wishFilter);return `${!select?`<div class="tabs" aria-label="Список желаний">${[['active','Я хочу'],['fulfilled','Уже сбылось'],['archived','Больше не хочу']].map(([k,label])=>button(`${label} · ${s.wishes.filter(w=>w.status===k).length}`,'wish-filter',`data-filter="${k}" aria-pressed="${wishFilter===k}"`,'tab '+(wishFilter===k?'selected':''))).join('')}</div>`:''}${!list.length?'<p class="empty">Здесь есть место для ваших желаний. Начните с того, что откликается сейчас</p>':''}<div class="wish-list">${list.map(w=>`<article class="wish-row"><div><p>${esc(w.text)}</p><small>${esc(w.category||'Без категории')}</small></div>${select?button('Сделать жизненной целью','goal-from-wish',`data-id="${esc(w.id)}"`,'secondary'):button(editedWish===w.id?'Закрыть':'Открыть желание','edit-wish',`data-id="${esc(w.id)}"`,'text-link')}${!select&&editedWish===w.id?`<div class="editor">${field('Мое желание',`wish|${w.id}|text`,w.text)}${chips(w.category,`wish|${w.id}|category`)}${button(w.status==='fulfilled'?'Вернуть желание в список':'Отметить как исполненное',w.status==='fulfilled'?'wish-active':'wish-fulfilled',`data-id="${esc(w.id)}"`,'secondary')}${button(w.status==='archived'?'Я снова этого хочу':'Больше не актуально',w.status==='archived'?'wish-active':'wish-archived',`data-id="${esc(w.id)}"`,'text-link')}${button('Сохранить','save')}</div>`:''}</article>`).join('')}</div>`}
function wishes(){return heading('РАЗРЕШИТЕ СЕБЕ ХОТЕТЬ','Мои желания','Ваш единый список сохраняется и остается доступным на протяжении всего марафона')+wishComposer()+wishList()+`<div class="actions">${link('Продолжить →',`day/${Math.min(5,Math.max(2,activeDay))}`,'primary')}${link('Вернуться в мой путь','path','secondary')}</div>`}
function plan(day){const date=localDate();return `<section class="practice-section" id="plan"><h2>Создайте план своего дня</h2><p>Выполняйте свой план в течение дня и наблюдайте за своим состоянием</p>${planQuestions.map((q,kind)=>`<div class="plan-column"><h3>${q}</h3><p>${['Дела, обязательства и задачи, которые важны сегодня','То, что не обязательно, но мне хочется сделать','Что сегодня может действительно порадовать или наполнить меня?'][kind]}</p><form data-form="task" data-day="${day}" data-kind="${kind}"><label class="field"><span class="sr-only">${q}</span><textarea name="text" rows="2" maxlength="20000" placeholder="Запишите действие"></textarea></label><button class="secondary" type="submit">＋ Добавить</button></form>${s.tasks.filter(t=>t.date===date&&t.kind===kind).map(t=>`<article class="task-row"><label class="task-check"><input type="checkbox" data-bind="task|${t.id}|done" ${t.done?'checked':''}><span>${esc(t.text)}<small>${t.done?'✓ Выполнено':'Отметить выполненным'}</small></span></label>${t.done?`<div class="task-feeling"><h4>${kind===2?'А что вы почувствовали на самом деле?':'Что вы чувствуете сейчас?'}</h4>${field('Что я чувствую?',`task|${t.id}|feeling`,t.feeling,'Ответ автоматически сохраняется в дневник',3)}<label class="check-label"><input type="checkbox" data-bind="task|${t.id}|joy" ${t.joy?'checked':''}>Это действительно принесло мне радость</label>${kind===2?`<fieldset class="joy-rating"><legend>Насколько это действительно принесло мне радость?</legend>${[1,2,3,4,5].map(n=>`<label><input type="radio" name="rating-${t.id}" value="${n}" data-bind="task|${t.id}|rating" ${t.rating==n?'checked':''}>${n}</label>`).join('')}<small>По желанию</small></fieldset>`:''}</div>`:''}</article>`).join('')}</div>`).join('')}${button('Сохранить план','save')}${link('Продолжить список желаний →','wishes','text-link')}</section>`}
function resources(){return `<section class="practice-section"><h2>Что хорошего уже есть в моей жизни?</h2>${['Что у меня уже есть?','Что я уже умею?','Что я уже знаю?'].map((q,kind)=>`<section class="resource-group"><h3>${q}</h3><p>${['Вещи, возможности, отношения и условия жизни','Навыки, способности и опыт','Знания, понимание и то, чему вы научились'][kind]}</p><form data-form="resource" data-kind="${kind}"><label class="field"><span class="sr-only">${q}</span><textarea name="text" maxlength="20000" rows="2" placeholder="Добавьте свой ресурс"></textarea></label><button class="secondary" type="submit">＋ Добавить</button></form><ul>${s.resources.filter(r=>r.kind===kind).map(r=>`<li>${esc(r.text)}</li>`).join('')}</ul></section>`).join('')}<h3>Посмотрите, сколько уже создано вами</h3>${field('За что сегодня я благодарен(на) себе?','answers|gratitude-self|0',s.answers['gratitude-self']?.[0])}${field('За что я благодарен(на) жизни, миру или людям?','answers|gratitude-world|0',s.answers['gratitude-world']?.[0])}${button('Сохранить благодарность','save')}</section>`}
function goalEditor(g){return `<div class="editor"><h3>Моя цель</h3>${[['title','Чего я хочу?'],['importance','Почему это важно для меня?'],['why','Что в этом приносит мне радость?'],['lifeChange','Какой я представляю свою жизнь, когда это станет ее частью?'],['step','Какой небольшой шаг я могу сделать в этом направлении?']].map(([key,q])=>field(q,`goal|${g.id}|${key}`,g[key])).join('')}<label class="field"><span>Когда я хочу вернуться к этой цели?</span><small>Дата или ориентир по желанию</small><input type="date" data-bind="goal|${g.id}|returnDate" value="${esc(g.returnDate)}"></label>${bot()}<div class="actions">${button('Сохранить цель','save-goal',`data-id="${g.id}"`)}${button('Перейти дальше →','close-goal','', 'secondary')}</div></div>`}
function goalList(){return `<div class="goal-list">${s.goals.map(g=>`<article class="goal-row" id="goal-${g.id}"><p class="eyebrow">МОЯ ЖИЗНЕННАЯ ЦЕЛЬ</p><h3>${esc(g.title||'Моя новая цель')}</h3>${editedGoal===g.id?goalEditor(g):`${g.why?`<p>${esc(g.why)}</p>`:''}${field('Мой следующий шаг',`goal|${g.id}|step`,g.step,'Небольшое действие в выбранном направлении',2)}${button('Открыть цель','edit-goal',`data-id="${g.id}"`,'text-link')}`}</article>`).join('')}${!s.goals.length?'<p class="empty">Здесь появятся ваши реальные цели. Выберите желание или добавьте новую цель</p>':''}</div>`}
function goals(day=false){return `${!day?heading('ДВИЖЕНИЕ ЧЕРЕЗ ЖЕЛАНИЕ И РАДОСТЬ','Мои жизненные цели'): '<h2>От желания к жизненной цели</h2>'}<section class="practice-section"><details ${day?'open':''}><summary>Выбрать желание из моего списка <span>＋</span></summary>${wishList(true)}</details>${button('＋ Добавить новую большую цель','new-goal','', 'primary')}</section><h2>Мои жизненные цели</h2>${goalList()}<div class="actions">${button('＋ Добавить еще одну цель','new-goal','', 'secondary')}${day?'<a href="#evening/4" class="primary">Перейти дальше →</a>':link('Вернуться в мой путь →','path','primary')}</div>`}
function evening(day){const date=localDate(),key=eveningKey(day,date),r=s.evenings[key]||{answers:{},closed:false};return `<section class="practice-section evening" id="evening"><p class="eyebrow">НЕСКОЛЬКО МИНУТ ДЛЯ СЕБЯ</p><h2>Завершение дня</h2><p>${day===2?'Посмотрите на свой день':'Заметьте важное и сохраните то, что хочется взять с собой'}</p>${days[day].evening.map((q,i)=>field(q,`evening|${key}|${i}`,r.answers?.[i]||'')).join('')}<div class="actions">${button('Сохранить','save')}${button('Завершить '+(day?'День '+day:'вводный урок'),'complete',`data-day="${day}"`)}</div>${s.completed.includes(day)?completion(day):''}</section>`}
function completion(day){return `<div class="completion" role="status"><span aria-hidden="true">✧</span><h2>${day?'День завершен':'Намерение сохранено'}</h2><p>${day===5?'Ваш путь продолжается. Теперь можно посмотреть, что изменилось':'Этот шаг стал частью вашей истории'}</p>${link(day===5?'Перейти к завершению марафона →':`Перейти к ${day===0?'Дню 1':'следующему дню'} →`,day===5?'final':`day/${day+1}`,'primary')}</div>`}
function lesson(day){const d=days[day];activeDay=day;if(s.currentDay!==day){s.currentDay=day;persist();if(s.reminder.enabled)void syncReminderDay(day)}if(!s.unlockedBonuses.includes(day)){s.unlockedBonuses.push(day);persist()}
let practice='';
if(day===0)practice=`<section class="practice-section"><h2>За эти 5 дней вы</h2><ul class="meaning-list">${['Выгрузите свои желания','Начнете различать, чего хотите именно вы','Увидите, что действительно приносит вам радость','Начнете формировать жизненные цели из собственных желаний','Будете наблюдать свое состояние и внутренние ограничения','Придете к более глубокому пониманию и принятию себя'].map(t=>`<li>${t}</li>`).join('')}</ul></section><section class="practice-section"><h2>С каким намерением вы начинаете этот путь?</h2><p>${d.instruction}</p>${intentionQuestions.map((q,i)=>field(q,`intention|${i}`,s.intention[i],i===4?'По желанию':'')).join('')}${button('Сохранить мое намерение','save-intention')}<p>В конце марафона мы вернемся к этим ответам. Вы сможете увидеть, что изменилось и что вы открыли в себе за это время.</p>${meditation(meditations[0])}${s.completed.includes(0)?completion(0):link('Перейти к Дню 1 →','day/1','primary')}</section>`;
if(day===1)practice=`<section class="practice-section"><h2>${d.practice}</h2><p>${d.instruction}</p>${wishComposer()}${wishList()}${button('Сохранить список','save')}</section>${meditation(meditations[1])}${evening(1)}`;
if(day===2)practice=plan(2)+meditation(meditations[1])+evening(2);
if(day===3)practice=`<section class="practice-section"><h2>Настройка на день</h2><p>Выделите время для себя, замечайте радость и продолжайте ежедневный ритм</p></section>`+plan(3)+resources()+meditation(meditations[2])+evening(3);
if(day===4)practice=`<section class="practice-section"><h2>${d.practice}</h2><p>${d.instruction}</p></section>`+goals(true)+evening(4);
if(day===5)practice=meditation(meditations[1])+plan(5)+`<section class="practice-section"><h2>Посмотрите на свои жизненные цели</h2><p>Какой маленький шаг я могу сделать в сторону одной из них?</p>${goalList()}${link('Мои жизненные цели →','goals','secondary')}</section>`+groupQuestions('Внимательнее увидеть себя','acceptance',acceptanceQuestions)+evening(5);
return link('← Вернуться в мой путь','path')+heading(day===0?'ВВОДНЫЙ УРОК':`ДЕНЬ ${day}`,d.title,d.subtitle)+`<figure class="lesson-photo"><img src="${base}images/${d.image}.webp" alt="${esc(d.subtitle)}"></figure><div class="intro">${d.intro.map(p=>`<p>${p}</p>`).join('')}</div>`+video(d)+consultation(day===5)+`<section class="practice-section meanings"><p class="eyebrow">ОПОРЫ СЕГОДНЯШНЕГО ЭТАПА</p><h2>Главное из урока</h2><ul class="meaning-list">${d.main.map(m=>`<li>${m}</li>`).join('')}</ul></section>${practice}`;
}
function final(){return `<section class="final-hero"><span class="gold-symbol" aria-hidden="true">✧</span><p class="eyebrow">ЗАВЕРШЕНИЕ МАРАФОНА</p><h1>Ваш путь<br><em>продолжается</em></h1><p>За эти дни вы не должны были найти все ответы. Вы начали задавать себе вопросы, замечать желания, искать радость, направлять внимание на важное и видеть то, что уже создано.</p><p>Вы формировали собственные жизненные ориентиры и узнавали себя немного глубже.</p></section><section class="practice-section"><h2>В начале пути вы написали</h2>${intentionQuestions.map((q,i)=>`<article class="intention-result"><h3>${q}</h3><p>${esc(s.intention[i]||'Этот вопрос остался открытым')}</p></article>`).join('')}</section><section class="practice-section"><h2>А что изменилось сейчас?</h2>${finalQuestions.map((q,i)=>field(q,`final|${i}`,s.final[i])).join('')}${button('Сохранить мой результат','finish')}</section>${summary()}${consultation(true)}${supernova()}<div class="actions">${link('Вернуться в мой путь','path','secondary')}${button('Скачать мой результат','export-result','', 'primary')}</div>`}
function supernova(){const url=safeUrl(cfg().supernovaUrl);return `<aside class="supernova"><p class="eyebrow">ПРОДОЛЖЕНИЕ ИНДИВИДУАЛЬНОГО ПУТИ</p><h2>Рождение сверхновой</h2><p>Индивидуальная работа и сопровождение для более глубокого исследования и принятия себя</p>${url?`<a class="secondary" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Узнать подробнее ↗</a>`:button('Узнать подробнее','missing-supernova','', 'secondary')}${!url?'<p class="availability">Ссылка на программу пока не добавлена автором</p>':''}</aside>`}
function summary(){const r=result(s),e=diary(s);const groups=[['Мои главные желания',s.wishes.filter(w=>w.status==='active').map(w=>w.text)],['Мои радости',joys(s).map(j=>j.text)],['Мои жизненные цели',s.goals.map(g=>g.title)],['Мои открытия',e.filter(e=>['Открытие','Итог марафона'].includes(e.kind)).map(e=>e.text)],['Мой следующий шаг',s.goals.map(g=>g.step).filter(Boolean)]];return `<section class="practice-section result"><h2>Мой результат</h2><div class="result-counts">${[['Желаний записано',r.wishes],['Желаний уже исполнилось',r.fulfilled],['Жизненных целей',r.goals],['Радостей найдено',r.joys],['Записей благодарности',r.gratitude]].map(([t,n])=>`<div><strong>${n}</strong><span>${t}</span></div>`).join('')}</div>${groups.map(([h,items])=>`<section class="result-group"><h3>${h}</h3>${items.length?`<ul>${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:'<p>Здесь есть место для ваших будущих открытий</p>'}</section>`).join('')}</section>`}
function diaryPage(){const e=diary(s).filter(e=>diaryFilter==='Все'||e.kind===diaryFilter);return heading('ВАШИ ОТВЕТЫ И СОСТОЯНИЯ','Мой дневник','Здесь собираются намерение, состояния после действий, благодарность и открытия')+`<div class="tabs">${['Все','Состояние','Благодарность','Открытие','Итог дня'].map(k=>button(k,'diary-filter',`data-filter="${k}"`,'tab '+(diaryFilter===k?'selected':''))).join('')}</div><div class="diary-list">${e.map(e=>`<article><p class="eyebrow">${esc(e.kind)} ${esc(e.date)}</p><p>${esc(e.text)}</p></article>`).join('')||'<p class="empty">Ваши ответы из практик появятся здесь автоматически</p>'}</div>${link('Вернуться в мой путь →','path','primary')}`}
function bonuses(){return heading('ПРАКТИКИ В ВАШЕМ РИТМЕ','Бонусные медитации','Открытые записи остаются доступными в последующие дни')+meditations.filter(m=>s.unlockedBonuses.includes(m.day)||s.completed.some(d=>d>=m.day)).map(meditation).join('')+link('Вернуться в мой путь →','path','primary')}
function settings(){const canRemind=!!(cfg().reminderApiUrl&&cfg().marathonBotUsername);return heading('ЗАПИСИ И ВРЕМЯ ДЛЯ СЕБЯ','Мое пространство')+`<div class="personal-links">${link('Мои жизненные цели →','goals')}${link('Мои желания →','wishes')}${link('Медитации →','bonus')}${link('Мой результат →','final')}</div><section class="practice-section"><h2>Вечернее напоминание</h2><p>Время завершить сегодняшний день и несколько минут посвятить себе</p><label class="field"><span>Время напоминания</span><input type="time" data-bind="reminder|time" value="${esc(s.reminder.time)}"></label><p>Часовой пояс: ${esc(s.reminder.timezone)}</p><label class="check-label"><input type="checkbox" data-bind="reminder|consent" ${s.reminder.enabled?'checked':''} ${canRemind?'':'disabled'}>Я согласен(на) получать вечернее напоминание в Telegram</label>${canRemind?button('Сохранить настройки напоминания','save-reminder'):'<p class="availability">Отправка напоминаний пока не подключена. Для нее автору нужно настроить бот марафона. Согласие не включается автоматически</p>'}<p>Кнопка в сообщении будет открывать вечернюю практику соответствующего дня</p>${link('Открыть вечернюю практику →',`evening/${Math.max(1,activeDay)}`,'secondary')}</section><section class="practice-section"><h2>Ваши записи</h2><p>Ответы сохраняются автоматически в этом браузере или Telegram WebView на этом устройстве. После обычного закрытия и повторного открытия они остаются. Между разными устройствами и браузерами автоматическая синхронизация пока не подключена.</p><p>Для резервной копии скачайте записи. Их можно восстановить из файла в другом браузере.</p><div class="actions">${button('Скачать все записи','export','', 'primary')}<label class="secondary import">Восстановить из файла<input id="import-data" type="file" accept="application/json,.json"></label></div><p class="availability">Импорт объединяет записи и сохраняет резервную копию текущего состояния</p></section>${link('Вернуться в мой путь →','path','primary')}`}
function render(){const parsed=page.match(/^(day|evening)\/([0-5])$/);let content;try{content=parsed?parsed[1]==='evening'?(activeDay=+parsed[2],heading('ВЕЧЕРНЯЯ ПРАКТИКА',days[activeDay].title)+evening(activeDay)):lesson(+parsed[2]):({home,how,path,wishes,goals,diary:diaryPage,bonus:bonuses,settings,final}[page]||path)()}catch{content=heading('ВАШ ПУТЬ','Продолжите свой путь')+link('Вернуться в мой путь','path','primary')}
app.innerHTML=`<header class="brandbar"><a class="brand" href="#home"><span aria-hidden="true">✧</span>Юлия Стоянова</a><span id="save-state" role="status">${storageError?'Нужна резервная копия':'Сохранено на устройстве'}</span></header>${storageError?`<div class="storage-error" role="alert">${esc(storageError)} ${button('Скачать резервную копию','export-raw','', 'secondary')}</div>`:''}<main id="main" class="${page==='home'?'landing':'workspace'}" tabindex="-1">${content}<footer><span>ЮЛИЯ СТОЯНОВА</span><p>С вниманием к вашему внутреннему миру</p><a href="/">На сайт автора ↗</a></footer></main><nav class="bottom-nav" aria-label="Основная навигация">${[['home','Домой','☼'],['path','Путь','✧'],['wishes','Хочу','♡'],['diary','Записи','▤'],['settings','Я','◌']].map(([route,label,icon])=>`<a href="#${route}" ${page===route?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}</a>`).join('')}</nav>`;document.title=(parsed?days[+parsed[2]].title:'Путь к себе')+' | Юлия Стоянова';}
const drafts={};
function bind(target){const [type,key,prop]=target.dataset.bind.split('|');const val=target.type==='checkbox'?target.checked:target.value;
if(type==='draft'){drafts[key]=val;if(target.type==='radio')target.closest('fieldset').querySelectorAll('label').forEach(l=>l.classList.toggle('selected',l.contains(target)));return}
if(readOnly){toast('Сначала восстановите записи из резервной копии');return}
if(type==='intention'||type==='final')s[type][+key]=val;
if(type==='answers'){s.answers[key]??={};s.answers[key][prop]=val}
if(type==='wish'||type==='goal'||type==='task'){const record=s[type==='wish'?'wishes':type==='goal'?'goals':'tasks'].find(x=>x.id===key);if(record)record[prop]=val}
if(type==='evening'){s.evenings[key]??={day:activeDay,date:localDate(),answers:{},closed:false};s.evenings[key].answers[prop]=val}
if(type==='reminder'){if(key==='consent'){drafts.consent=val;return}s.reminder[key]=val}
persist();if(target.type==='radio'){target.closest('fieldset').querySelectorAll('label').forEach(l=>l.classList.toggle('selected',l.contains(target)))}
if(type==='task'&&prop==='done')render();}
app.addEventListener('input',e=>{if(e.target.dataset.bind&&e.target.type!=='checkbox'&&e.target.type!=='radio')bind(e.target)});
app.addEventListener('change',e=>{if(e.target.dataset.bind&&(e.target.type==='checkbox'||e.target.type==='radio'||e.target.type==='date'||e.target.type==='time'))bind(e.target);if(e.target.id==='import-data')void importFile(e.target.files[0])});
app.addEventListener('submit',e=>{const form=e.target;if(!form.dataset.form)return;e.preventDefault();if(readOnly)return;const type=form.dataset.form;
if(type==='wish'){const text=(drafts.wish||'').trim();if(!text)return;s.wishes.push({id:id(),text,category:drafts.category||'',status:'active',completedAt:null});drafts.wish='';drafts.category='';persist();render();app.querySelector('[data-bind="draft|wish"]')?.focus({preventScroll:true});toast('Желание добавлено')}
if(type==='task'||type==='resource'){const text=form.elements.text.value.trim();if(!text)return;if(type==='task')s.tasks.push({id:id(),text,kind:+form.dataset.kind,day:+form.dataset.day,date:localDate(),done:false,feeling:'',joy:false,rating:null});else s.resources.push({id:id(),text,kind:+form.dataset.kind,date:localDate()});persist();const y=scrollY;render();window.scrollTo(0,y);toast(type==='task'?'Действие добавлено':'Ресурс сохранен')}
});
app.addEventListener('click',async e=>{const t=e.target.closest('[data-action]');if(!t)return;const action=t.dataset.action,wid=t.dataset.id;
if(action==='save'){if(persist())toast('Ваши ответы сохранены');return}
if(action==='submit-wish')return;
if(action.startsWith('missing-')){toast(action==='missing-consultation'?'Автор еще не добавил ссылку записи на консультацию':'Автор еще не добавил ссылку на программу');return}
if(action==='wish-filter'){wishFilter=t.dataset.filter;render();return}
if(action==='diary-filter'){diaryFilter=t.dataset.filter;render();return}
if(action==='edit-wish'){editedWish=editedWish===wid?null:wid;render();return}
if(['wish-active','wish-fulfilled','wish-archived'].includes(action)){setWishStatus(s,wid,action.split('-')[1]==='active'?'active':action.split('-')[1]==='fulfilled'?'fulfilled':'archived');persist();render();return}
if(action==='goal-from-wish'||action==='new-goal'){const g=addGoal(s,action==='goal-from-wish'?wid:null);editedGoal=g.id;persist();if(page==='goals'||page==='day/4'){render();document.getElementById('goal-'+g.id)?.scrollIntoView({behavior:'smooth',block:'start'})}else go('goals');return}
if(action==='edit-goal'){editedGoal=wid;render();return}
if(action==='save-goal'||action==='close-goal'){if(!persist())return;editedGoal=null;render();toast('Цель сохранена');return}
if(action==='save-intention'){if(persist()){if(!s.completed.includes(0))s.completed.push(0);persist();render();toast('Мы вернемся к этим ответам в конце марафона')}return}
if(action==='complete'){const day=+t.dataset.day,key=eveningKey(day,localDate());s.evenings[key]??={day,date:localDate(),answers:{}};s.evenings[key].closed=true;completeDay(s,day);if(persist()){render();document.querySelector('.completion')?.scrollIntoView({behavior:'smooth',block:'center'});window.Telegram?.WebApp?.HapticFeedback?.notificationOccurred('success')}return}
if(action==='finish'){s.finished=true;if(persist()){toast('Ваш результат сохранен');document.querySelector('.result')?.scrollIntoView({behavior:'smooth'})}return}
if(action==='export'||action==='export-raw'){download('Мой-путь-к-себе.json',action==='export-raw'?(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(BACKUP_KEY)||JSON.stringify(s)):JSON.stringify(s,null,2),'application/json');return}
if(action==='export-result'){download('Мой-результат.txt',['Путь к себе','Мое намерение',...s.intention,'Мои желания',...s.wishes.map(w=>w.text),'Мои цели',...s.goals.map(g=>g.title+'\nСледующий шаг: '+g.step),'Мои открытия',...diary(s).map(e=>e.kind+': '+e.text)].join('\n\n'),'text/plain;charset=utf-8');return}
if(action==='save-reminder')await saveReminder();
});
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function importFile(file){if(!file)return;try{if(file.size>10000000)throw Error('Файл слишком большой');const incoming=normalize(JSON.parse(await file.text()));const merged={...s,...incoming};for(const key of ['wishes','goals','tasks','resources','notes','joys'])merged[key]=[...new Map([...s[key],...incoming[key]].map(v=>[v.id,v])).values()];for(const key of ['answers','evenings','gratitude'])merged[key]={...s[key],...incoming[key]};for(const key of ['completed','unlockedBonuses'])merged[key]=[...new Set([...s[key],...incoming[key]])];merged.intention=incoming.intention.map((v,i)=>v||s.intention[i]);merged.final=incoming.final.map((v,i)=>v||s.final[i]);save(localStorage,merged);s=merged;readOnly=false;storageError='';render();toast('Записи восстановлены')}catch(e){toast('Не удалось восстановить файл: '+e.message)}}
async function syncReminderDay(day){const tg=window.Telegram?.WebApp;if(day<3||!tg?.initData||!cfg().reminderApiUrl)return;try{await fetch(cfg().reminderApiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData,enabled:true,time:s.reminder.time,timezone:s.reminder.timezone,day})})}catch{}}
async function saveReminder(){const tg=window.Telegram?.WebApp;if(!tg?.initData){toast('Откройте марафон внутри Telegram, чтобы настроить напоминание');return}const enabled=drafts.consent??s.reminder.enabled;if(enabled&&tg.requestWriteAccess){const allowed=await new Promise(resolve=>tg.requestWriteAccess(resolve));if(!allowed){toast('Разрешение на сообщения не получено. Напоминание не включено');return}}try{const r=await fetch(cfg().reminderApiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData,enabled:!!enabled,time:s.reminder.time,timezone:s.reminder.timezone,day:Math.max(3,activeDay)})});if(!r.ok)throw Error();s.reminder.enabled=!!enabled;persist();toast(s.reminder.enabled?'Вечернее напоминание включено':'Вечернее напоминание выключено')}catch{toast('Не удалось сохранить настройки. Напоминание не включено')}}
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1)||'home';if(next!==page){page=next;render();window.scrollTo({top:0,behavior:'instant'})}});
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&e.newValue){try{s=normalize(JSON.parse(e.newValue));render();toast('Записи обновлены из другой вкладки')}catch{}}});
configScript.onload=render;
function initTelegram(){const tg=window.Telegram?.WebApp;if(!tg)return;tg.ready();tg.expand();tg.setHeaderColor?.('#151217');tg.setBackgroundColor?.('#f9f5ed');const safe=()=>{document.documentElement.style.setProperty('--tg-top',((tg.safeAreaInset?.top||0)+(tg.contentSafeAreaInset?.top||0))+'px');document.documentElement.style.setProperty('--tg-bottom',((tg.safeAreaInset?.bottom||0)+(tg.contentSafeAreaInset?.bottom||0))+'px')};safe();tg.onEvent?.('safeAreaChanged',safe);tg.onEvent?.('contentSafeAreaChanged',safe);tg.onEvent?.('viewportChanged',safe);tg.BackButton?.onClick(()=>go('path'));const p=tg.initDataUnsafe?.start_param;if(/^evening_[1-5]$/.test(p||''))go('evening/'+p.split('_')[1]);else if(/^day_[0-5]$/.test(p||''))go('day/'+p.split('_')[1]);const back=()=>{if(page==='home')tg.BackButton?.hide();else tg.BackButton?.show()};back();window.addEventListener('hashchange',back);app.addEventListener('click',e=>{const a=e.target.closest('[data-telegram-link]');if(a&&tg.openTelegramLink){e.preventDefault();tg.openTelegramLink(a.href)}})}
window.addEventListener('load',initTelegram,{once:true});
window.visualViewport?.addEventListener('resize',()=>document.documentElement.classList.toggle('keyboard-open',window.innerHeight-window.visualViewport.height>150));
render();
