import assert from 'node:assert/strict';import fs from 'node:fs';
import {geometry,solidModel} from '../geometry.js';import {hullFaces,torusPoint,documentedTreeEdges} from '../audited-geometry.js';import {mainCatalog,isArchetype} from '../catalog.js';import {books} from '../library.js';import {education} from '../education.js';
const all=JSON.parse(fs.readFileSync(new URL('../symbols.json',import.meta.url))),catalog=mainCatalog(all);assert.equal(catalog.length,77);assert.equal(all.filter(isArchetype).length,7);assert.equal(new Set(catalog.map(x=>x.category)).size,12);assert.equal(books.length,8);
for(let[name,count,size]of [['ТЕТРАЭДР',4,3],['КУБ (ГЕКСАЭДР)',6,4],['ОКТАЭДР',8,3],['ИКОСАЭДР',20,3],['ДОДЕКАЭДР',12,5],['КУБООКТАЭДР',14,0]]){const m=solidModel(name),faces=hullFaces(m.vertices);assert.equal(faces.length,count);assert.equal(m.vertices.length-m.edges.length+faces.length,2);if(size)assert.ok(faces.every(f=>f.ids.length===size));else{assert.equal(faces.filter(f=>f.ids.length===3).length,8);assert.equal(faces.filter(f=>f.ids.length===4).length,6);}for(let face of faces){let lengths=face.ids.map((a,i)=>Math.hypot(...m.vertices[a].map((v,k)=>v-m.vertices[face.ids[(i+1)%face.ids.length]][k])));assert.ok(lengths.every(v=>Math.abs(v-lengths[0])<1e-8));}}
for(let u of [0,.7,2])for(let v of [0,.4,1.3,3]){let p=torusPoint(u,v),rho=Math.hypot(p[0],p[1]);assert.ok(Math.abs((rho-51)**2+p[2]**2-45**2)<1e-8);assert.ok(Math.hypot(...p.map((x,k)=>x-torusPoint(u+2*Math.PI,v+2*Math.PI)[k]))<1e-8);}
const egg=geometry('ЯЙЦО ЖИЗНИ').parameters;assert.equal(egg.projectedCenters.length,8);assert.deepEqual(egg.projectedCenters[0],egg.projectedCenters[1]);egg.projectedCenters.slice(2).forEach(p=>assert.ok(Math.abs(Math.hypot(p[0]-150,p[1]-150)-egg.radius*Math.sqrt(8/3))<1e-8));
assert.equal(documentedTreeEdges.length,22);assert.ok(!documentedTreeEdges.some(([a,b])=>a===5&&b===9));assert.ok(documentedTreeEdges.some(([a,b])=>a===7&&b===9));
for(let s of all){let e=education(s);assert.ok(!/SVG-элемент|JavaScript|использовани[ея] path/.test([e.geometry,e.history,...e.facts].join(' ')));if(s.name.startsWith('ЯНТРА '))assert.equal(e.mode,'interpretation');}
console.log('PASS: 77 catalog/7 archived, all source data retained, polyhedron facets/edges/Euler, torus equations/closed paths, diagonal Egg model, corrected Hermetic graph, 8 books, no implementation facts in education.');
