import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const root=new URL('../dist/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8');
async function setup(saved){
 const dom=new JSDOM(html,{url:'https://game.test/',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window;w.matchMedia=()=>({matches:true});w.open=()=>({});
 w.fetch=async p=>({ok:true,json:async()=>p==='/api/me'?{signedIn:false,profile:null}:JSON.parse(fs.readFileSync(new URL(p.replace(/^\.\//,''),root),'utf8'))});
 if(saved)w.localStorage.setItem('tochka-sily-game-v2',saved);
 const ctx=dom.getInternalVMContext(),run=s=>vm.runInContext(s,ctx);
 for(const script of w.document.querySelectorAll('script[src^="./"]'))run(fs.readFileSync(new URL(script.getAttribute('src').slice(2),root),'utf8'));
 await new Promise(r=>setTimeout(r,40));run('ge("journey-cinema").hidden=true');
 return {dom,w,run};
}
const names=[];
for(let level=0;level<5;level++){
 let t=await setup();
 t.run(`game=defaultGame();game.originalRequest="Исходный запрос";game.request="Актуальный запрос";game.stage="board";game.introSeen=true;game.level=${level};game.energy=${level===3?25:8};game.position=routeCells().findIndex(c=>c.type==='guardian');persist();renderGame();handleCell()`);
 names.push(t.run('routeCells()[game.position].name'));
 assert.equal(t.run('game.bodyMarks.length'),0);
 assert.equal(t.w.document.querySelectorAll('#modal-content textarea').length,1,'one required field');
 assert.equal(t.w.document.querySelector('#modal-content input,#modal-content select,.body-map'),null);
 assert.doesNotMatch(t.w.document.getElementById('modal-content').textContent,/Отметьте|отклик в теле|чакр/i);
 let field=t.w.document.getElementById('guardian-insight'),button=t.w.document.querySelector('#modal-buttons button');
 assert.equal(button.disabled,true);
 for(const text of ['','   ','Д','Д ']){field.value=text;field.dispatchEvent(new t.w.Event('input'));assert.equal(button.disabled,true)}
 field.value='Да';field.dispatchEvent(new t.w.Event('input'));assert.equal(button.disabled,false);
 const before=t.run('crystalBalance()'),energy=t.run('game.energy'),runId=t.run('game.runId');
 button.click();button.click();button.dispatchEvent(new t.w.Event('click'));
 assert.match(t.w.document.getElementById('modal-title').textContent,/КЛЮЧ ПОЛУЧЕН/);
 assert.equal(t.run(`game.keys[${level}]`),true);
 assert.equal(t.run('game.insights.length'),1);
 assert.equal(t.run('crystalBalance()'),before+1,'Guardian crystal and key are distinct once-only rewards');
 assert.equal(t.run('game.energy'),energy,'a key does not change energy');
 assert.equal(t.run('game.insights[0].requestAtTime'),'Актуальный запрос');
 assert.equal(t.run('game.insights[0].runId'),runId);
 const record=JSON.parse(t.run('JSON.stringify(game.guardianRecords[0])'));
 for(const key of ['guardianId','guardianType','levelId','insightText','guardianCompleted','keyGranted','keyConsumed','completedAt'])assert(key in record);
 assert.equal(record.insightText,'Да');assert.equal(record.guardianCompleted,true);assert.equal(record.keyGranted,true);assert.equal(record.keyConsumed,false);
 assert.equal(t.run('game.journal.guardians.length'),1);
 assert.match(t.run('journalHtml(game.journal)'),new RegExp(record.guardianType));
 assert.match(t.run('journalHtml(game.journal)'),/Да/);
 assert.match(t.run('circleWalletHtml(99)'),/🔑 1\/1 ✓/,'energy animation never drops the key counter');
 assert.match(t.w.document.getElementById('circle-wallet').textContent,/⚡.*💎.*🔑 1\/1 ✓/);
 assert(t.w.document.getElementById('circle-key').classList.contains('key-owned'));
 t.run('closeModal();handleCell()');assert.match(t.w.document.getElementById('modal-title').textContent,/УЖЕ ПОЛУЧЕН/);
 assert.match(t.w.document.getElementById('modal-content').textContent,/Да/);assert.equal(t.w.document.getElementById('guardian-insight'),null);
 const saved=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(saved);
 assert.equal(t.run('game.guardianRecords[0].guardianCompleted'),true);assert.equal(t.run('crystalBalance()'),before+1);
 t.run('handleCell()');assert.match(t.w.document.getElementById('modal-title').textContent,/УЖЕ ПОЛУЧЕН/);
 assert.equal(t.run('game.insights.length'),1);
 t.run(`closeModal();game.laps[${level}]=1;game.position=0;persist();renderGame()`);
 assert.equal(t.run('canPassPortal()'),true,'no body, need or additional Guardian fields gate the portal');
 t.run('showPortalChoice()');assert.match(t.w.document.getElementById('modal-content').textContent,/КЛЮЧ ЕСТЬ/);
 assert(t.w.document.querySelector('#modal-buttons button').textContent.includes('ВОЙТИ В ПОРТАЛ'));
 t.w.document.querySelector('#modal-buttons button').click();
 assert.equal(t.run('game.guardianRecords[0].keyConsumed'),true);
 await new Promise(r=>setTimeout(r,145));
 assert.equal(t.run('game.stage'),level===4?'center':['intro','intro2','intro3','intro4','intro5'][level+1]);
 const transitioned=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(transitioned);
 assert.equal(t.run('game.guardianRecords[0].keyConsumed'),true);assert.equal(t.run('game.insights.length'),1);
 if(level<4)assert.match(t.w.document.getElementById('circle-key').textContent,/0\/1/);
 t.dom.window.close();
}
const noKey=await setup();noKey.run('game.originalRequest="Запрос";game.stage="board";game.laps[0]=1;persist();renderGame();showPortalChoice()');
assert.equal(noKey.run('canPassPortal()'),false);assert.match(noKey.w.document.getElementById('modal-title').textContent,/ТЕБЕ НУЖЕН КЛЮЧ/);
assert.doesNotMatch(noKey.w.document.getElementById('modal-content').textContent,/отклик|чакр/i);
noKey.run('game.level=3;game.keys[3]=true;game.laps[3]=1;game.energy=24');assert.equal(noKey.run('canPassPortal()'),false,'existing 25-energy rule retained');
noKey.run('game.energy=25');assert.equal(noKey.run('canPassPortal()'),true);noKey.dom.window.close();
const legacy=await setup();legacy.run('game.level=1;game.originalRequest="Запрос";game.keys[1]=true;game.insights.push({kind:"Хранитель выбора",level:1,text:"Мое старое осознание",at:"2026-10-02T10:00:00Z"});ensureGuardians();persist()');
const legacySaved=legacy.w.localStorage.getItem('tochka-sily-game-v2');legacy.dom.window.close();const restored=await setup(legacySaved);restored.run('showGuardian()');
assert.match(restored.w.document.getElementById('modal-content').textContent,/Мое старое осознание/);assert.equal(restored.run('crystalBalance()'),0,'migration does not grant extra crystals');restored.dom.window.close();
console.log('PASS all five Guardians:',names.join(' / '));
console.log('PASS text-only 2-character input, once-only key/crystal, request/run metadata, central wallet, repeat/reload, portal/consumption, next-stage reset, legacy migration, retained lap/energy requirements');
