import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
const root=new URL('../dist/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8');
async function setup(saved){const dom=new JSDOM(html,{url:'https://game.test/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:true});w.fetch=async p=>({ok:true,json:async()=>p==='/api/me'?{signedIn:false,profile:null}:JSON.parse(fs.readFileSync(new URL(p.slice(2),root)))});if(saved)w.localStorage.setItem('tochka-sily-game-v2',saved);const context=dom.getInternalVMContext(),run=s=>vm.runInContext(s,context);for(const script of w.document.querySelectorAll('script[src^="./"]'))run(fs.readFileSync(new URL(script.getAttribute('src').slice(2),root),'utf8'));await new Promise(r=>setTimeout(r,40));run('ge("journey-cinema").hidden=true');return {dom,w,run}}
const tick=()=>new Promise(r=>setTimeout(r,25));
let t=await setup();t.run('game.originalRequest="Мой запрос";game.request=game.originalRequest;game.stage="board"');
const baseline=JSON.parse(fs.readFileSync(new URL('../docs/routes-before-redesign.json',import.meta.url)));
for(let level=0;level<5;level++){
 const {run,w}=t;run(`game.level=${level};game.position=routeCells().length-2;game.energy=10;boardLevelRendered=-1;renderGame()`);assert.equal(w.document.querySelectorAll('.circle-cells .cell-hit').length,baseline[level].cells.length);assert.equal(w.document.querySelectorAll('.circle-cells .cell-illustration').length,baseline[level].cells.length,'each existing cell has mapped artwork');
 for(const width of [320,390,430,768,1440]){assert(run(`routeCells().every(c=>c.x/100*${width}>0&&c.x/100*${width}<${width}&&c.y/100*${width}>0&&c.y/100*${width}<${width})`));}const types=Array.from(run('routeCells().map(c=>c.type)'));assert.deepEqual(types,baseline[level].cells.map(c=>c.type==='blank'?'archetype':c.type));assert(run('routeCells().every(c=>c.nextId&&c.id&&c.path&&c.x>0&&c.x<100)'));assert.equal(w.document.getElementById('roll-button').closest('.circle-center').className,'circle-center');
 const movement=run('moveSteps(3)');await tick();assert.equal(run('game.position'),0,'pause exactly at start');assert.equal(run('game.pendingMovement.remaining'),1);assert.equal(run('game.energy'),10);assert.equal(w.document.getElementById('modal-title').textContent,'ПОЛНЫЙ КРУГ ПРОЙДЕН');run('closeModal()');assert.equal(w.document.getElementById('game-modal').hidden,false,'outside/Escape cannot bypass decision');
 const button=w.document.querySelector('#modal-buttons button');button.click();button.click();assert.equal(button.disabled,true,'button blocked synchronously');await movement;assert.equal(run('game.position'),1,'remaining step resumes');assert.equal(run('game.energy'),11);const event=run('game.lapEnergyEvents.at(-1)');assert.equal(event.state,'accepted');assert.equal(event.credited,true);assert.equal(run(`game.energyHistory.filter(e=>e.eventId===${JSON.stringify(event.id)}).length`),1);assert.equal(run(`decideLapEnergy(${JSON.stringify(event.id)},"accepted")`),false);
 run('game.position=routeCells().length-1;game.circleProgress[game.level]=game.position');const next=run('moveSteps(1)');await tick();w.document.querySelectorAll('#modal-buttons button')[1].click();await next;assert.equal(run('game.energy'),11);assert.equal(run('game.lapEnergyEvents.at(-1).state'),'declined');assert.equal(run('game.lapEnergyEvents.at(-1).credited'),false);assert.notEqual(run('game.lapEnergyEvents.at(-1).id'),event.id);assert.equal(run('decideLapEnergy(game.lapEnergyEvents.at(-1).id,"accepted")'),false);
}
// Reload while the choice is pending, including a die turn with unfinished movement.
t.run('game.level=0;game.position=routeCells().length-1;game.circleProgress[0]=game.position;game.energy=20;game.portalDeferred=true;game.pendingRoll={roll:2,turn:game.turn};closeModal()');t.run('moveSteps(2)');await tick();const pendingSaved=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(pendingSaved);assert.equal(t.run('pendingLapEnergy().state'),'pending');t.w.document.querySelector('#modal-buttons button').click();await tick();assert.equal(t.run('game.energy'),21);assert.equal(t.run('game.position'),1);assert.equal(t.run('game.pendingRoll'),null);assert.equal(t.run('game.lastRoll'),2);const acceptedSaved=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(acceptedSaved);assert.equal(t.run('pendingLapEnergy()'),null);assert.equal(t.run('game.energy'),21);assert.equal(t.run('decideLapEnergy(game.lapEnergyEvents.at(-1).id,"accepted")'),false);
// Card movement resumes its effect sequence after reload without applying energy twice.
t.run('game=defaultGame();game.originalRequest="Запрос";game.request=game.originalRequest;game.stage="board";game.level=3;game.position=routeCells().length-1;game.energy=5;game.seenDecks={"Особое событие":true};boardLevelRendered=-1;renderGame();globalThis.effectCard={id:"event-test",deck:"Особое событие",title:"Тест",effects:[{type:"energy",amount:2},{type:"move",steps:2},{type:"energy",amount:3}]};cardManifest[effectCard.deck].push(effectCard);game.openedCards.push({id:effectCard.id,deck:effectCard.deck,eventId:"effects-one"});acceptCard(effectCard)');await tick();assert.equal(t.run('game.energy'),7);const effectsSaved=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(effectsSaved);t.run('cardManifest["Особое событие"].push({id:"event-test",deck:"Особое событие",title:"Тест",effects:[{type:"energy",amount:2},{type:"move",steps:2},{type:"energy",amount:3}]})');t.w.document.querySelectorAll('#modal-buttons button')[1].click();await tick();assert.equal(t.run('game.energy'),10,'effect before pause not replayed, next effect applied once');assert.equal(t.run('game.acceptedCards.length'),1);assert.equal(t.run('game.pendingCardCompletion'),null);assert.equal(t.run('game.position'),1);
t.run('closeModal();game=defaultGame();game.originalRequest="Запрос";game.stage="board"');await t.run('moveSteps(-2)');await t.run('moveSteps(2)');assert.equal(t.run('game.laps[0]'),0,'backward then forward across start is not a full lap');assert.equal(t.run('game.lapEnergyEvents.length'),0);t.dom.window.close();console.log('PASS lap: five routes and sectors, accept once/double click, decline final, unique laps, pause/remainder, pending/accepted reload, die/card resume, history persists');
