import {fileURLToPath} from 'node:url';import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
const nodes=new Map();const element=id=>{if(!nodes.has(id))nodes.set(id,{id,hidden:false,style:{},value:'',textContent:'',innerHTML:'',disabled:false,clientWidth:800,scrollWidth:800,clientHeight:800,scrollLeft:0,dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},append(){},replaceChildren(){},focus(){},setAttribute(){},querySelector(){return element('nested')},querySelectorAll(){return []}});return nodes.get(id)};
const local=new Map();const ctx=vm.createContext({console,Math,Date,Promise,globalThis:null,localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},document:{getElementById:element,querySelector:element,querySelectorAll:()=>[],createElement:()=>element('created'),body:element('body'),addEventListener(){}},window:{},setTimeout:fn=>{fn();return 0},clearTimeout(){},fetch:async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(root+path.slice(2),'utf8'))})});ctx.globalThis=ctx;
vm.runInContext(fs.readFileSync(root+'overview.js','utf8'),ctx);vm.runInContext(fs.readFileSync(root+'life-spheres.js','utf8'),ctx);vm.runInContext(fs.readFileSync(root+'game.js','utf8'),ctx);
const run=code=>vm.runInContext(code,ctx);
const seq=['portal','archetype','action','goal','creationInsight','creation','key','action','event','archetype','guardian','action','event','support','creation','goal','action','support','creation','archetype','support'];
assert.deepEqual(Array.from(run('level5Cells.map(c=>c.type)')),seq);
assert(run('level5Cells.every(c=>c.x>0&&c.x<100&&c.y>0&&c.y<100)'));
run('game.level=3;game.position=0;game.stage="board";game.originalRequest="Запрос";game.keys[3]=true;game.laps[3]=1;game.energy=24');
assert.equal(run('canPassPortal()'),false);
run('game.energy=25;pendingPortal=false;globalThis.visited=[];renderGame=()=>visited.push(game.position);transitionTo(4)');
assert.equal(run('game.level'),4);assert.equal(run('game.position'),0);assert.equal(run('game.energy'),25);assert.equal(run('game.stage'),'intro5');
run('game.stage="board";game.position=18');await run('moveSteps(5)');
assert.deepEqual(Array.from(ctx.visited.slice(-7)),[18,19,20,0,1,2,2]);assert.equal(run('game.laps[4]'),1);assert.equal(run('game.energy'),25);
run('game.position=6;showKey=()=>{};handleCell()');assert.equal(run('game.keys[4]'),true);
run('globalThis.view=null;showModal=(...args)=>{view=args};showPortalChoice()');assert.equal(ctx.view[3].length,2);assert.match(ctx.view[3][0].label,/Центр/);
ctx.view[3][1].action();assert.equal(run('game.stage'),'board');
run('pendingPortal=false;showPortalChoice()');ctx.view[3][0].action();assert.equal(run('game.stage'),'center');assert.equal(run('game.position'),0);
run('game.stage="board";game.energy=7;game.lifeGoals=[];game.energyHistory=[];game.creationActions=[]');
run('showGoalEditor()');element('goal-sphere').value='work';element('goal-title').value='Запустить проект';element('goal-energy').value='10';ctx.view[3][0].action();assert.match(element('goal-feedback').textContent,/Доступно только 7/);assert.equal(run('game.energy'),7);
element('goal-energy').value='5';ctx.view[3][0].action();assert.match(ctx.view[2],/Подтвердить/);const confirm=ctx.view[3][0].action;confirm();confirm();assert.equal(run('game.energy'),2);assert.equal(run('directedEnergy()'),5);assert.equal(run('game.lifeGoals.length'),1);assert.equal(run('game.energyHistory.length'),1);
run('showGoalConfirm({sphereId:"body",title:"Здоровье",amount:2})');ctx.view[3][0].action();assert.equal(run('game.energy'),0);assert.equal(run('directedEnergy()'),7);assert.equal(run('game.lifeGoals.length'),2);assert.equal(run('game.energy+directedEnergy()'),7);
run('showSphereTablet()');assert.match(ctx.view[2],/Запустить проект/);assert.match(ctx.view[2],/Здоровье/);assert.match(ctx.view[2],/Направлено 7 ⚡/);
const snapshot=JSON.parse(local.get('tochka-sily-game-v2'));assert.equal(snapshot.lifeGoals.length,2);assert.equal(snapshot.energyHistory.length,2);assert.equal(snapshot.energy,0);
run('confirmEnergyReturn(game.lifeGoals[0].id)');ctx.view[3][0].action();assert.equal(run('game.energy'),5);assert.equal(run('directedEnergy()'),2);assert.equal(run('game.energyHistory.length'),3);
run('game.position=2;showCreationAction()');element('modal-text').value='Да';ctx.view[3][0].action();assert.equal(run('game.creationActions.length'),1);assert.equal(run('game.insights.at(-1).text'),'Да');
run('game.position=4;showShortReflection("Чего я хочу на самом деле?","Осознание","Чего я хочу?")');element('modal-text').value='Да';ctx.view[3][0].action();assert.equal(run('game.insights.at(-1).level'),4);
run('game.position=10;showShortReflection("Хранитель будущего","Хранитель будущего","Что создаю?")');element('modal-text').value='Будущее';ctx.view[3][0].action();assert.equal(run('game.futureGuardianInsight'),'Будущее');
await new Promise(setImmediate);const cards=JSON.parse(fs.readFileSync(root+'cards.json'));assert.equal(cards['Творение'].length,24);assert(cards['Творение'].every(c=>c.fields.length===4));assert.equal(cards['Особое событие'].filter(c=>c.availableLevels.includes(5)).length,13);
const old=run('showDrawnCard');run('showDrawnCard=c=>globalThis.drawn=c;game.position=5;cardFor("Творение")');assert.equal(ctx.drawn.deck,'Творение');ctx.showDrawnCard=old;
run('showDrawnCard(cardManifest["Богини / Архетипы силы"][0])');assert(ctx.view[2].indexOf('<img')<ctx.view[2].indexOf('<h3>'));
const stored=JSON.parse(local.get('tochka-sily-game-v2'));assert.equal(stored.lifeGoals.length,2);assert.equal(stored.creationActions.length,1);assert.equal(stored.futureGuardianInsight,'Будущее');
console.log('PASS: entry gate, 20 cells, 18+5 portal, key, center, 24 cards, event/support, goals, over-allocation, confirmation, multiple spheres, return, journal, persistence');
