import {fileURLToPath} from 'node:url';import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
const nodes=new Map();
const element=id=>{if(!nodes.has(id)){const n={id,hidden:false,style:{},value:'',textContent:'',innerHTML:'',disabled:false,clientWidth:800,scrollWidth:800,clientHeight:800,scrollLeft:0,classList:{add(){},remove(){},toggle(){}},addEventListener(){},append(){},replaceChildren(){},focus(){},setAttribute(){},querySelector(){return element('nested')},querySelectorAll(){return []}};nodes.set(id,n)}return nodes.get(id)};
const local=new Map();
const ctx=vm.createContext({console,Math,Date,Promise,globalThis:null,localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},document:{getElementById:element,querySelector:element,querySelectorAll:()=>[],createElement:()=>element('created'),body:element('body'),addEventListener(){}},window:{},setTimeout:fn=>{fn();return 0},clearTimeout(){},fetch:async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(root+path.slice(2),'utf8'))})});ctx.globalThis=ctx;
vm.runInContext(fs.readFileSync(root+'overview.js','utf8'),ctx);
vm.runInContext(fs.readFileSync(root+'life-spheres.js','utf8'),ctx);vm.runInContext(fs.readFileSync(root+'game.js','utf8'),ctx);
const run=(code)=>vm.runInContext(code,ctx);
const sequence=['portal','event','energy','ocean','returnInsight','return','key','support','event','energy','archetype','guardian','energy','return','event','archetype','energy','return','view','event','energy'];
assert.deepEqual(Array.from(run('level4Cells.map(c=>c.type)')),sequence);
assert(run('level4Cells.every(c=>c.x>0&&c.x<100&&c.y>0&&c.y<100)'));
run('game.level=3;game.position=18;game.stage="board";game.originalRequest="Запрос";game.energy=18;game.keys[3]=true;globalThis.visited=[];renderGame=()=>visited.push(game.position)');
await run('moveSteps(5)');
assert.deepEqual(Array.from(ctx.visited),[18,19,20,0,1,2,2]);
assert.equal(run('game.laps[3]'),1);assert.equal(run('game.energy'),18);assert.equal(run('pendingPortal'),true);
run('pulseEnergy=()=>{};game.position=2;handleCell()');assert.equal(run('game.energy'),19);
run('game.position=6;showKey=()=>{};handleCell()');assert.equal(run('game.keys[3]'),true);
run('game.energy=24');assert.equal(run('canPassPortal()'),false);
run('game.energy=25');assert.equal(run('canPassPortal()'),true);
run('globalThis.portalView=null;showModal=(...args)=>{portalView=args};showPortalChoice()');assert.equal(ctx.portalView[3].length,2);assert.match(ctx.portalView[3][1].label,/Остаться/);
run('game.energy=19;showPortalChoice()');assert.match(ctx.portalView[2],/19 ⚡ \/ 25 ⚡/);
run('game.energy=25;game.keys[3]=true;game.position=0;transitionTo(4)');assert.equal(run('game.level'),4);assert.equal(run('game.position'),0);assert.equal(run('game.energy'),25);
const saved=JSON.parse(local.get('tochka-sily-game-v2'));assert.equal(saved.level,4);assert.equal(saved.energy,25);assert.equal(saved.laps[3],1);
const cards=JSON.parse(fs.readFileSync(root+'cards.json'));assert.equal(cards['Возвращение энергии'].length,24);assert(cards['Возвращение энергии'].every(c=>c.fields.length===6));
const images=JSON.parse(fs.readFileSync(root+'card-images.json'));assert(cards['Богини / Архетипы силы'].every(c=>images[c.id]&&fs.existsSync(root+images[c.id])));
assert.equal(run('hasReflectionText("Да")'),true);assert.equal(run('hasReflectionText("  ")'),false);assert.equal(run('hasReflectionText("А")'),false);

await new Promise(setImmediate);
const originalDraw=run('showDrawnCard');
run('game.level=3;game.position=5;globalThis.deckDraw=null;showDrawnCard=c=>deckDraw=c;cardFor("Возвращение энергии")');
assert.equal(ctx.deckDraw.deck,'Возвращение энергии');assert.equal(run('game.openedCards.at(-1).id'),ctx.deckDraw.id);
run('game.position=1;cardFor("Особое событие")');assert.equal(ctx.deckDraw.deck,'Особое событие');assert(ctx.deckDraw.availableLevels.includes(4));
run('game.position=18;cardFor("Другой взгляд")');assert.equal(ctx.deckDraw.deck,'Другой взгляд');
ctx.showDrawnCard=originalDraw;
run('game.position=7;globalThis.imageView=null;showModal=(...args)=>{imageView=args};showDrawnCard(cardManifest["Богини / Архетипы силы"][0])');
assert(ctx.imageView[2].indexOf('<img')<ctx.imageView[2].indexOf('<h3>'));
assert(ctx.imageView[2].includes('Афродита'));
run('game.position=11;showShortReflection("Хранитель истины","Хранитель истины","Что я заметила?")');
element('modal-text').value='Да';ctx.imageView[3][0].action();
assert.equal(run('game.returnGuardianInsight'),'Да');assert.equal(run('game.insights.at(-1).level'),3);
console.log('PASS: route, 18+5 wrap, lap, energy, key, 25 gate, optional stay, persistence, 24 cards, 20 images, short reflection');
