import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
const root=new URL('../dist/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8');
async function setup(saved){const dom=new JSDOM(html,{url:'https://game.test/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:true});w.fetch=async p=>({ok:true,json:async()=>p==='/api/me'?{signedIn:false,profile:null}:JSON.parse(fs.readFileSync(new URL(p.slice(2),root)))});if(saved)w.localStorage.setItem('tochka-sily-game-v2',saved);const ctx=dom.getInternalVMContext(),run=s=>vm.runInContext(s,ctx);for(const script of w.document.querySelectorAll('script[src]'))run(fs.readFileSync(new URL(script.getAttribute('src').slice(2),root),'utf8'));await new Promise(r=>setTimeout(r,40));run('ge("journey-cinema").hidden=true');return {dom,w,run}}
let t=await setup();t.run('game.originalRequest="Мой исходный запрос";game.request=game.originalRequest;game.stage="board";game.energy=8;renderGame();game.position=5;handleCell()');assert.match(t.w.document.getElementById('modal-content').textContent,/Зачем нужна эта клетка/);assert.match(t.w.document.getElementById('modal-content').textContent,/Мой исходный запрос/);assert.equal(t.run('game.energy'),8);assert.equal(t.run('crystalBalance()'),0);t.run('closeModal()');assert.equal(t.w.document.getElementById('game-modal').hidden,false);t.w.document.querySelector('#modal-buttons button').click();assert.equal(t.run('game.requestHistory.length'),0);assert.equal(t.run('game.requestReviews[0].state'),'kept');assert.equal(t.run('currentRequest()'),'Мой исходный запрос');
t.run('game.turn++;showOcean()');assert.equal(t.w.document.querySelector('.ocean-help').tagName,'DETAILS');assert(!t.w.document.getElementById('modal-content').textContent.startsWith('Зачем'));t.w.document.querySelectorAll('#modal-buttons button')[1].click();let field=t.w.document.getElementById('ocean-request');field.value='   ';field.dispatchEvent(new t.w.Event('input'));assert.equal(t.w.document.querySelector('#modal-buttons button').disabled,true);field.value='Я хочу опору';field.dispatchEvent(new t.w.Event('input'));const save=t.w.document.querySelector('#modal-buttons button');save.click();save.click();assert.equal(t.run('game.originalRequest'),'Мой исходный запрос');assert.equal(t.run('currentRequest()'),'Я хочу опору');assert.equal(t.run('game.requestHistory.length'),1);assert.equal(t.run('game.energy'),8);assert.equal(t.run('crystalBalance()'),0);
t.run('cardFor("Диагностика")');t.w.document.querySelector('#modal-buttons button').click();assert.match(t.w.document.querySelector('.card-request').textContent,/Я хочу опору/);assert.equal(t.run('game.openedCards.at(-1).requestAtTime'),'Я хочу опору');t.run('closeModal();showBodyMap(null,1)');assert.match(t.w.document.querySelector('label[for=body-note]').textContent,/Заметка о теле/);assert(!t.w.document.querySelector('.crystal-save'));t.w.document.getElementById('body-note').value='Да';t.w.document.querySelector('#modal-buttons button').click();assert.equal(t.run('game.bodyMarks.length'),1);assert.equal(t.run('crystalBalance()'),0,'body note and chosen chakra do not reward');
t.run('game.turn++;showOcean()');t.w.document.querySelectorAll('#modal-buttons button')[1].click();field=t.w.document.getElementById('ocean-request');field.value='Мне важно выбирать себя';field.dispatchEvent(new t.w.Event('input'));const draftSaved=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(draftSaved);assert.equal(t.w.document.getElementById('ocean-request').value,'Мне важно выбирать себя','pending editor and draft restore');t.w.document.querySelector('#modal-buttons button').click();assert.equal(t.run('game.requestHistory.length'),2);assert.equal(t.run('game.originalRequest'),'Мой исходный запрос');assert.equal(t.run('currentRequest()'),'Мне важно выбирать себя');assert.equal(t.run('game.journal.requestHistory.length'),2);const report=t.run('printDocument(game.journal)');assert.match(report,/После Океана иллюзий я увидела свой запрос так/);assert.match(report,/Я хочу опору/);assert.match(report,/Мне важно выбирать себя/);assert.match(report,/Мой исходный запрос/);
t.run('showOcean()');t.w.document.querySelector('#modal-buttons button').click();assert.equal(t.run('game.requestHistory.length'),2,'keeping current request never creates change');assert.equal(t.run('currentRequest()'),'Мне важно выбирать себя');const state=t.w.localStorage.getItem('tochka-sily-game-v2');t.dom.window.close();t=await setup(state);assert.equal(t.run('currentRequest()'),'Мне важно выбирать себя');assert.equal(t.run('game.pendingOcean'),null);
await t.run('showTreasury()');assert.equal(t.w.document.querySelectorAll('.gift').length,8);assert.deepEqual(Array.from(t.run('Player.economy.gifts.map(g=>g.cost)')),[50,80,120,170,230,300,400,600]);assert(t.w.document.querySelectorAll('.gift progress').length===8);assert([...t.w.document.querySelectorAll('[data-gift]')].every(b=>b.disabled));assert.match(t.w.document.getElementById('modal-content').textContent,/Мандалы Египта/);assert.match(t.w.document.getElementById('modal-content').textContent,/скидка 50%/);
t.dom.window.close();console.log('PASS ocean: first/repeat help, keep/change, empty guard, immutable original, full history/print, current card context, pending draft reload, no energy/crystal/turn penalty, body no reward, 8 gifts');
