import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=new URL('../dist/',import.meta.url),storage=new Map(),timers=new Map(),nodes=[],listeners={};let created=0,timerId=0;
const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}});
function node(){const n={gain:param(),frequency:param(),Q:param(),threshold:param(),knee:param(),ratio:param(),connect(to){return to},disconnect(){},start(t){this.started=t},stop(t){this.stopped=t}};nodes.push(n);return n}
class Audio{constructor(){created++;this.currentTime=10;this.state='suspended';this.sampleRate=8000;this.destination=node()}resume(){this.state='running';return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}createGain(){return node()}createDynamicsCompressor(){return node()}createOscillator(){return node()}createBufferSource(){return node()}createBiquadFilter(){return node()}createBuffer(_,len){return {getChannelData:()=>new Float32Array(len)}}}
const ctx=vm.createContext({console,Math,Promise,window:{AudioContext:Audio},document:{hidden:false,getElementById:()=>null,addEventListener:(n,fn)=>listeners[n]=fn},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId},clearTimeout:id=>timers.delete(id),fetch:async()=>{throw Error('missing audio')},globalThis:null});ctx.globalThis=ctx;
const run=s=>vm.runInContext(s,ctx);for(const f of ['sound-config.js','sound-manager.js'])run(fs.readFileSync(new URL(f,root),'utf8'));
const sound=ctx.SoundManager;await sound.play('intro');assert.equal(created,0,'no context or autoplay before user interaction');sound.unlock();await sound.play('intro');assert.equal(created,1);assert(sound.active.size>0);assert.equal(sound.master.gain.value,.24);
sound.stop();await sound.play('energyGain');const energy=[...sound.active];assert.equal(energy.length,4,'one accumulation sequence, not per-unit repetitions');assert(energy.some(r=>r.source.started>=11.05),'arrival chime follows flight');await sound.play('energyGain');assert.equal(sound.active.size,4,'duplicate event throttled');
sound.setEnabled(false);assert.equal(sound.active.size,0);assert.equal(timers.size,0);assert.equal(storage.get('tochka-sily-sound'),'off');await sound.play('guardian');assert.equal(sound.active.size,0);sound.setEnabled(true);sound.context.currentTime=20;await sound.play('guardian');assert(sound.active.size>0);
sound.context.currentTime=30;sound.loop('portalIdle');await new Promise(setImmediate);assert(timers.size>0);sound.stop('portal');assert.equal(timers.size,0);assert([...sound.active].every(r=>r.group!=='portal'));
sound.context.currentTime=40;const queued=sound.play('support');sound.setEnabled(false);await queued;assert.equal(sound.active.size,0,'mute cancels queued cues');
sound.setEnabled(true);ctx.document.hidden=true;listeners.visibilitychange();assert.equal(sound.active.size,0);await sound.play('intro');assert.equal(sound.active.size,0);ctx.document.hidden=false;
run('soundDesign.events.support.url="./missing.wav"');sound.context.currentTime=50;sound.unlock();await sound.play('support');assert.equal(sound.active.size,0,'missing replacement asset cannot break game');
assert.equal(Object.keys(ctx.soundDesign.events).length,22);assert.equal(new Set(ctx.soundDesign.events.stepReveal.steps).size,5);
const newSound=run('new GameSoundManager(soundDesign)');storage.set('tochka-sily-sound','off');assert.equal(run('new GameSoundManager(soundDesign).enabled'),false);
console.log('PASS sound: gesture-only startup, quiet master, flight arrival timing, one gain sequence, duplicate guard, persistent mute, queue/loop cancellation, hidden tab, missing asset fallback, 22 events and five step motifs');
